# Identificação do participante

Preencha a célula abaixo com sua matrícula no formato F + 7 algarismos, sem dígito verificador.

Exemplo:

    chaveF = "F1234567"

In [1]:
chaveF = "F6779951"

# Desafio Engenharia de Dados

A Dipes precisa fazer o acompanhamento do cumprimento dos indicadores de algumas Unidades Estratégicas e solicitou à UAN o desenvolvimento de um dashboard. Os colegas da equipe de Dataviz identificaram a necessidade de <b>disponibilização de algumas bases de dados</b> para desenvolvimento do dashboard, principalmente para o acompanhamento das <b>Trilhas de Capacitação</b> das Unidades Estratégicas:

|PREFIXO|SIGLA|
|---|---|
|8008|DIREC|
|8556|DICRE|
|8559|DIPES|
|8593|DIGOV|
|9797|UCI|
|9880|DIMEP|
|9968|UAN|
|9973|DIEMP|

A equipe de Engenharia de Dados foi então acionada para preparação das bases de dados conforme abaixo detalhado.

<b>Dados essenciais:</b>
- acompanhamento do cumprimento do indicador de capacitação por matrícula dos funcionários das Diretorias alvo da análise
- acompanhamento do cumprimento por UOR das Unidades Estratégicas, contendo a Vice-Presidência jurisdicionante

Além disso, a equipe de Dataviz solicitou que a equipe de engenharia reunisse algumas informações úteis para análise e levantamento de insights, tais como:
- dados de função, escolaridade, idade, tempo de banco e estado civil de cada funcionário das dependências citadas.
- detalhamentos sobre a área dos cursos que os funcionários concluíram nos últimos 3 anos para identificação do perfil.

# Orientações Gerais:

1) Inclua sua matrícula na seção de Identificação, no início deste Notebook.

2) **Link para envio das soluções:**

- https://envio-academiabb.bb.com.br/

    - **Atenção:** não serão acatadas outras formas de envio. O link acima permite acesso com senha de portais externos.

3) Selecione a Trilha Engenharia ao enviar.

**Nome do arquivo:** cada participante deverá baixar o presente arquivo e renomeá-lo de modo a conter:

- A matrícula com F maiúsculo, sete algarismos e sem dígito (FXXXXXXX)

- A trilha a qual a entrega se refere em letras minúsculas: engenharia

- O nome não deve conter espaços em branco. Substitua-os por “_”.

- O versionamento será gerado automaticamente na subida do arquivo, por meio do timestamp do envio.

    - Exemplo1: F1234567_engenharia.ipynb

    - Exemplo2: F1234567_engenharia_v3.ipynb

**Formato:** .ipynb

- **Atenção:** não carregar nenhum outro formato de arquivo, pois será ignorado

**Prazo final:** até às 18h (horário de Brasília) do dia 20/09/2024.

## Requerimentos de versões

Para construção do desafio em qualquer ambiente diferente do [labblite](https://labblite.bb.com.br/), deverão ser utilizadas as versões de biblioteca abaixo especificadas:

|Biblioteca|Versão|
|---|---|
|pandas|1.5.2 ou inferior|
|numpy|1.23.5 ou inferior|
|unidecode|1.3.8 ou inferior|
|pathlib|sem indicativo de versão|
|glob|sem indicativo de versão|

Essas versões são padrão no labblite, e você pode checar após importação da biblioteca por meio da instrução:
    
    print(nome_biblioteca. __version__)

Caso identifique a necessidade de utilização de alguma biblioteca diferente das listadas acima, entre em contato com a comissão organizadora para verificar a possibilidade de utilização no script, sob o risco de gerar erros durante a validação.

## Pode:

- Inserir células no notebook.

    Obs: as células adicionadas após a seção do Boletim de Soluções não surtirão efeitos para fins de validação dos resultados dos exercícios propostos.

- Fazer vários envios (tantos quantos forem necessários).

- Nas máquinas do Banco, desenvolver na plataforma [Labblite](https://labblite.bb.com.br/)

- O participante que optar por desenvolver no computador pessoal, poderá utilizar qualquer plataforma que permita a execução de scripts em Python, desde que atente para as versões das bibliotecas mencionadas na seção "Requerimentos de versões" acima especificada.
    
    Atenção: consulte as versões homologadas pelo Banco no aplicativo <b>BB Verifica Software</b> antes de instalar qualquer aplicativo nas máquinas corporativas.

## Não pode:

- Compartilhar arquivos/código, sob pena de desclassificação de todas as partes envolvidas.

- Alterar as bases de dados disponibilizadas. Os itens contidos na pasta “bases” devem permanecer inalterados quanto a:
    - Nome e tipo dos arquivos/pastas
    - Conteúdo
    - Estrutura das pastas iniciando em “bases”

- Descompactar os arquivos correspondentes às bases de dados. Os arquivos disponibilizados no formato .zip deverão ser lidos nesse mesmo formato.

- Gerar arquivos de qualquer formato durante a execução, com exceção daqueles gerados pelo Boletim de Soluções.

- Utilizar outros arquivos além dos disponibilizados no pacote do desafio do Eixo Temático Engenharia de Dados.

- Excluir ou alterar linhas do Boletim de Soluções (exceto quando explicitamente orientado pela comissão organizadora do Programa).

- Apresentar erros no código no momento da validação.

- O tempo total de execução do notebook não poderá exceder 2 minutos.

- Importar bibliotecas no código enviado para validação. Caso necessite instalar bibliotecas durante o desenvolvimento da solução, as linhas deverão ser comentadas antes do envio, sob o risco de apresentar erros ou exceder o tempo de execução do notebook durante a validação dos exercícios.
    
    *Atenção:* as bibliotecas mapeadas estarão previamente instaladas no ambiente de execução da solução validadora. Caso identifique a necessidade de utilizar alguma biblioteca diferente das mencionadas na seção "Requerimentos de versões", entre em contato com a comissão organizadora para verificar a viabilidade de utilização.

## Geras para o Nome Físico das colunas

- Observe atentamente a documentação constante no enunciado de cada exercício, para evitar apontamentos nas verificações.

- A ordem dos atributos deverá ser obedecida na construção dos DataFrames.

- A nomenclatura de todos os campos dos DataFrames deverá seguir o padrão de nomenclatura do Banco, conforme consulta disponível no Glossário.

- O nome físico não deve conter espaços, devendo as abreviações ser separadas por “_”.

- Todas as palavras do Nome Lógico deverão ser abreviadas, com exceção apenas das preposições (ex.: de, com, para, até, etc.).

- Ao consultar o Glossário, é importante atentar para a existência de palavras compostas, que devem ser abreviadas juntas.

## Demais recomendações/Orientações

- Leia atentamente o enunciado dos exercícios. Eventuais cálculos, formatações, filtros, transformações ou arredondamentos dos dados serão detalhados na descrição de cada atributo.

- Verifique o indicativo de nível de dificuldade e de ordem de solução dos exercícios, pois alguns têm como requisito a conclusão de algum exercício anterior na íntegra.

- Não se esqueça de salvar seu projeto! Sugerimos fazer vários versionamentos dos arquivos, para não correr riscos de perder alterações e para ter um backup, caso algo não saia como o planejado.

- Não se assuste com os apontamentos de erros durante o desenvolvimento dos exercícios. Observe as orientações e dicas para solucioná-los com maior assertividade.

- Ao fazer junção de tabelas, não se esqueça de conferir as quantidades de linhas e colunas das tabelas originais e tenha sempre em mente o seu objetivo antes de escolher o método de junção (interna, esquerda, direita ou total).

- Ao copiar variáveis, utilize preferencialmente o método copy() para evitar corromper as variáveis que serão utilizadas para conferência dos exercícios.

- Faça envios parciais, tantos quanto for necessário. Não há limite de quantidade de envios. O ideal é submeter seu notebook a cada exercício concluído, para evitar acúmulo de apontamentos na validação.

- Execute o Notebook na íntegra antes de efetuar seus envios para testar o tempo de execução e a ocorrência de erros, mesmo que ainda não tenha finalizado todos os exercícios.

- Utilize o Boletim de Soluções ao final do Notebook Modelo para checar a existência das variáveis de cada exercício. Não se esqueça de informar a sua chave F (chaveF) na seção de Identificação.

- Após execução na íntegra do seu notebook, visualize suas variáveis finais, aquelas que serão utilizadas para correção dos exercícios, para chegar eventuais alterações indesejadas nas variáveis. Exemplo:
    
        exercicio1.info()
        exercicio2.info()


**Atenção:** encorajamos a colaboração entre os participantes, porém sempre no sentido de ajudar os demais a chegarem à resposta, nunca respondendo diretamente às perguntas ou compartilhando os arquivos/código.

# Importar bibliotecas

Use esse espaço para importar as bibliotecas necessárias para execução do seu notebook.

Lembrando que eventuais instalações de bibliotecas durante o desenvolvimento deverão ser retiradas ou comentadas antes do envio.

In [2]:
# Atenção, somente descomente as células abaixo caso não esteja desenvolvendo no labblite
# após instalação, comente novamente as células

#!pip3 install --force-reinstall --user pandas==1.5.2
#!pip3 install --force-reinstall --user numpy==1.23.5
#!pip3 install --force-reinstall --user unidecode==1.3.8

In [3]:
# as celulas abaixo referem-se a instalação e importação de bibliotecas para desenvolvimento da solução
# favor não alterar esta célula sem antes consultar a comissão organizadora

try:
    import micropip
    await micropip.install('pandas')
    import pandas as pd
    await micropip.install('unidecode')
    from unidecode import unidecode
    await micropip.install('numpy')
    import numpy as np
    import warnings
    warnings.filterwarnings("ignore")
    from pathlib import Path
    import glob

    mensagem = "Importações de bibliotecas executadas com sucesso"
except:
    try:
        import pandas as pd
        from unidecode import unidecode
        import numpy as np
        import warnings
        warnings.filterwarnings("ignore")
        from pathlib import Path
        import glob

        mensagem = "Importações de bibliotecas executadas com sucesso"
    except Exception as e:
        mensagem = f"{e.args[0]} \nImportações de bibliotecas não executada"
finally:
    print(mensagem)

Importações de bibliotecas executadas com sucesso

In [4]:
# após upload, comente novamente as células
#from google.colab import files
#import zipfile
#import os

# Fazer o upload do arquivo zip
#uploaded = files.upload()

# Nome do arquivo zip
#zip_filename = list(uploaded.keys())[0]

# Extrair o arquivo zip para o diretório atual
#with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
#     zip_ref.extractall()

# Exercício 1 - Tabela de Vínculo entre as Unidades Organizacionais

<b>Nível de dificuldade:</b> 1

<b>Ordem:</b> qualquer

Criar um DataFrame Pandas chamado <b>exercicio1</b> com a tabela que contém o vínculo entre as UORs do Banco.

Na tabela abaixo especificamos as <b>informações descritivas</b> (nome, formato dos dados, etc.) dos atributos (colunas) que deverão constar no dataframe resultante:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|1|Código da Unidade Organizacional Vinculada|CD_UOR_VCLD|Int64|Código identificador de Unidade Organizacional (UOR) vinculada ou JURISDICIONADA.|N|VCL_UOR|CD_UOR_VCLD
|2|Código do Tipo de Vínculo|CD_TIP_VCL|Int64|Código identificador do Tipo de Vínculo ou JURISDIÇÃO utilizado para a vinculação entre Unidades Organizacionais.|N|VCL_UOR|CD_TIP_VCL
|3|Código da Unidade Organizacional Vinculadora|CD_UOR_VCLR|Int64|Código identificador da Unidade Organizacional vinculadora ou JURISDICIONANTE, conforme determinado Tipo de Vínculo ou jurisdição.|N|VCL_UOR|CD_UOR_VCLR
|4|Número do Intervalo de Nível Hierárquico|NR_ITVL_NVL_HRQO|Int64|Representa o intervalo de nível hierárquico entre a UOR Vinculada e a UOR Vinculadora. A partir deste atributo, é possível saber quantos níveis acima ou abaixo encontra-se uma UOR Vinculadora em relação à UOR Vinculada.|S|VCL_UOR|NR_ITVL_NVL_HRQO

Ao final do exerício, o resultado da consulta do cabeçado (<b>.head()</b>) do dataframe exercicio1 deverá seguir a estrutura abaixo exemplificada:

- código a ser executado:


    <i>exercicio1.head()</i>

- exemplo de resultado do código acima com valores fictícios:

||CD_UOR_VCLD|CD_TIP_VCL|CD_UOR_VCL|NR_ITVL_NVL_HRQO|
|---|---|---|---|---|
|0|9999|99|1111|&lt;NA&gt;|
|1|9999|101|2222|&lt;NA&gt;|
|2|9999|1100|3333|&lt;NA&gt;|
|3|9999|1200|4444|&lt;NA&gt;|
|34|9999|1220|5555|&lt;NA&gt;|

   
<b>Regra:</b> a ordem das colunas deverá obedecer à ordem da tabela de informações descritivas constante do enunciado.

<b>Dica 1:</b> verifique o <b>Vocabulário de Termos</b> anexo para saber mais sobre o termo <b>&lt;NA&gt;</b> e o tipo <b>Int64</b>.

<b>Dica 2:</b> os registros nulos somente deverão ser tratados quando expressamente orientado no enunciado do exercício.

In [5]:
# ler o arquivo VCL_UOR e atribuir a uma variável: pd.read_csv()
exercicio1 = pd.read_csv("bases/VCL_UOR.csv", sep=";")

In [6]:
exercicio1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40869 entries, 0 to 40868
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR_VCLD       40869 non-null  int64
 1   CD_TIP_VCL        40869 non-null  int64
 2   CD_UOR_VCLR       40869 non-null  int64
 3   NR_ITVL_NVL_HRQO  8452 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 1.2 MB

In [7]:
#converter as colunas abaixo para "Int64"
exercicio1['CD_UOR_VCLD'] = exercicio1['CD_UOR_VCLD'].astype("Int64")
exercicio1['CD_TIP_VCL'] = exercicio1['CD_TIP_VCL'].astype("Int64")
exercicio1['CD_UOR_VCLR'] = exercicio1['CD_UOR_VCLR'].astype("Int64")
exercicio1['NR_ITVL_NVL_HRQO'] = exercicio1['NR_ITVL_NVL_HRQO'].astype("Int64")
exercicio1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40869 entries, 0 to 40868
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR_VCLD       40869 non-null  Int64
 1   CD_TIP_VCL        40869 non-null  Int64
 2   CD_UOR_VCLR       40869 non-null  Int64
 3   NR_ITVL_NVL_HRQO  8452 non-null   Int64
dtypes: Int64(4)
memory usage: 1.4 MB

In [8]:
exercicio1.head()

   CD_UOR_VCLD  CD_TIP_VCL  CD_UOR_VCLR  NR_ITVL_NVL_HRQO
0         9598          99         4924              <NA>
1         9598         101         9598              <NA>
2         9598        1060        38047              <NA>
3         9598        1090         7638              <NA>
4         9598        1100         1993              <NA>

# Exercício 2 - Tabela de Unidades Organizacionais (UOR) do BB

<b>Nível de dificuldade (1 a 5):</b> 2

<b>Ordem:</b> qualquer

Criar um DataFrame Pandas chamado <b>exercicio2</b> com a tabela UORs do BB, conforme detalhado abaixo:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|1|Código da Unidade Organizacional|CD_UOR|Int64|Código identificador de Unidade Organizacional (UOR) do conglomerado Banco do Brasil (no Brasil e Exterior) ou UOR externas que o BB tenha algum tipo de relacionamento ou interesse em identificá-las.|N|UOR|CD_UOR
|2|Nome da Unidade Organizacional Reduzido|NM_UOR_RDZ|object|Nome reduzido da Unidade Organizacional.|N|UOR|NM_UOR_RDZ
|3|Sigla da Unidade Organizacional|SG_UOR|object|Reunião das letras iniciais dos vocábulos fundamentais de uma denominação ou título, sem articulação prosódica, constituindo meras abreviaturas. Ex.: "DITEC", "GBASE", "DIREO", "PRESI", etc.|S|UOR|SG_UOR
|4|Data Início de Validade|DT_INC_VLD|datetime64[ns]|Data em que o registro passa a ter validade (geralmente coincide com a data de inclusão).  Formato "AAAA-MM-DD".|N|UOR|DT_INC_VLD
|5|Código do Item da Arquitetura da Unidade Organizacional|CD_ITEM_AQTT_UOR|Int64|Código identificador dos Itens de Arquitetura que existem em uma Instituição Organizacional para orientação da estrutura das Unidades Organizacionais (oriundo do sistema IOR).|N|UOR|CD_ITEM_AQTT_UOR
|6|Código do Tipo da Unidade Organizacional|CD_TIP_UOR|Int64|Código identificador dos Tipos nos quais as Unidades Organizacionais podem ser classificadas. Ex.: "001 - Governo" "003 - Canal de Atendimento",  "004 - Dependências BB",  "005 - Exterior" etc. |N|UOR|CD_TIP_UOR
|7|Código da Dependência da Unidade Organizacional|CD_DEPE_UOR|Int64|Código identificador de Dependências de Instituições Organizacionais. No BB atualmente é utilizado os domínios entre 1 e 9999.Ex.: "0001 - Ag. Rio de Janeiro", "4886 - Ag. Estilo Alvorada-Brasília"|N|UOR|CD_DEPE_UOR
|8|Número da Ordem da Dependência Subordinada|NR_ORD_DEPE_SBDD|Int64|Número identificador de subordinação de uma dependência de IOR's que possuam em sua organização subdependências ou subordinadas. 0 indica a UOR principal da dependência|N|UOR|NR_ORD_DEPE_SBDD

<b>Regra 1:</b> considere apenas as UORs da Instituição Organizacional "Banco do Brasil".

<b>Regra 2:</b> considere apenas as UORs "em funcionamento".

<b>Dica: </b>atenção para o formato da data.

#dica para copiar dataframe
# exercicio2 = exercicio1.copy()

In [9]:
# ler o arquivo uor.zip e atribuir a uma variável: pd.read_csv()
uor01 = pd.read_csv('bases/UOR/uor01.zip', compression='zip', header=0)
uor02 = pd.read_csv('bases/UOR/uor02.zip', compression='zip', header=0)
uor03 = pd.read_csv('bases/UOR/uor03.zip', compression='zip', header=0)
uor04 = pd.read_csv('bases/UOR/uor04.zip', compression='zip', header=0)
uor05 = pd.read_csv('bases/UOR/uor05.zip', compression='zip', header=0)
uor06 = pd.read_csv('bases/UOR/uor06.zip', compression='zip', header=0)
uor07 = pd.read_csv('bases/UOR/uor07.zip', compression='zip', header=0)
uor08 = pd.read_csv('bases/UOR/uor08.zip', compression='zip', header=0)
uor09 = pd.read_csv('bases/UOR/uor09.zip', compression='zip', header=0)
uor10 = pd.read_csv('bases/UOR/uor10.zip', compression='zip', header=0)
uor11 = pd.read_csv('bases/UOR/uor11.zip', compression='zip', header=0)
uor12 = pd.read_csv('bases/UOR/uor12.zip', compression='zip', header=0)

In [10]:
#selecionar as colunas a exibir
colunas_exibir = ['CD_UOR','CD_IOR', 'NM_UOR_RDZ','CD_EST_UOR', 'SG_UOR', 'DT_INC_VLD', 'CD_ITEM_AQTT_UOR', 'CD_TIP_UOR', 'CD_DEPE_UOR', 'NR_ORD_DEPE_SBDD']
uor01 = uor01[colunas_exibir]
uor02 = uor02[colunas_exibir]
uor03 = uor03[colunas_exibir]
uor04 = uor04[colunas_exibir]
uor05 = uor05[colunas_exibir]
uor06 = uor06[colunas_exibir]
uor07 = uor07[colunas_exibir]
uor08 = uor08[colunas_exibir]
uor09 = uor09[colunas_exibir]
uor10 = uor10[colunas_exibir]
uor11 = uor11[colunas_exibir]
uor12 = uor12[colunas_exibir]
uor01.head()

,CD_UOR,CD_IOR,NM_UOR_RDZ,CD_EST_UOR,SG_UOR,DT_INC_VLD,CD_ITEM_AQTT_UOR,CD_TIP_UOR,CD_DEPE_UOR,NR_ORD_DEPE_SBDD
0,1,1,RIO,2,NaN,02/05/1936,54,4,1.0,0.0
1,2,1,CVRDN-DOCENAVE,4,NaN,01/10/1992,59,4,0.0,0.0
2,3,1,MANAUS,2,NaN,14/01/1908,54,4,2.0,0.0
3,4,1,PRESIDENTE VARGAS,2,NaN,01/07/1908,54,4,3.0,0.0
4,5,1,SANTOS,2,NaN,22/08/1908,54,4,4.0,0.0

In [11]:
#unir dataframes
uor = pd.concat([uor01,uor02,uor03,uor04,uor05,uor06,uor07,uor08,uor09,uor10,uor11,uor12])
uor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 414078 entries, 0 to 22577
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   CD_UOR            414078 non-null  int64
 1   CD_IOR            414078 non-null  int64
 2   NM_UOR_RDZ        414078 non-null  object
 3   CD_EST_UOR        414078 non-null  int64
 4   SG_UOR            70472 non-null   object
 5   DT_INC_VLD        414078 non-null  object
 6   CD_ITEM_AQTT_UOR  414078 non-null  int64
 7   CD_TIP_UOR        414078 non-null  int64
 8   CD_DEPE_UOR       88334 non-null   float64
 9   NR_ORD_DEPE_SBDD  88334 non-null   float64
dtypes: float64(2), int64(5), object(3)
memory usage: 34.8+ MB

In [12]:
#Regra 1: considere apenas as UORs da Instituição Organizacional "Banco do Brasil".
#Campo a utilizar: CD_IOR
# "001 - Banco do Brasil"
exercicio2 = uor[uor['CD_IOR'] == 1]
exercicio2.head()

,CD_UOR,CD_IOR,NM_UOR_RDZ,CD_EST_UOR,SG_UOR,DT_INC_VLD,CD_ITEM_AQTT_UOR,CD_TIP_UOR,CD_DEPE_UOR,NR_ORD_DEPE_SBDD
0,1,1,RIO,2,NaN,02/05/1936,54,4,1.0,0.0
1,2,1,CVRDN-DOCENAVE,4,NaN,01/10/1992,59,4,0.0,0.0
2,3,1,MANAUS,2,NaN,14/01/1908,54,4,2.0,0.0
3,4,1,PRESIDENTE VARGAS,2,NaN,01/07/1908,54,4,3.0,0.0
4,5,1,SANTOS,2,NaN,22/08/1908,54,4,4.0,0.0

In [13]:
#Regra 2: considere apenas as UORs "em funcionamento".
#Campo a utilizar: CD_EST_UOR
#Filtro: "002 - Em Funcionamento"
exercicio2 = exercicio2.copy()[exercicio2.copy()['CD_EST_UOR'] == 2]
exercicio2.head()

,CD_UOR,CD_IOR,NM_UOR_RDZ,CD_EST_UOR,SG_UOR,DT_INC_VLD,CD_ITEM_AQTT_UOR,CD_TIP_UOR,CD_DEPE_UOR,NR_ORD_DEPE_SBDD
0,1,1,RIO,2,NaN,02/05/1936,54,4,1.0,0.0
2,3,1,MANAUS,2,NaN,14/01/1908,54,4,2.0,0.0
3,4,1,PRESIDENTE VARGAS,2,NaN,01/07/1908,54,4,3.0,0.0
4,5,1,SANTOS,2,NaN,22/08/1908,54,4,4.0,0.0
6,7,1,CAMPOS GOYTACAZES,2,NaN,26/06/1910,54,4,5.0,0.0

# Vamos supor que queremos filtrar
# os registros onde o campo1 contenha
# apenas o valor 'valor1'
filtro1 = (df['campo1'] == 'valor1')

# E o campo2 contendo apenas o valor 'valor2'
filtro2 = (df['campo2'] == 'valor2')

# Usamos o & (E lógico) para combinar os filtros
# que queremos aqui
df_filtrado = df[filtro1 & filtro2]

In [14]:
exercicio2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43005 entries, 0 to 20832
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR            43005 non-null  int64
 1   CD_IOR            43005 non-null  int64
 2   NM_UOR_RDZ        43005 non-null  object
 3   CD_EST_UOR        43005 non-null  int64
 4   SG_UOR            39719 non-null  object
 5   DT_INC_VLD        43005 non-null  object
 6   CD_ITEM_AQTT_UOR  43005 non-null  int64
 7   CD_TIP_UOR        43005 non-null  int64
 8   CD_DEPE_UOR       43005 non-null  float64
 9   NR_ORD_DEPE_SBDD  43005 non-null  float64
dtypes: float64(2), int64(5), object(3)
memory usage: 4.6+ MB

In [15]:
#converter as colunas abaixo conforme formato solicitado na atividade 2:
exercicio2['CD_UOR'] = exercicio2['CD_UOR'].astype("Int64")
exercicio2.DT_INC_VLD = pd.to_datetime(exercicio2.DT_INC_VLD, format='%d/%m/%Y')
exercicio2['CD_ITEM_AQTT_UOR'] = exercicio2['CD_ITEM_AQTT_UOR'].astype("Int64")
exercicio2['CD_TIP_UOR'] = exercicio2['CD_TIP_UOR'].astype("Int64")
exercicio2['CD_DEPE_UOR'] = exercicio2['CD_DEPE_UOR'].astype("Int64")
exercicio2['NR_ORD_DEPE_SBDD'] = exercicio2['NR_ORD_DEPE_SBDD'].astype("Int64")
exercicio2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43005 entries, 0 to 20832
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR            43005 non-null  Int64
 1   CD_IOR            43005 non-null  int64
 2   NM_UOR_RDZ        43005 non-null  object
 3   CD_EST_UOR        43005 non-null  int64
 4   SG_UOR            39719 non-null  object
 5   DT_INC_VLD        43005 non-null  datetime64[ns]
 6   CD_ITEM_AQTT_UOR  43005 non-null  Int64
 7   CD_TIP_UOR        43005 non-null  Int64
 8   CD_DEPE_UOR       43005 non-null  Int64
 9   NR_ORD_DEPE_SBDD  43005 non-null  Int64
dtypes: Int64(5), datetime64[ns](1), int64(2), object(2)
memory usage: 4.8+ MB

In [16]:
#remover as colunas CD_IOR e CD_EST_UOR
exercicio2.drop(columns=['CD_IOR', 'CD_EST_UOR'], inplace=True)
exercicio2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43005 entries, 0 to 20832
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR            43005 non-null  Int64
 1   NM_UOR_RDZ        43005 non-null  object
 2   SG_UOR            39719 non-null  object
 3   DT_INC_VLD        43005 non-null  datetime64[ns]
 4   CD_ITEM_AQTT_UOR  43005 non-null  Int64
 5   CD_TIP_UOR        43005 non-null  Int64
 6   CD_DEPE_UOR       43005 non-null  Int64
 7   NR_ORD_DEPE_SBDD  43005 non-null  Int64
dtypes: Int64(5), datetime64[ns](1), object(2)
memory usage: 4.2+ MB

In [17]:
exercicio2.head(5000)

,CD_UOR,NM_UOR_RDZ,SG_UOR,DT_INC_VLD,CD_ITEM_AQTT_UOR,CD_TIP_UOR,CD_DEPE_UOR,NR_ORD_DEPE_SBDD
0,1,RIO,NaN,1936-05-02,54,4,1,0
2,3,MANAUS,NaN,1908-01-14,54,4,2,0
3,4,PRESIDENTE VARGAS,NaN,1908-07-01,54,4,3,0
4,5,SANTOS,NaN,1908-08-22,54,4,4,0
6,7,CAMPOS GOYTACAZES,NaN,1910-06-26,54,4,5,0
...,...,...,...,...,...,...,...,...
9184,9185,PSO MARILIA,,2009-11-07,113,4,7839,0
9185,9186,PSO MAUA,,2009-11-07,113,4,7840,0
9188,9189,PSO TAUBATE,,2009-11-07,113,4,7843,0
9189,9190,PSO PAE S.PAULO II,,2009-11-07,113,4,7844,0
9190,9191,PSO PAE S.PAULO III,,2009-11-07,113,4,7845,0

# Exercício 3 - Tabela de cursos realizados por funcionário

<b>Nível de dificuldade (1 a 5):</b> 1

<b>Ordem:</b> qualquer

Criar um DataFrame Pandas chamado <b>exercicio3</b> com a tabela dos cursos realizados pelos funcionários, conforme detalhado abaixo:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|1|Codigo de matricula do funcionario|?|Int64|Código da matrícula do funcionário. |N|?|?|
|2|Código do Curso|?|Int64|Identificador do curso. Campo numérico de 7 posições. |N|?|?|
|3|Data final do curso|?|datetime64[ns]|Data que identifica a finalizaçao do curso. Formato "AAAA-MM-DD".|N|?|?|
|4|Codigo de origem do curso|?|Int64|O conteudo deste campo indentificara a origem do curso. Exemplo: 01-ARH, 02-GTD, 03-PFP, 04-ALURA, 05-UNIBB, 17-SYNAPSE|N|?|?|

<b>Dica 1:</b> para construir o nome físico das tabelas, consulte as abreviações no Glossário de Termos.

<b>Dica 2:</b> atenção para o formato da matrícula.

In [18]:
# ler o arquivo cso_pss_itse_sis.zip e atribuir a uma variável: pd.read_csv()
cso_pss_itse_sis01 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis01.zip', compression='zip', header=0)
cso_pss_itse_sis02 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis02.zip', compression='zip', header=0)
cso_pss_itse_sis03 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis03.zip', compression='zip', header=0)
cso_pss_itse_sis04 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis04.zip', compression='zip', header=0)
cso_pss_itse_sis05 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis05.zip', compression='zip', header=0)
cso_pss_itse_sis06 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis06.zip', compression='zip', header=0)
cso_pss_itse_sis07 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis07.zip', compression='zip', header=0)
cso_pss_itse_sis08 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis08.zip', compression='zip', header=0)
cso_pss_itse_sis09 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis09.zip', compression='zip', header=0)
cso_pss_itse_sis10 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis10.zip', compression='zip', header=0)
cso_pss_itse_sis11 = pd.read_csv('bases/CSO_PSS_ITSE_SIS/cso_pss_itse_sis11.zip', compression='zip', header=0)

In [19]:
#unir dataframes
exercicio3 = pd.concat([cso_pss_itse_sis01,cso_pss_itse_sis02,cso_pss_itse_sis03,cso_pss_itse_sis04,cso_pss_itse_sis05,cso_pss_itse_sis06,cso_pss_itse_sis07,cso_pss_itse_sis08,cso_pss_itse_sis09,cso_pss_itse_sis10,cso_pss_itse_sis11])
exercicio3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1953341 entries, 0 to 8340
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   MATRICULA   object
 1   CD_CSO      int64
 2   DT_FIM_CSO  object
 3   CD_OGM_CSO  int64
dtypes: int64(2), object(2)
memory usage: 74.5+ MB

In [20]:
# Utilizar str[1:] para remover o primeiro caractere de cada célula:
exercicio3['MATRICULA'] = exercicio3['MATRICULA'].str[1:]
exercicio3.head()

  MATRICULA  CD_CSO  DT_FIM_CSO  CD_OGM_CSO
0   3066439     127  2008-04-04           4
1   3066439     350  2012-05-18           4
2   3066439     569  2013-10-22           4
3   3066439     828  2016-10-07           4
4   3066439    1251  2013-11-13           4

In [21]:
#converter as colunas abaixo
exercicio3['MATRICULA'] = exercicio3['MATRICULA'].astype("Int64")
exercicio3['CD_CSO'] = exercicio3['CD_CSO'].astype('Int64')
exercicio3.DT_FIM_CSO = pd.to_datetime(exercicio3.DT_FIM_CSO)
exercicio3['CD_OGM_CSO'] = exercicio3['CD_OGM_CSO'].astype("Int64")

In [22]:
#renomear colunas de acordo com o Glossário
exercicio3.rename(columns={'MATRICULA':'CD_MTC_FUN'}, inplace=True)
exercicio3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1953341 entries, 0 to 8340
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   CD_MTC_FUN  Int64
 1   CD_CSO      Int64
 2   DT_FIM_CSO  datetime64[ns]
 3   CD_OGM_CSO  Int64
dtypes: Int64(3), datetime64[ns](1)
memory usage: 80.1 MB

In [23]:
exercicio3.head()

   CD_MTC_FUN  CD_CSO DT_FIM_CSO  CD_OGM_CSO
0     3066439     127 2008-04-04           4
1     3066439     350 2012-05-18           4
2     3066439     569 2013-10-22           4
3     3066439     828 2016-10-07           4
4     3066439    1251 2013-11-13           4

In [24]:
exercicio3.notnull().sum()

CD_MTC_FUN    1953341
CD_CSO        1953341
DT_FIM_CSO    1953341
CD_OGM_CSO    1953341
dtype: int64

# Exercício 4 - Tabela de cadastro dos funcionários

<b>Nível de dificuldade (1 a 5):</b> 2

<b>Ordem:</b> qualquer

Criar um DataFrame Pandas chamado <b>exercicio4</b> com a tabela de cadastro dos funcionários, conforme detalhado abaixo:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|1|Codigo de matricula do funcionario|?|Int64|Código da matrícula (F) do funcionário. |N|CAD_FUN|?
|2|Nome do funcionário|?|object|Nome do funcionário cadastrado no ARH. Formato: caixa alta, sem acentuação.|N|CAD_FUN|?
|3|Sigla do Tipo do Estado Civil|?|object|Sigla ARH que define o estado civil do funcionário. |N|CAD_FUN|?
|4|Código do Tipo de Nível de Instrução|?|Int64|Código ARH do nível de instrução. |N|CAD_FUN|?
|5|Data de nascimento|?|datetime64[ns]|Data de nascimento. Formato "AAAA-MM-DD".|N|CAD_FUN|?
|6|Código do Tipo de Gênero|?|Int64|Código ARH do sexo/gênero. 1 -Masculino, 2 - Feminino.|N|CAD_FUN|?
|7|Código do Prefixo da Dependência de Localização|?|Int64|Código do prefixo da dependência de localização (UOR). |N|CAD_FUN|?
|8|Código de Função ou Cargo Efetiva|?|Int64|Código ARH da função ou cargo efetivo. Exemplo: 610 - ESCRITURARIO, 12381 - ASSESSOR II UE etc. |N|CAD_FUN|?
|9|Data de Posse na Localização|?|datetime64[ns]|Data de posse na dependência de localização (UOR).  Formato "AAAA-MM-DD".|N|CAD_FUN|?
|10|Data de posse no BB|?|datetime64[ns]|Data de posse no Banco do Brasil. Formato "AAAA-MM-DD".|N|CAD_FUN|?

<b>Dica:</b> atenção para a formatação do nome.

In [25]:
# ler o arquivo CAD_FUN e atribuir a uma variável: pd.read_csv()
exercicio4 = pd.read_csv("bases/CAD_FUN.csv", sep=",")
exercicio4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5287 entries, 0 to 5286
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MATRICULA           5287 non-null   int64
 1   NOME                5287 non-null   object
 2   EST_CIVIL           5287 non-null   object
 3   GRAU_INSTRUCAO      5287 non-null   int64
 4   NASC_DT             5287 non-null   int64
 5   SEXO                5287 non-null   int64
 6   LOCALIZACAO         5287 non-null   int64
 7   FUNCAO_LOCALIZACAO  5287 non-null   int64
 8   LOCALIZACAO_DT      5287 non-null   object
 9   POSSE_BANCO_DT      5287 non-null   object
dtypes: int64(6), object(4)
memory usage: 413.2+ KB

In [26]:
exercicio4.head()

,MATRICULA,NOME,EST_CIVIL,GRAU_INSTRUCAO,NASC_DT,SEXO,LOCALIZACAO,FUNCAO_LOCALIZACAO,LOCALIZACAO_DT,POSSE_BANCO_DT
0,665496,Agatha da Costa,2,8,4111966,2,8008,12392,2024-05-21,2008-10-01
1,724351,Alexia Dias,8,8,20021981,2,8008,12331,2017-02-21,2002-12-16
2,850407,Allana Mendonça,1,8,4101983,2,8008,12331,2023-10-30,2012-06-11
3,872028,Amanda Sousa,2,8,30051979,2,8008,12331,2022-05-23,2015-08-03
4,971323,Ana Clara Montenegro,2,8,9121982,2,8008,12331,2023-07-06,2016-01-25

In [27]:
#renomear colunas de acordo com o Glossário
exercicio4.rename(columns={'MATRICULA':'CD_MTC_FUN',
                           'NOME':'NM_FUN',
                           'EST_CIVIL':'SG_TIP_EST_CVL',
                           'GRAU_INSTRUCAO':'CD_TIP_NVL_ITC',
                           'NASC_DT':'DT_NSC',
                           'SEXO':'CD_TIP_GNR',
                           'LOCALIZACAO':'CD_PRF_DEPE_LCZC',
                           'FUNCAO_LOCALIZACAO':'CD_FUC_CRG_EFT',
                           'LOCALIZACAO_DT':'DT_PSSE_LCZC',
                           'POSSE_BANCO_DT':'DT_PSSE_BB'}, inplace=True)
exercicio4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5287 entries, 0 to 5286
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        5287 non-null   int64
 1   NM_FUN            5287 non-null   object
 2   SG_TIP_EST_CVL    5287 non-null   object
 3   CD_TIP_NVL_ITC    5287 non-null   int64
 4   DT_NSC            5287 non-null   int64
 5   CD_TIP_GNR        5287 non-null   int64
 6   CD_PRF_DEPE_LCZC  5287 non-null   int64
 7   CD_FUC_CRG_EFT    5287 non-null   int64
 8   DT_PSSE_LCZC      5287 non-null   object
 9   DT_PSSE_BB        5287 non-null   object
dtypes: int64(6), object(4)
memory usage: 413.2+ KB

In [28]:
# Converter Nome do funcionário cadastrado no ARH para Formato: caixa alta, sem acentuação.
exercicio4['NM_FUN'] = exercicio4['NM_FUN'].apply(lambda x: unidecode(x).upper())
exercicio4.head()

,CD_MTC_FUN,NM_FUN,SG_TIP_EST_CVL,CD_TIP_NVL_ITC,DT_NSC,CD_TIP_GNR,CD_PRF_DEPE_LCZC,CD_FUC_CRG_EFT,DT_PSSE_LCZC,DT_PSSE_BB
0,665496,AGATHA DA COSTA,2,8,4111966,2,8008,12392,2024-05-21,2008-10-01
1,724351,ALEXIA DIAS,8,8,20021981,2,8008,12331,2017-02-21,2002-12-16
2,850407,ALLANA MENDONCA,1,8,4101983,2,8008,12331,2023-10-30,2012-06-11
3,872028,AMANDA SOUSA,2,8,30051979,2,8008,12331,2022-05-23,2015-08-03
4,971323,ANA CLARA MONTENEGRO,2,8,9121982,2,8008,12331,2023-07-06,2016-01-25

In [29]:
# Converter os números para string e padronizar para o formato adequado DDMMYYYY
# Zfill adiciona zeros à esquerda para garantir 8 dígitos
exercicio4['DT_NSC'] = exercicio4['DT_NSC'].astype(str).str.zfill(8)
exercicio4.head()

,CD_MTC_FUN,NM_FUN,SG_TIP_EST_CVL,CD_TIP_NVL_ITC,DT_NSC,CD_TIP_GNR,CD_PRF_DEPE_LCZC,CD_FUC_CRG_EFT,DT_PSSE_LCZC,DT_PSSE_BB
0,665496,AGATHA DA COSTA,2,8,04111966,2,8008,12392,2024-05-21,2008-10-01
1,724351,ALEXIA DIAS,8,8,20021981,2,8008,12331,2017-02-21,2002-12-16
2,850407,ALLANA MENDONCA,1,8,04101983,2,8008,12331,2023-10-30,2012-06-11
3,872028,AMANDA SOUSA,2,8,30051979,2,8008,12331,2022-05-23,2015-08-03
4,971323,ANA CLARA MONTENEGRO,2,8,09121982,2,8008,12331,2023-07-06,2016-01-25

In [30]:
# Converter os formatos e usar pd.to_datetime para converter para datetime
exercicio4['CD_MTC_FUN'] = exercicio4['CD_MTC_FUN'].astype("Int64")
exercicio4['CD_TIP_NVL_ITC'] = exercicio4['CD_TIP_NVL_ITC'].astype('Int64')
exercicio4['DT_NSC'] = pd.to_datetime(exercicio4['DT_NSC'], format='%d%m%Y')
exercicio4['CD_TIP_GNR'] = exercicio4['CD_TIP_GNR'].astype("Int64")
exercicio4['CD_PRF_DEPE_LCZC'] = exercicio4['CD_PRF_DEPE_LCZC'].astype("Int64")
exercicio4['CD_FUC_CRG_EFT'] = exercicio4['CD_FUC_CRG_EFT'].astype("Int64")
exercicio4['DT_PSSE_LCZC'] = pd.to_datetime(exercicio4['DT_PSSE_LCZC'])
exercicio4['DT_PSSE_BB'] = pd.to_datetime(exercicio4['DT_PSSE_BB'])
exercicio4.head()

,CD_MTC_FUN,NM_FUN,SG_TIP_EST_CVL,CD_TIP_NVL_ITC,DT_NSC,CD_TIP_GNR,CD_PRF_DEPE_LCZC,CD_FUC_CRG_EFT,DT_PSSE_LCZC,DT_PSSE_BB
0,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01
1,724351,ALEXIA DIAS,8,8,1981-02-20,2,8008,12331,2017-02-21,2002-12-16
2,850407,ALLANA MENDONCA,1,8,1983-10-04,2,8008,12331,2023-10-30,2012-06-11
3,872028,AMANDA SOUSA,2,8,1979-05-30,2,8008,12331,2022-05-23,2015-08-03
4,971323,ANA CLARA MONTENEGRO,2,8,1982-12-09,2,8008,12331,2023-07-06,2016-01-25

In [31]:
exercicio4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5287 entries, 0 to 5286
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        5287 non-null   Int64
 1   NM_FUN            5287 non-null   object
 2   SG_TIP_EST_CVL    5287 non-null   object
 3   CD_TIP_NVL_ITC    5287 non-null   Int64
 4   DT_NSC            5287 non-null   datetime64[ns]
 5   CD_TIP_GNR        5287 non-null   Int64
 6   CD_PRF_DEPE_LCZC  5287 non-null   Int64
 7   CD_FUC_CRG_EFT    5287 non-null   Int64
 8   DT_PSSE_LCZC      5287 non-null   datetime64[ns]
 9   DT_PSSE_BB        5287 non-null   datetime64[ns]
dtypes: Int64(5), datetime64[ns](3), object(2)
memory usage: 439.0+ KB

# Exercício 5 - Incremento da tabela de cadastro de funcionários

<b>Nível de dificuldade (1 a 5):</b> 3

<b>Requisitos:</b> exercício 4

Criar um DataFrame Pandas chamado <b>exercicio5</b> contendo os campos adicionais do cadastro do funcionários, conforme abaixo detalhado:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|1|Codigo de matricula do funcionario|?|Int64|Código da matrícula (F) do funcionário. |N|?|?|
|2|Nome do funcionário|?|object|Nome do funcionário cadastrado no ARH. Formato: caixa alta, sem acentuação.|N|?|?|
|3|Código de Função ou Cargo Efetiva|?|Int64|Código ARH da função ou cargo efetivo. Exemplo: 610, 12381, etc. |N|?|?|
|4|Nome da Função ou Cargo Efetivo|?|object|Nome da função ou cargo efetivo. Exemplo: 610 - ESCRITURARIO, 12381 - ASSESSOR II UE etc. |S|?|?|
|5|Código do Prefixo da Dependência de Localização|?|Int64|Código do prefixo da dependência de localização (UOR). |N|?|?|
|6|Data de Posse na Localização|?|datetime64[ns]|Data de posse na dependência de localização (UOR).  Formato "AAAA-MM-DD".|N|?|?|
|7|Data de posse no BB|?|datetime64[ns]|Data de posse no Banco do Brasil. Formato "AAAA-MM-DD".|N|?|?|
|8|Data de nascimento|?|datetime64[ns]|Data de nascimento. Formato "AAAA-MM-DD".|N|?|?|
|9|Código do Tipo de Gênero|?|Int64|Código ARH do sexo/gênero. 1 -Masculino, 2 - Feminino.|N|?|?|
|10|Sigla do Tipo do Estado Civil|?|object|Sigla ARH que define o estado civil do funcionário. |N|?|?|
|11|Nome do Tipo de Estado Civil|?|object|Descrição do estado civil do funcionário. |N|?|?|
|12|Código do Tipo de Nível de Instrução|?|Int64|Código ARH do nível de instrução. |N|?|?|
|13|Nome do Tipo de Nível de Instrução|?|object|Descrição do nível de instrução. |N|?|?|

<b>Regra 1:</b> para a descrição do estado civil, considere os valores abaixo:

|Cod.|Descrição|
|---|---|
|1|SOLTEIRO(A)|
|2|CASADO(A)|
|3|CASADO(A) COM FUNCIONARIA(O)|
|4|VIUVO(A)|
|5|SEPARADO(A) JUDICIAL OU EXTRAJ|
|8|DIVORCIADO(A)|
|M|SEPARADO(A) CONSENSUALMENTE|

<b>Regra 2:</b> para a descrição do nível de instrução, considere os valores abaixo:

|Cod.|Descrição|
|---|---|
|1|ENSINO FUNDAMENTAL|
|2|ENSINO MEDIO|
|3|SUPERIOR EM ANDAMENTO|
|4|SUPERIOR SEQUENCIAL|
|5|SUPERIOR GRADUACAO|
|6|POS-GRADUACAO-APERFEIC|
|7|POS-GRADUCAO-ESPEC|
|8|MESTRADO|
|9|DOUTORADO|

In [32]:
# ler o arquivo FUC_FUN e atribuir a uma variável: pd.read_csv()
FUC_FUN = pd.read_csv("bases/FUC_FUN.csv", sep=",")
FUC_FUN.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544 entries, 0 to 543
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CD_FUC_FUN  544 non-null    int64
 1   NM_FUC_FUN  544 non-null    object
dtypes: int64(1), object(1)
memory usage: 8.6+ KB

In [33]:
#renomear colunas de acordo com o Glossário
FUC_FUN.rename(columns={'CD_FUC_FUN':'CD_FUC_CRG_EFT',
                           'NM_FUC_FUN':'NM_FUC_CRG_EFT',
                           }, inplace=True)
FUC_FUN.head()

   CD_FUC_CRG_EFT   NM_FUC_CRG_EFT
0             288  CAIXA EXECUTIVO
1             394  CAIXA EXECUTIVO
2             610     ESCRITURARIO
3             649     SAC-CONTINUO
4             674    SAC-VIGILANTE

In [34]:
# Converter para Int64
FUC_FUN['CD_FUC_CRG_EFT'] = FUC_FUN['CD_FUC_CRG_EFT'].astype("Int64")
FUC_FUN.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544 entries, 0 to 543
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CD_FUC_CRG_EFT  544 non-null    Int64
 1   NM_FUC_CRG_EFT  544 non-null    object
dtypes: Int64(1), object(1)
memory usage: 9.2+ KB

In [35]:
# unir os dois dataframes 'exercicio4' e 'FUC_FUN' : .merge
exercicio5 = exercicio4.merge(FUC_FUN, how='left', on='CD_FUC_CRG_EFT')
exercicio5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5287 entries, 0 to 5286
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        5287 non-null   Int64
 1   NM_FUN            5287 non-null   object
 2   SG_TIP_EST_CVL    5287 non-null   object
 3   CD_TIP_NVL_ITC    5287 non-null   Int64
 4   DT_NSC            5287 non-null   datetime64[ns]
 5   CD_TIP_GNR        5287 non-null   Int64
 6   CD_PRF_DEPE_LCZC  5287 non-null   Int64
 7   CD_FUC_CRG_EFT    5287 non-null   Int64
 8   DT_PSSE_LCZC      5287 non-null   datetime64[ns]
 9   DT_PSSE_BB        5287 non-null   datetime64[ns]
 10  NM_FUC_CRG_EFT    5262 non-null   object
dtypes: Int64(5), datetime64[ns](3), object(3)
memory usage: 521.5+ KB

In [36]:
# Dados como um dicionário de listas
dados_EST_CVL = {
    'SG_TIP_EST_CVL': ['1','2','3','4','5','8','M'],
    'NM_TIP_EST_CVL': ['SOLTEIRO(A)',
                       'CASADO(A)',
                       'CASADO(A) COM FUNCIONARIA(O)',
                       'VIUVO(A)',
                       'SEPARADO(A) JUDICIAL OU EXTRAJ',
                       'DIVORCIADO(A)',
                       'SEPARADO(A) CONSENSUALMENTE']
   }

# Criar DataFrame
EST_CVL = pd.DataFrame(dados_EST_CVL)
EST_CVL.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SG_TIP_EST_CVL  7 non-null      object
 1   NM_TIP_EST_CVL  7 non-null      object
dtypes: object(2)
memory usage: 240.0+ bytes

In [37]:
EST_CVL.head(7)

  SG_TIP_EST_CVL                  NM_TIP_EST_CVL
0              1                     SOLTEIRO(A)
1              2                       CASADO(A)
2              3    CASADO(A) COM FUNCIONARIA(O)
3              4                        VIUVO(A)
4              5  SEPARADO(A) JUDICIAL OU EXTRAJ
5              8                   DIVORCIADO(A)
6              M     SEPARADO(A) CONSENSUALMENTE

In [38]:
# unir os dois dataframes 'exercicio5' e 'EST_CVL' : .merge
exercicio5 = exercicio5.merge(EST_CVL, how='left', on='SG_TIP_EST_CVL')
exercicio5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5287 entries, 0 to 5286
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        5287 non-null   Int64
 1   NM_FUN            5287 non-null   object
 2   SG_TIP_EST_CVL    5287 non-null   object
 3   CD_TIP_NVL_ITC    5287 non-null   Int64
 4   DT_NSC            5287 non-null   datetime64[ns]
 5   CD_TIP_GNR        5287 non-null   Int64
 6   CD_PRF_DEPE_LCZC  5287 non-null   Int64
 7   CD_FUC_CRG_EFT    5287 non-null   Int64
 8   DT_PSSE_LCZC      5287 non-null   datetime64[ns]
 9   DT_PSSE_BB        5287 non-null   datetime64[ns]
 10  NM_FUC_CRG_EFT    5262 non-null   object
 11  NM_TIP_EST_CVL    5287 non-null   object
dtypes: Int64(5), datetime64[ns](3), object(4)
memory usage: 562.8+ KB

In [39]:
# Dados como um dicionário de listas
dados_NVL_ITC = {
    'CD_TIP_NVL_ITC': [1,2,3,4,5,6,7,8,9],
    'NM_TIP_NVL_ITC': ['ENSINO FUNDAMENTAL',
                       'ENSINO MEDIO',
                       'SUPERIOR EM ANDAMENTO',
                       'SUPERIOR SEQUENCIAL',
                       'SUPERIOR GRADUACAO',
                       'POS-GRADUACAO-APERFEIC',
                       'POS-GRADUCAO-ESPEC',
                       'MESTRADO',
                       'DOUTORADO']
   }

# Criar DataFrame
NVL_ITC = pd.DataFrame(dados_NVL_ITC)

In [40]:
# Converter para Int64
NVL_ITC['CD_TIP_NVL_ITC'] = NVL_ITC['CD_TIP_NVL_ITC'].astype("Int64")
NVL_ITC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CD_TIP_NVL_ITC  9 non-null      Int64
 1   NM_TIP_NVL_ITC  9 non-null      object
dtypes: Int64(1), object(1)
memory usage: 281.0+ bytes

In [41]:
NVL_ITC.head(9)

   CD_TIP_NVL_ITC          NM_TIP_NVL_ITC
0               1      ENSINO FUNDAMENTAL
1               2            ENSINO MEDIO
2               3   SUPERIOR EM ANDAMENTO
3               4     SUPERIOR SEQUENCIAL
4               5      SUPERIOR GRADUACAO
5               6  POS-GRADUACAO-APERFEIC
6               7      POS-GRADUCAO-ESPEC
7               8                MESTRADO
8               9               DOUTORADO

In [42]:
# unir os dois dataframes 'exercicio5' e 'NVL_ITC' : .merge
exercicio5 = exercicio5.merge(NVL_ITC, how='left', on='CD_TIP_NVL_ITC')
exercicio5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5287 entries, 0 to 5286
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        5287 non-null   Int64
 1   NM_FUN            5287 non-null   object
 2   SG_TIP_EST_CVL    5287 non-null   object
 3   CD_TIP_NVL_ITC    5287 non-null   Int64
 4   DT_NSC            5287 non-null   datetime64[ns]
 5   CD_TIP_GNR        5287 non-null   Int64
 6   CD_PRF_DEPE_LCZC  5287 non-null   Int64
 7   CD_FUC_CRG_EFT    5287 non-null   Int64
 8   DT_PSSE_LCZC      5287 non-null   datetime64[ns]
 9   DT_PSSE_BB        5287 non-null   datetime64[ns]
 10  NM_FUC_CRG_EFT    5262 non-null   object
 11  NM_TIP_EST_CVL    5287 non-null   object
 12  NM_TIP_NVL_ITC    5287 non-null   object
dtypes: Int64(5), datetime64[ns](3), object(5)
memory usage: 604.1+ KB

In [43]:
exercicio5.head()

,CD_MTC_FUN,NM_FUN,SG_TIP_EST_CVL,CD_TIP_NVL_ITC,DT_NSC,CD_TIP_GNR,CD_PRF_DEPE_LCZC,CD_FUC_CRG_EFT,DT_PSSE_LCZC,DT_PSSE_BB,NM_FUC_CRG_EFT,NM_TIP_EST_CVL,NM_TIP_NVL_ITC
0,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,ASSESSOR III UE,CASADO(A),MESTRADO
1,724351,ALEXIA DIAS,8,8,1981-02-20,2,8008,12331,2017-02-21,2002-12-16,ASSESSOR I UE,DIVORCIADO(A),MESTRADO
2,850407,ALLANA MENDONCA,1,8,1983-10-04,2,8008,12331,2023-10-30,2012-06-11,ASSESSOR I UE,SOLTEIRO(A),MESTRADO
3,872028,AMANDA SOUSA,2,8,1979-05-30,2,8008,12331,2022-05-23,2015-08-03,ASSESSOR I UE,CASADO(A),MESTRADO
4,971323,ANA CLARA MONTENEGRO,2,8,1982-12-09,2,8008,12331,2023-07-06,2016-01-25,ASSESSOR I UE,CASADO(A),MESTRADO

In [44]:
#lista de colunas
exercicio5.columns

Index(['CD_MTC_FUN', 'NM_FUN', 'SG_TIP_EST_CVL', 'CD_TIP_NVL_ITC', 'DT_NSC',
       'CD_TIP_GNR', 'CD_PRF_DEPE_LCZC', 'CD_FUC_CRG_EFT', 'DT_PSSE_LCZC',
       'DT_PSSE_BB', 'NM_FUC_CRG_EFT', 'NM_TIP_EST_CVL', 'NM_TIP_NVL_ITC'],
      dtype='object')

In [45]:
# Reordedar as colunas
colunas_exercicio5 = ['CD_MTC_FUN', 'NM_FUN', 'CD_FUC_CRG_EFT','NM_FUC_CRG_EFT',
                      'CD_PRF_DEPE_LCZC','DT_PSSE_LCZC','DT_PSSE_BB','DT_NSC',
                      'CD_TIP_GNR', 'SG_TIP_EST_CVL','NM_TIP_EST_CVL',
                      'CD_TIP_NVL_ITC','NM_TIP_NVL_ITC']

exercicio5 = exercicio5[colunas_exercicio5]
exercicio5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5287 entries, 0 to 5286
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        5287 non-null   Int64
 1   NM_FUN            5287 non-null   object
 2   CD_FUC_CRG_EFT    5287 non-null   Int64
 3   NM_FUC_CRG_EFT    5262 non-null   object
 4   CD_PRF_DEPE_LCZC  5287 non-null   Int64
 5   DT_PSSE_LCZC      5287 non-null   datetime64[ns]
 6   DT_PSSE_BB        5287 non-null   datetime64[ns]
 7   DT_NSC            5287 non-null   datetime64[ns]
 8   CD_TIP_GNR        5287 non-null   Int64
 9   SG_TIP_EST_CVL    5287 non-null   object
 10  NM_TIP_EST_CVL    5287 non-null   object
 11  CD_TIP_NVL_ITC    5287 non-null   Int64
 12  NM_TIP_NVL_ITC    5287 non-null   object
dtypes: Int64(5), datetime64[ns](3), object(5)
memory usage: 604.1+ KB

# Exercício 6 - Tabela Catálogo de Cursos

<b>Nível de dificuldade (1 a 5):</b> 3

<b>Ordem:</b> qualquer

Criar um DataFrame Pandas chamado <b>exercicio6</b> contendo o catálodo de cursos e formações do Banco, conforme abaixo:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|1|Código do Curso|?|Int64|Identificador do curso. Campo numérico de 7 posições. |N|?|?|
|2|Nome do Curso|?|object|Nome genérico do curso. |N|?|?|
|3|Texto do Curso|?|object|Breve descrição do assunto abordado pelo curso. |N|?|?|
|4|Texto do Objetivo do Curso|?|object|Texto que descreve o objetivo do curso. |N|?|?|
|5|Texto do Desempenho Esperado|?|object|Texto que descreve o desempenho esperado no curso para o treinando. |S|?|?|
|6|Texto do Objetivo Estratégico|?|object|Texto que descreve quais são os objetivos estratégicos do curso. |S|?|?|
|7|Código da Área de Conhecimento|?|Int64|Código da área de conhecimento do curso. Campo numérico de 3. Exemplo: Área: 170 (Será este atributo) Subárea: 170.050 conhecimento: 170.050.0025.|S|?|?|
|8|Nome da Área de Conhecimento|?|object|Descrição da área de conhecimento do curso.|S|?|?|
|9|Código da Sub Área de Conhecimento|?|Int64|Código da sub-área do conhecimento. Exemplo: Área: 170 Subárea: 170.050 (Será o 050) conhecimento: 170.050.0025.|S|?|?|
|10|Nome da Sub Área de Conhecimento|?|object|Descrição da sub-área do conhecimento.|S|?|?|
|11|Código do Conhecimento do Curso|?|Int64|Código do conhecimento. Identifica o conhecimento do curso.|N|?|?|
|12|Nome do Conhecimento do Curso|?|object|Descrição do conhecimento do curso.|S|?|?|
|13|Quantidade de Carga Horária do Curso|?|Int64|Carga horária total do curso em horas|S|?|?|
|14|Código do Tipo da Formação Superior|?|Int64|Código identificador da formação superior. Ex:   35- Pós-Graduação;  36- Mestrado;  37- Doutorado. |S|?|?|
|15|Texto do Tipo da Formação Superior|?|object|Descrição da formação superior. |S|?|?|
|16|Código da Modalidade do Curso|?|Int64|Indica o código da modalidade do curso. Sendo: 01 - Presencial; 02 - Auto-instrucional; 03 - Em serviço; 09 - A regularizar |N|?|?|
|17|Código do Nível do Curso|?|Int64|Identificador do tipo do nível do curso (enfoque de aprendizagem). Sendo: 01 - Fundamental; 02 - Instrumental; 03 - Estratégico; 04 - Acadêmico; 09 - A classificar. |N|?|?|
|18|Código da Natureza do Curso|?|Int64|Identificador da natureza do curso. 01 - Atualização; 02 - Formação; 03 - Aperfeiçoamento; 04 - Qualificação. |N|?|?|
|19|Código do Tipo de Origem do Curso|?|Int64|Código dos tipos de origem do curso. 01 - Desenvolvido pelo banco; 02 - Contratado no mercado; 03 - Em parceria |N|?|?|
|20|Código do Tipo de Público|?|Int64|Código dos tipos de público (participação) que o curso pode ter. Ex.: 1- Interno;  2- externo; 3- misto. |N|?|?|
|21|Indicador de Vigência do Curso|?|object|Indica a utilização do curso. Possíveis valores: "S" - (SIM) Em Linha; "N" - (NÃO) Fora de linha |N|?|?|
|22|Indicador de Trilha de Estratégica|?|object|Indica se o curso faz parte da Trilha de Estratégica de Capacitação. Possíveis valores: "S" - (SIM); "N" - (NÃO)|N|?|?|
|23|Nome da Etapa|?|object|Descrição do tema da etapa de capacitação para os cursos que fazem parte da Trilha Estratégica. Possíveis valores: ASG, NEGOCIOS, LIDERANCA, TRANSFORMACAO DIGITAL. Formato: caixa alta, sem acentuação.|S|?|?|

<b>Regra 1:</b> todas as colunas de texto devem ser formatadas conforme o padrão caixa alta e sem acento.

<b>Regra 2:</b> os registros das colunas de texto que contiverem nulos deverão permanecer nulos ao final das transformações.

<b>Regra 3:</b> excluir registros que atendam a alguma das regras abaixo:

- quando o Texto do Objetivo do Curso for igual a 'TESTE EDUCA' ou 'TESTE GTD' ou 'TESTE' ou 'TESTANDO' ou 'DADFAFD' ou 'SGASDG' ou 'NXYZ' ou 'R';
- quando o Texto do Objetivo do Curso for igual a 'A' e o Código da Área de Conhecimento for nulo;
- quando o Nome do Curso contiver 'EXCEL TESTE' ou 'TESTE DISCIPLINA' ou 'EXCLUIR' ou 'ALURA';
- quando o Nome do curso for contiver 'TESTE' e o Código da Área de Conhecimento for nulo, com exceção do curso 7740;
- quando o Nome do curso for contiver 'TESTE' e o Texto do Objetivo do Curso for igual a '.';
- quando o Texto do Curso contiver 'TESTE MATERIAL' ou 'TESTE GERAL'.
- quando o Nome do curso ou o Texto do Curso contiverem 'EXCLUIDO'.

In [46]:
# ler o arquivo cso.zip e atribuir a uma variável: pd.read_csv()
cso01 = pd.read_csv('bases/CSO/cso01.zip', compression='zip', header=0)
cso02 = pd.read_csv('bases/CSO/cso02.zip', compression='zip', header=0)
cso03 = pd.read_csv('bases/CSO/cso03.zip', compression='zip', header=0)

In [47]:
#unir dataframes
cso = pd.concat([cso01,cso02,cso03])
cso.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 6359
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  int64
 7   CD_MDLD_CSO       34360 non-null  int64
 8   CD_NVL_CSO        34360 non-null  int64
 9   CD_NTZ_CSO        34360 non-null  int64
 10  CD_TIP_OGM_CSO    34360 non-null  int64
 11  CD_TIP_PBCO       34360 non-null  int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  float64
 13  IN_VGC_CSO        34360 non-null  object
 14  CGHR_CSO          5309 non-null   float64
dtypes: float64(2), int64(7), object(6)
memory usage: 4.2+ MB

In [48]:
cso.head()

,CD_CSO,NM_CSO,TX_CSO,TX_OBJT_CSO,TX_DSMP_EPRO,TX_OBJT_ESTG,CD_CNH_CSO,CD_MDLD_CSO,CD_NVL_CSO,CD_NTZ_CSO,CD_TIP_OGM_CSO,CD_TIP_PBCO,CD_TIP_FRMC_SUPR,IN_VGC_CSO,CGHR_CSO
0,1,EDUCA TESTE PRESENCIAL,EDUCA TESTE PRESENCIAL ...,teste educa,teste educa,teste educa,100010001,1,1,1,1,3,NaN,N,NaN
1,2,EDUCA TESTE AUTOINSTRUCIONAL,EDUCA TESTE AUTOINSTRUCIONAL ...,TESTE EDUCA,TESTE EDUCA,TESTE EDUCA,100010001,2,2,1,1,3,NaN,N,NaN
2,3,PFP,PLANEJAMENTO FINANCEIRO PESSOAL ...,Compreender a importância de gerir seus recurs...,a) Elaborar um planejamento financeiro pessoal...,Promover a educação financeira de clientes e f...,100600015,2,2,3,1,1,NaN,S,NaN
3,4,EXCEL TESTE,EXCEL BASICO ...,melhor..,Melhoria e agilidade nos processos ..,Prepar..,1607600030,1,2,1,2,1,NaN,S,4.0
4,5,TESTE EDUCA AI,TESTE EDUCA AUTO-INSTRUCIONAL ...,teste gtd,teste gtd,teste gtd,100010001,2,1,1,1,3,NaN,N,8.0

In [49]:
# ler o arquivo CNH e atribuir a uma variável: pd.read_csv()
CNH = pd.read_csv("bases/CNH.csv", sep=",")
CNH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3822 entries, 0 to 3821
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CD_CNH           3822 non-null   int64
 1   NM_CNH           3822 non-null   object
 2   IN_CNH_ATI       3822 non-null   object
 3   CD_AREA_CNH      3822 non-null   int64
 4   CD_SUB_AREA_CNH  3822 non-null   int64
dtypes: int64(3), object(2)
memory usage: 149.4+ KB

In [50]:
CNH.head()

,CD_CNH,NM_CNH,IN_CNH_ATI,CD_AREA_CNH,CD_SUB_AREA_CNH
0,100010000,ADMINISTRACAO DE EMPRESAS ...,N,10,1
1,100010001,TEORIA GERAL DA ADMINISTRAÇÃO ...,S,10,1
2,100010002,SISTEMA APOIO INTEGR. AS MICROS E PEQU. EMPRES...,S,10,1
3,100010003,EMPREENDEDORISMO ...,S,10,1
4,100010004,GESTAO EMPRESARIAL ...,S,10,1

In [51]:
# ler o arquivo AREA_CNH e atribuir a uma variável: pd.read_csv()
AREA_CNH = pd.read_csv("bases/AREA_CNH.csv", sep=",")
AREA_CNH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CD_AREA_CNH  25 non-null     int64
 1   NM_AREA_CNH  25 non-null     object
 2   IN_AREA_ATI  25 non-null     object
dtypes: int64(1), object(2)
memory usage: 728.0+ bytes

In [52]:
AREA_CNH.head()

   CD_AREA_CNH                                        NM_AREA_CNH IN_AREA_ATI
0           10  AREA DE ADMINISTRACAO                         ...           S
1           11  AREA DE CIENCIAS SOCIAS APLICADAS             ...           S
2           20  AREA DE ARTES                                 ...           S
3           25  AREA DE CIENCIA DA INFORMACAO                 ...           S
4           30  AREA DE CIENCIAS CONTABEIS                    ...           S

In [53]:
# ler o arquivo SUB_AREA_CNH e atribuir a uma variável: pd.read_csv()
SUB_AREA_CNH = pd.read_csv("bases/SUB_AREA_CNH.csv", sep=",")
SUB_AREA_CNH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CD_AREA_CNH      375 non-null    int64
 1   CD_SUB_AREA_CNH  375 non-null    int64
 2   NM_SUB_AREA_CNH  375 non-null    object
 3   IN_SUB_AREA_ATI  375 non-null    object
dtypes: int64(2), object(2)
memory usage: 11.8+ KB

In [54]:
SUB_AREA_CNH.head()

,CD_AREA_CNH,CD_SUB_AREA_CNH,NM_SUB_AREA_CNH,IN_SUB_AREA_ATI
0,10,1,ADMINISTRACAO DE EMPRESAS ...,S
1,10,20,ADM. - COMERCIO EXTERIOR ...,S
2,10,21,ADM. - FINANCAS INTERNACIONAIS ...,S
3,10,60,ADM. FINANCEIRA ...,S
4,10,80,ADMINISTRACAO HOSPITALAR ...,S

In [55]:
# ler o arquivo TIP_FRMC_SUPR e atribuir a uma variável: pd.read_csv()
TIP_FRMC_SUPR = pd.read_csv("bases/TIP_FRMC_SUPR.csv", sep=",")
TIP_FRMC_SUPR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_TIP_FRMC_SUPR  36 non-null     int64
 1   TX_TIP_FRMC_SUPR  36 non-null     object
 2   IN_VLD_REG        36 non-null     object
 3   NR_CTL_LOG        36 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.2+ KB

In [56]:
TIP_FRMC_SUPR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_TIP_FRMC_SUPR  36 non-null     int64
 1   TX_TIP_FRMC_SUPR  36 non-null     object
 2   IN_VLD_REG        36 non-null     object
 3   NR_CTL_LOG        36 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.2+ KB

In [57]:
TIP_FRMC_SUPR.head(36)

    CD_TIP_FRMC_SUPR                TX_TIP_FRMC_SUPR IN_VLD_REG  NR_CTL_LOG
0                  0  CONHECIMENTO TEORICO                    S           0
1                  9  CURSO TECNICO                           S           0
2                 15  CERT.CONHECIMENTO-Inscrição             S           0
3                 17  CERT.CONHECIMENTO BáSICO                S           0
4                 18  CERT.CONHECIMENTO INTERMEDI             S           0
5                 19  CERT.CONHECIMENTO AVAÇADO               S           0
6                 20  Foi descontinuado                       S           0
7                 21  Certificação Profissional               S           0
8                 22  PROVA DE SELECAO                        S           0
9                 25  CERTIFICACAO LEGAL BASICA               S           0
10                26  CERTIFICACAO LEGAL AVANCADA             S           0
11                27  CERT.LEGAL-OUTRAS                       S           0
12                29  CURSO SEQUENCIAL                        S           0
13                30  GRADUACAO COMPLETA                      S           0
14                31  POS-GRADUACAO/APERFEIÇOAMENTO           S           0
15                32  BB-MBA                                  S           0
16                33  EXT/APER/ESP>=360H                      S           0
17                34  BB-MBA - ESPECIALIZACAO                 S           0
18                35  POS-GRADUACAO LATO SENSU                S           0
19                36  MESTRADO                                S           0
20                37  DOUTORADO                               S           0
21                38  POS-DOUTORADO                           S           0
22                40  CERT./LINGUAS-BASICO 2 ANOS             S           0
23                41  CERT./LINGUAS-INTERM 2 ANOS             S           0
24                42  CERT./LINGUAS-INTERM 3 ANOS             S           0
25                43  CERT./LINGUAS-AVANCA 2 ANOS             S           0
26                44  CERT./LINGUAS-AVANCA 4 ANOS             S           0
27                45  CERT./LINGUAS-SUPERI 2 ANOS             S           0
28                46  CERT./LINGUAS-SUPERI 5 ANOS             S           0
29                47  CERT./LINGUAS-DOMINI 2 ANOS             S           0
30                48  CERT./LINGUAS-DOMINI PERM               S           0
31                56  Colaborador                             S           0
32                58  Mentor                                  S           0
33                60  Licença de Uso                          S           0
34                99  A CLASSIFICAR                           S           0
35                16  Certificação de Negócios                S           0

In [58]:
# ler o arquivo lista_treinamentos e atribuir a uma variável: pd.read_csv()
lista_treinamentos = pd.read_csv("bases/lista_treinamentos.csv", sep=",")
lista_treinamentos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Código Educa  89 non-null     int64
 1   Título        89 non-null     object
 2   Etapa         89 non-null     object
dtypes: int64(1), object(2)
memory usage: 2.2+ KB

In [59]:
#renomear coluna Código Educa  para   CD_CNH_CSO
lista_treinamentos.rename(columns={'Código Educa':'CD_CSO'}, inplace=True)
lista_treinamentos.rename(columns={'Etapa':'NM_ETP'}, inplace=True)
lista_treinamentos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CD_CSO  89 non-null     int64
 1   Título  89 non-null     object
 2   NM_ETP  89 non-null     object
dtypes: int64(1), object(2)
memory usage: 2.2+ KB

In [60]:
lista_treinamentos.head()

   CD_CSO                                   Título NM_ETP
0   11296  ÉTICA E BOAS PRÁTICAS DE RELACIONAMENTO    ASG
1    9733                        Princípios de ESG    ASG
2    9734                  Empresas ESG na prática    ASG
3    9735                            Regulação ESG    ASG
4    9736                            Liderança ESG    ASG

In [61]:
# unir os dois dataframes 'CSO' e 'TIP_FRMC_SUPR ' : .merge
exercicio6 = cso.merge(TIP_FRMC_SUPR, how='left', on='CD_TIP_FRMC_SUPR')
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 34359
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  int64
 7   CD_MDLD_CSO       34360 non-null  int64
 8   CD_NVL_CSO        34360 non-null  int64
 9   CD_NTZ_CSO        34360 non-null  int64
 10  CD_TIP_OGM_CSO    34360 non-null  int64
 11  CD_TIP_PBCO       34360 non-null  int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  float64
 13  IN_VGC_CSO        34360 non-null  object
 14  CGHR_CSO          5309 non-null   float64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  IN_VLD_REG        28722 non-null  object
 17  NR_CTL_LOG        28722 non-null  float64
dtypes: float64(3), int64(7), object(8)
memory usage: 5.0+ MB

In [62]:
#remover as colunas IN_VLD_REG e NR_CTL_LOG
exercicio6.drop(columns=['IN_VLD_REG', 'NR_CTL_LOG'], inplace=True)
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 34359
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  int64
 7   CD_MDLD_CSO       34360 non-null  int64
 8   CD_NVL_CSO        34360 non-null  int64
 9   CD_NTZ_CSO        34360 non-null  int64
 10  CD_TIP_OGM_CSO    34360 non-null  int64
 11  CD_TIP_PBCO       34360 non-null  int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  float64
 13  IN_VGC_CSO        34360 non-null  object
 14  CGHR_CSO          5309 non-null   float64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
dtypes: float64(2), int64(7), object(7)
memory usage: 4.5+ MB

In [63]:
# unir os dois dataframes 'AREA_CNH' e 'SUB_AREA_CNH': .merge
tabela1 = SUB_AREA_CNH.merge(AREA_CNH, how='left', on='CD_AREA_CNH')
tabela1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CD_AREA_CNH      375 non-null    int64
 1   CD_SUB_AREA_CNH  375 non-null    int64
 2   NM_SUB_AREA_CNH  375 non-null    object
 3   IN_SUB_AREA_ATI  375 non-null    object
 4   NM_AREA_CNH      374 non-null    object
 5   IN_AREA_ATI      374 non-null    object
dtypes: int64(2), object(4)
memory usage: 20.5+ KB

In [64]:
# unir os dois dataframes 'CNH' e 'tabela1': .merge
tabela2 = CNH.merge(tabela1, how='left', on=['CD_AREA_CNH', 'CD_SUB_AREA_CNH'])
tabela2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3822 entries, 0 to 3821
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CD_CNH           3822 non-null   int64
 1   NM_CNH           3822 non-null   object
 2   IN_CNH_ATI       3822 non-null   object
 3   CD_AREA_CNH      3822 non-null   int64
 4   CD_SUB_AREA_CNH  3822 non-null   int64
 5   NM_SUB_AREA_CNH  3818 non-null   object
 6   IN_SUB_AREA_ATI  3818 non-null   object
 7   NM_AREA_CNH      3815 non-null   object
 8   IN_AREA_ATI      3815 non-null   object
dtypes: int64(3), object(6)
memory usage: 298.6+ KB

In [65]:
#remover as colunas IN_CNH_ATI e IN_AREA_ATI e CD_SUB_AREA_CNH_y e IN_SUB_AREA_ATI)
tabela2.drop(columns=['IN_CNH_ATI', 'IN_AREA_ATI','IN_SUB_AREA_ATI'], inplace=True)

In [66]:
#renomear coluna CD_SUB_AREA_CNH_x  para CD_SUB_AREA_CNH
tabela2.rename(columns={'CD_SUB_AREA_CNH_x':'CD_SUB_AREA_CNH'}, inplace=True)
tabela2.rename(columns={'CD_CNH':'CD_CNH_CSO'}, inplace=True)
tabela2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3822 entries, 0 to 3821
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CD_CNH_CSO       3822 non-null   int64
 1   NM_CNH           3822 non-null   object
 2   CD_AREA_CNH      3822 non-null   int64
 3   CD_SUB_AREA_CNH  3822 non-null   int64
 4   NM_SUB_AREA_CNH  3818 non-null   object
 5   NM_AREA_CNH      3815 non-null   object
dtypes: int64(3), object(3)
memory usage: 209.0+ KB

In [67]:
# unir os dois dataframes 'exercicio6 e 'tabela2': .merge
exercicio6 = exercicio6.merge(tabela2, how='left', on='CD_CNH_CSO')
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 34359
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  int64
 7   CD_MDLD_CSO       34360 non-null  int64
 8   CD_NVL_CSO        34360 non-null  int64
 9   CD_NTZ_CSO        34360 non-null  int64
 10  CD_TIP_OGM_CSO    34360 non-null  int64
 11  CD_TIP_PBCO       34360 non-null  int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  float64
 13  IN_VGC_CSO        34360 non-null  object
 14  CGHR_CSO          5309 non-null   float64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  NM_CNH            34076 non-null  object
 17  CD_AREA_CNH       34076 non-null  float64
 18  CD_SUB_AREA_CNH   34076 non-null  float64
 19  NM_SUB_AREA_CNH   34076 non-null  object
 20  NM_AREA_CNH       34074 non-null  object
dtypes: float64(4), int64(7), object(10)
memory usage: 5.8+ MB

In [68]:
# unir os dois dataframes 'exercicio6 e 'lista_treinamentos': .merge
exercicio6 = exercicio6.merge(lista_treinamentos, how='left', on='CD_CSO')
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  int64
 7   CD_MDLD_CSO       34360 non-null  int64
 8   CD_NVL_CSO        34360 non-null  int64
 9   CD_NTZ_CSO        34360 non-null  int64
 10  CD_TIP_OGM_CSO    34360 non-null  int64
 11  CD_TIP_PBCO       34360 non-null  int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  float64
 13  IN_VGC_CSO        34360 non-null  object
 14  CGHR_CSO          5309 non-null   float64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  NM_CNH            34076 non-null  object
 17  CD_AREA_CNH       34076 non-null  float64
 18  CD_SUB_AREA_CNH   34076 non-null  float64
 19  NM_SUB_AREA_CNH   34076 non-null  object
 20  NM_AREA_CNH       34074 non-null  object
 21  Título            89 non-null     object
 22  NM_ETP            89 non-null     object
dtypes: float64(4), int64(7), object(12)
memory usage: 6.3+ MB

In [69]:
#remover as colunas Título            )
exercicio6.drop(columns=['Título'], inplace=True)
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 34359
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  int64
 7   CD_MDLD_CSO       34360 non-null  int64
 8   CD_NVL_CSO        34360 non-null  int64
 9   CD_NTZ_CSO        34360 non-null  int64
 10  CD_TIP_OGM_CSO    34360 non-null  int64
 11  CD_TIP_PBCO       34360 non-null  int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  float64
 13  IN_VGC_CSO        34360 non-null  object
 14  CGHR_CSO          5309 non-null   float64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  NM_CNH            34076 non-null  object
 17  CD_AREA_CNH       34076 non-null  float64
 18  CD_SUB_AREA_CNH   34076 non-null  float64
 19  NM_SUB_AREA_CNH   34076 non-null  object
 20  NM_AREA_CNH       34074 non-null  object
 21  NM_ETP            89 non-null     object
dtypes: float64(4), int64(7), object(11)
memory usage: 6.0+ MB

In [70]:
#Criar coluna com "S" ou "N" baseada na condição
exercicio6['IN_TRLA_ESTG'] = np.where(exercicio6['NM_ETP'] > '1', 'S', 'N')
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  int64
 7   CD_MDLD_CSO       34360 non-null  int64
 8   CD_NVL_CSO        34360 non-null  int64
 9   CD_NTZ_CSO        34360 non-null  int64
 10  CD_TIP_OGM_CSO    34360 non-null  int64
 11  CD_TIP_PBCO       34360 non-null  int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  float64
 13  IN_VGC_CSO        34360 non-null  object
 14  CGHR_CSO          5309 non-null   float64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  NM_CNH            34076 non-null  object
 17  CD_AREA_CNH       34076 non-null  float64
 18  CD_SUB_AREA_CNH   34076 non-null  float64
 19  NM_SUB_AREA_CNH   34076 non-null  object
 20  NM_AREA_CNH       34074 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34360 non-null  object
dtypes: float64(4), int64(7), object(12)
memory usage: 6.3+ MB

In [71]:
exercicio6[exercicio6['IN_TRLA_ESTG'] == 'S'].head()

,CD_CSO,NM_CSO,TX_CSO,TX_OBJT_CSO,TX_DSMP_EPRO,TX_OBJT_ESTG,CD_CNH_CSO,CD_MDLD_CSO,CD_NVL_CSO,CD_NTZ_CSO,...,IN_VGC_CSO,CGHR_CSO,TX_TIP_FRMC_SUPR,NM_CNH,CD_AREA_CNH,CD_SUB_AREA_CNH,NM_SUB_AREA_CNH,NM_AREA_CNH,NM_ETP,IN_TRLA_ESTG
344,200707,FEEDBACK: A ARTE DE ORIENTAR E,ALURA - FEEDBACK: A ARTE DE ORIENTAR E SER ORI...,FACA ESSE CURSO E: ENTENDA O QUE ESTA POR TRAS...,FACA ESSE CURSO E: ENTENDA O QUE ESTA POR TRAS...,Nao se Aplica,100900010,2,3,1,...,S,5.0,NaN,GESTAO DE INFORMACAO ...,10.0,90.0,ADM. - INFORMACAO ...,AREA DE ADMINISTRACAO ...,Liderança,S
1974,201080,MACHINE LEARNING PARTE 1: OTIM,ALURA - MACHINE LEARNING PARTE 1: OTIMIZACAO D...,FACA ESSE CURSO E: ENTENDA O QUE SAO HIPERPARA...,FACA ESSE CURSO E: ENTENDA O QUE SAO HIPERPARA...,Nao se Aplica,250100010,2,3,1,...,S,9.0,NaN,CIENCIA DA INFORMACAO ...,25.0,10.0,CIENCIA DA INFORMACAO ...,AREA DE CIENCIA DA INFORMACAO ...,Transformação Digital,S
2030,201088,GERENCIAMENTO DE INOVACAO ORGA,ALURA - GERENCIAMENTO DE INOVACAO ORGANIZACION...,FACA ESSE CURSO E: ENTENDA MELHOR DO QUE SE TR...,FACA ESSE CURSO E: ENTENDA MELHOR DO QUE SE TR...,Nao se Aplica,100900010,2,3,1,...,S,10.0,NaN,GESTAO DE INFORMACAO ...,10.0,90.0,ADM. - INFORMACAO ...,AREA DE ADMINISTRACAO ...,Transformação Digital,S
2033,201091,A EMPRESA AGIL: IMPLEMENTE O B,ALURA - A EMPRESA AGIL: IMPLEMENTE O BUSINESS ...,FACA ESSE CURSO E: APRENDA COMO UMA EMPRESA AP...,FACA ESSE CURSO E: APRENDA COMO UMA EMPRESA AP...,Nao se Aplica,100900010,2,3,1,...,S,6.0,NaN,GESTAO DE INFORMACAO ...,10.0,90.0,ADM. - INFORMACAO ...,AREA DE ADMINISTRACAO ...,Transformação Digital,S
2090,201103,MACHINE LEARNING PARTE 2: OTIM,ALURA - MACHINE LEARNING PARTE 2: OTIMIZACAO C...,FACA ESSE CURSO E: EXPLORE ESPACOS DE PARAMETR...,FACA ESSE CURSO E: EXPLORE ESPACOS DE PARAMETR...,Nao se Aplica,250100010,2,3,1,...,S,8.0,NaN,CIENCIA DA INFORMACAO ...,25.0,10.0,CIENCIA DA INFORMACAO ...,AREA DE CIENCIA DA INFORMACAO ...,Transformação Digital,S

In [72]:
#renomear colunas de acordo com o Glossário
exercicio6.rename(columns={'CGHR_CSO':'QT_CGHR_CSO'}, inplace=True)
exercicio6.rename(columns={'NM_CNH':'NM_CNH_CSO'}, inplace=True)
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  int64
 7   CD_MDLD_CSO       34360 non-null  int64
 8   CD_NVL_CSO        34360 non-null  int64
 9   CD_NTZ_CSO        34360 non-null  int64
 10  CD_TIP_OGM_CSO    34360 non-null  int64
 11  CD_TIP_PBCO       34360 non-null  int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  float64
 13  IN_VGC_CSO        34360 non-null  object
 14  QT_CGHR_CSO       5309 non-null   float64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  NM_CNH_CSO        34076 non-null  object
 17  CD_AREA_CNH       34076 non-null  float64
 18  CD_SUB_AREA_CNH   34076 non-null  float64
 19  NM_SUB_AREA_CNH   34076 non-null  object
 20  NM_AREA_CNH       34074 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34360 non-null  object
dtypes: float64(4), int64(7), object(12)
memory usage: 6.3+ MB

In [73]:
#converter as colunas abaixo para "Int64"
exercicio6['CD_CSO'] = exercicio6['CD_CSO'].astype("Int64")
exercicio6['CD_AREA_CNH'] = exercicio6['CD_AREA_CNH'].astype("Int64")
exercicio6['CD_SUB_AREA_CNH'] = exercicio6['CD_SUB_AREA_CNH'].astype("Int64")
exercicio6['CD_CNH_CSO'] = exercicio6['CD_CNH_CSO'].astype("Int64")
exercicio6['QT_CGHR_CSO'] = exercicio6['QT_CGHR_CSO'].astype("Int64")
exercicio6['CD_TIP_FRMC_SUPR'] = exercicio6['CD_TIP_FRMC_SUPR'].astype("Int64")
exercicio6['CD_MDLD_CSO'] = exercicio6['CD_MDLD_CSO'].astype("Int64")
exercicio6['CD_NVL_CSO'] = exercicio6['CD_NVL_CSO'].astype("Int64")
exercicio6['CD_NTZ_CSO'] = exercicio6['CD_NTZ_CSO'].astype("Int64")
exercicio6['CD_TIP_OGM_CSO'] = exercicio6['CD_TIP_OGM_CSO'].astype("Int64")
exercicio6['CD_TIP_PBCO'] = exercicio6['CD_TIP_PBCO'].astype("Int64")
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  Int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  Int64
 7   CD_MDLD_CSO       34360 non-null  Int64
 8   CD_NVL_CSO        34360 non-null  Int64
 9   CD_NTZ_CSO        34360 non-null  Int64
 10  CD_TIP_OGM_CSO    34360 non-null  Int64
 11  CD_TIP_PBCO       34360 non-null  Int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  Int64
 13  IN_VGC_CSO        34360 non-null  object
 14  QT_CGHR_CSO       5309 non-null   Int64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  NM_CNH_CSO        34076 non-null  object
 17  CD_AREA_CNH       34076 non-null  Int64
 18  CD_SUB_AREA_CNH   34076 non-null  Int64
 19  NM_SUB_AREA_CNH   34076 non-null  object
 20  NM_AREA_CNH       34074 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34360 non-null  object
dtypes: Int64(11), object(12)
memory usage: 6.7+ MB

In [74]:
# Regra 1: todas as colunas de texto devem ser formatadas conforme o padrão caixa alta e sem acento.
#Regra 2: os registros das colunas de texto que contiverem nulos deverão permanecer nulos ao final das transformações.
# Função para remover acentos e converter para caixa alta, preservando valores nulos

columns_to_format = ['NM_CSO','TX_CSO','TX_OBJT_CSO','TX_DSMP_EPRO','TX_OBJT_ESTG','NM_AREA_CNH',
                     'NM_SUB_AREA_CNH','NM_CNH_CSO','TX_TIP_FRMC_SUPR','IN_VGC_CSO','NM_ETP']

for col in columns_to_format:
    exercicio6[col] = exercicio6[col].apply(lambda x: unidecode(x.upper()) if isinstance(x, str) else x)

#def format_text(x):
#    if pd.isna(x):
#        return x
#    return unidecode(str(x)).upper()

# Aplicar a função de formatação a várias colunas
#columns_to_format = ['NM_CSO','TX_CSO','TX_OBJT_CSO','TX_DSMP_EPRO','TX_OBJT_ESTG','NM_AREA_CNH',
#                     'NM_SUB_AREA_CNH','NM_CNH_CSO','TX_TIP_FRMC_SUPR','IN_VGC_CSO','NM_ETP']
#for col in columns_to_format:
#    exercicio6[col] = exercicio6[col].apply(format_text)

exercicio6.head()

,CD_CSO,NM_CSO,TX_CSO,TX_OBJT_CSO,TX_DSMP_EPRO,TX_OBJT_ESTG,CD_CNH_CSO,CD_MDLD_CSO,CD_NVL_CSO,CD_NTZ_CSO,...,IN_VGC_CSO,QT_CGHR_CSO,TX_TIP_FRMC_SUPR,NM_CNH_CSO,CD_AREA_CNH,CD_SUB_AREA_CNH,NM_SUB_AREA_CNH,NM_AREA_CNH,NM_ETP,IN_TRLA_ESTG
0,1,EDUCA TESTE PRESENCIAL,EDUCA TESTE PRESENCIAL ...,TESTE EDUCA,TESTE EDUCA,TESTE EDUCA,100010001,1,1,1,...,N,<NA>,NaN,TEORIA GERAL DA ADMINISTRACAO ...,10,1,ADMINISTRACAO DE EMPRESAS ...,AREA DE ADMINISTRACAO ...,NaN,N
1,2,EDUCA TESTE AUTOINSTRUCIONAL,EDUCA TESTE AUTOINSTRUCIONAL ...,TESTE EDUCA,TESTE EDUCA,TESTE EDUCA,100010001,2,2,1,...,N,<NA>,NaN,TEORIA GERAL DA ADMINISTRACAO ...,10,1,ADMINISTRACAO DE EMPRESAS ...,AREA DE ADMINISTRACAO ...,NaN,N
2,3,PFP,PLANEJAMENTO FINANCEIRO PESSOAL ...,COMPREENDER A IMPORTANCIA DE GERIR SEUS RECURS...,A) ELABORAR UM PLANEJAMENTO FINANCEIRO PESSOAL...,PROMOVER A EDUCACAO FINANCEIRA DE CLIENTES E F...,100600015,2,2,3,...,S,<NA>,NaN,PLANEJAMENTO FINANCEIRO PESSOAL ...,10,60,ADM. FINANCEIRA ...,AREA DE ADMINISTRACAO ...,NaN,N
3,4,EXCEL TESTE,EXCEL BASICO ...,MELHOR..,MELHORIA E AGILIDADE NOS PROCESSOS ..,PREPAR..,1607600030,1,2,1,...,S,4,NaN,INFORMATICA - CONHEC. GERAIS ...,160,760,ENGENHARIA DE COMPUTACAO ...,COMPUTACAO ...,NaN,N
4,5,TESTE EDUCA AI,TESTE EDUCA AUTO-INSTRUCIONAL ...,TESTE GTD,TESTE GTD,TESTE GTD,100010001,2,1,1,...,N,8,NaN,TEORIA GERAL DA ADMINISTRACAO ...,10,1,ADMINISTRACAO DE EMPRESAS ...,AREA DE ADMINISTRACAO ...,NaN,N

In [75]:

# Lista de informações para conferência com original
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34360 entries, 0 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34360 non-null  Int64
 1   NM_CSO            34360 non-null  object
 2   TX_CSO            34360 non-null  object
 3   TX_OBJT_CSO       34360 non-null  object
 4   TX_DSMP_EPRO      33615 non-null  object
 5   TX_OBJT_ESTG      34353 non-null  object
 6   CD_CNH_CSO        34360 non-null  Int64
 7   CD_MDLD_CSO       34360 non-null  Int64
 8   CD_NVL_CSO        34360 non-null  Int64
 9   CD_NTZ_CSO        34360 non-null  Int64
 10  CD_TIP_OGM_CSO    34360 non-null  Int64
 11  CD_TIP_PBCO       34360 non-null  Int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  Int64
 13  IN_VGC_CSO        34360 non-null  object
 14  QT_CGHR_CSO       5309 non-null   Int64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  NM_CNH_CSO        34076 non-null  object
 17  CD_AREA_CNH       34076 non-null  Int64
 18  CD_SUB_AREA_CNH   34076 non-null  Int64
 19  NM_SUB_AREA_CNH   34076 non-null  object
 20  NM_AREA_CNH       34074 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34360 non-null  object
dtypes: Int64(11), object(12)
memory usage: 6.7+ MB

In [76]:
#Regra1
regra1 = exercicio6[~exercicio6['TX_OBJT_CSO'].isin(['TESTE EDUCA', 'TESTE GTD', 'TESTE', 'TESTANDO', 'DADFAFD', 'SGASDG', 'NXYZ', 'R'])]
regra1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34345 entries, 2 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34345 non-null  Int64
 1   NM_CSO            34345 non-null  object
 2   TX_CSO            34345 non-null  object
 3   TX_OBJT_CSO       34345 non-null  object
 4   TX_DSMP_EPRO      33600 non-null  object
 5   TX_OBJT_ESTG      34338 non-null  object
 6   CD_CNH_CSO        34345 non-null  Int64
 7   CD_MDLD_CSO       34345 non-null  Int64
 8   CD_NVL_CSO        34345 non-null  Int64
 9   CD_NTZ_CSO        34345 non-null  Int64
 10  CD_TIP_OGM_CSO    34345 non-null  Int64
 11  CD_TIP_PBCO       34345 non-null  Int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  Int64
 13  IN_VGC_CSO        34345 non-null  object
 14  QT_CGHR_CSO       5302 non-null   Int64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  NM_CNH_CSO        34064 non-null  object
 17  CD_AREA_CNH       34064 non-null  Int64
 18  CD_SUB_AREA_CNH   34064 non-null  Int64
 19  NM_SUB_AREA_CNH   34064 non-null  object
 20  NM_AREA_CNH       34062 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34345 non-null  object
dtypes: Int64(11), object(12)
memory usage: 6.6+ MB

In [77]:
#Regra2
regra2 = regra1[~((regra1['TX_OBJT_CSO'] == 'A') & regra1['CD_AREA_CNH'].isna())]
regra2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34341 entries, 2 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34341 non-null  Int64
 1   NM_CSO            34341 non-null  object
 2   TX_CSO            34341 non-null  object
 3   TX_OBJT_CSO       34341 non-null  object
 4   TX_DSMP_EPRO      33596 non-null  object
 5   TX_OBJT_ESTG      34334 non-null  object
 6   CD_CNH_CSO        34341 non-null  Int64
 7   CD_MDLD_CSO       34341 non-null  Int64
 8   CD_NVL_CSO        34341 non-null  Int64
 9   CD_NTZ_CSO        34341 non-null  Int64
 10  CD_TIP_OGM_CSO    34341 non-null  Int64
 11  CD_TIP_PBCO       34341 non-null  Int64
 12  CD_TIP_FRMC_SUPR  28722 non-null  Int64
 13  IN_VGC_CSO        34341 non-null  object
 14  QT_CGHR_CSO       5299 non-null   Int64
 15  TX_TIP_FRMC_SUPR  28722 non-null  object
 16  NM_CNH_CSO        34064 non-null  object
 17  CD_AREA_CNH       34064 non-null  Int64
 18  CD_SUB_AREA_CNH   34064 non-null  Int64
 19  NM_SUB_AREA_CNH   34064 non-null  object
 20  NM_AREA_CNH       34062 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34341 non-null  object
dtypes: Int64(11), object(12)
memory usage: 6.6+ MB

In [78]:
#Regra3
regra3 = regra2[~regra2['NM_CSO'].str.contains('EXCEL TESTE|TESTE DISCIPLINA|EXCLUIR|ALURA', na=False)]
regra3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34335 entries, 2 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34335 non-null  Int64
 1   NM_CSO            34335 non-null  object
 2   TX_CSO            34335 non-null  object
 3   TX_OBJT_CSO       34335 non-null  object
 4   TX_DSMP_EPRO      33590 non-null  object
 5   TX_OBJT_ESTG      34328 non-null  object
 6   CD_CNH_CSO        34335 non-null  Int64
 7   CD_MDLD_CSO       34335 non-null  Int64
 8   CD_NVL_CSO        34335 non-null  Int64
 9   CD_NTZ_CSO        34335 non-null  Int64
 10  CD_TIP_OGM_CSO    34335 non-null  Int64
 11  CD_TIP_PBCO       34335 non-null  Int64
 12  CD_TIP_FRMC_SUPR  28720 non-null  Int64
 13  IN_VGC_CSO        34335 non-null  object
 14  QT_CGHR_CSO       5297 non-null   Int64
 15  TX_TIP_FRMC_SUPR  28720 non-null  object
 16  NM_CNH_CSO        34060 non-null  object
 17  CD_AREA_CNH       34060 non-null  Int64
 18  CD_SUB_AREA_CNH   34060 non-null  Int64
 19  NM_SUB_AREA_CNH   34060 non-null  object
 20  NM_AREA_CNH       34058 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34335 non-null  object
dtypes: Int64(11), object(12)
memory usage: 6.6+ MB

In [79]:
#Regra4
regra4 = regra3[~(((regra3['NM_CSO'].str.contains('TESTE', na=False)) & regra3['CD_AREA_CNH'].isna()) & (regra3['CD_CSO'] != 7740))]
regra4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34330 entries, 2 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34330 non-null  Int64
 1   NM_CSO            34330 non-null  object
 2   TX_CSO            34330 non-null  object
 3   TX_OBJT_CSO       34330 non-null  object
 4   TX_DSMP_EPRO      33585 non-null  object
 5   TX_OBJT_ESTG      34323 non-null  object
 6   CD_CNH_CSO        34330 non-null  Int64
 7   CD_MDLD_CSO       34330 non-null  Int64
 8   CD_NVL_CSO        34330 non-null  Int64
 9   CD_NTZ_CSO        34330 non-null  Int64
 10  CD_TIP_OGM_CSO    34330 non-null  Int64
 11  CD_TIP_PBCO       34330 non-null  Int64
 12  CD_TIP_FRMC_SUPR  28719 non-null  Int64
 13  IN_VGC_CSO        34330 non-null  object
 14  QT_CGHR_CSO       5296 non-null   Int64
 15  TX_TIP_FRMC_SUPR  28719 non-null  object
 16  NM_CNH_CSO        34060 non-null  object
 17  CD_AREA_CNH       34060 non-null  Int64
 18  CD_SUB_AREA_CNH   34060 non-null  Int64
 19  NM_SUB_AREA_CNH   34060 non-null  object
 20  NM_AREA_CNH       34058 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34330 non-null  object
dtypes: Int64(11), object(12)
memory usage: 6.6+ MB

In [80]:
#Regra5
regra5 = regra4[~(regra4['NM_CSO'].str.contains('TESTE', na=False) & (regra4['TX_OBJT_CSO']=='.'))]
regra5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34329 entries, 2 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34329 non-null  Int64
 1   NM_CSO            34329 non-null  object
 2   TX_CSO            34329 non-null  object
 3   TX_OBJT_CSO       34329 non-null  object
 4   TX_DSMP_EPRO      33584 non-null  object
 5   TX_OBJT_ESTG      34322 non-null  object
 6   CD_CNH_CSO        34329 non-null  Int64
 7   CD_MDLD_CSO       34329 non-null  Int64
 8   CD_NVL_CSO        34329 non-null  Int64
 9   CD_NTZ_CSO        34329 non-null  Int64
 10  CD_TIP_OGM_CSO    34329 non-null  Int64
 11  CD_TIP_PBCO       34329 non-null  Int64
 12  CD_TIP_FRMC_SUPR  28719 non-null  Int64
 13  IN_VGC_CSO        34329 non-null  object
 14  QT_CGHR_CSO       5296 non-null   Int64
 15  TX_TIP_FRMC_SUPR  28719 non-null  object
 16  NM_CNH_CSO        34059 non-null  object
 17  CD_AREA_CNH       34059 non-null  Int64
 18  CD_SUB_AREA_CNH   34059 non-null  Int64
 19  NM_SUB_AREA_CNH   34059 non-null  object
 20  NM_AREA_CNH       34057 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34329 non-null  object
dtypes: Int64(11), object(12)
memory usage: 6.6+ MB

In [81]:
#Regra6
regra6 = regra5[~regra4['TX_CSO'].str.contains('TESTE MATERIAL|TESTE GERAL', na=False)]
regra6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34327 entries, 2 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34327 non-null  Int64
 1   NM_CSO            34327 non-null  object
 2   TX_CSO            34327 non-null  object
 3   TX_OBJT_CSO       34327 non-null  object
 4   TX_DSMP_EPRO      33582 non-null  object
 5   TX_OBJT_ESTG      34320 non-null  object
 6   CD_CNH_CSO        34327 non-null  Int64
 7   CD_MDLD_CSO       34327 non-null  Int64
 8   CD_NVL_CSO        34327 non-null  Int64
 9   CD_NTZ_CSO        34327 non-null  Int64
 10  CD_TIP_OGM_CSO    34327 non-null  Int64
 11  CD_TIP_PBCO       34327 non-null  Int64
 12  CD_TIP_FRMC_SUPR  28719 non-null  Int64
 13  IN_VGC_CSO        34327 non-null  object
 14  QT_CGHR_CSO       5295 non-null   Int64
 15  TX_TIP_FRMC_SUPR  28719 non-null  object
 16  NM_CNH_CSO        34057 non-null  object
 17  CD_AREA_CNH       34057 non-null  Int64
 18  CD_SUB_AREA_CNH   34057 non-null  Int64
 19  NM_SUB_AREA_CNH   34057 non-null  object
 20  NM_AREA_CNH       34055 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34327 non-null  object
dtypes: Int64(11), object(12)
memory usage: 6.6+ MB

In [82]:
#Regra7
exercicio6 = regra6[~(regra6['NM_CSO'].str.contains('EXCLUIDO', na=False) | regra6['TX_CSO'].str.contains('EXCLUIDO', na=False))]
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34322 entries, 2 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34322 non-null  Int64
 1   NM_CSO            34322 non-null  object
 2   TX_CSO            34322 non-null  object
 3   TX_OBJT_CSO       34322 non-null  object
 4   TX_DSMP_EPRO      33577 non-null  object
 5   TX_OBJT_ESTG      34315 non-null  object
 6   CD_CNH_CSO        34322 non-null  Int64
 7   CD_MDLD_CSO       34322 non-null  Int64
 8   CD_NVL_CSO        34322 non-null  Int64
 9   CD_NTZ_CSO        34322 non-null  Int64
 10  CD_TIP_OGM_CSO    34322 non-null  Int64
 11  CD_TIP_PBCO       34322 non-null  Int64
 12  CD_TIP_FRMC_SUPR  28717 non-null  Int64
 13  IN_VGC_CSO        34322 non-null  object
 14  QT_CGHR_CSO       5295 non-null   Int64
 15  TX_TIP_FRMC_SUPR  28717 non-null  object
 16  NM_CNH_CSO        34052 non-null  object
 17  CD_AREA_CNH       34052 non-null  Int64
 18  CD_SUB_AREA_CNH   34052 non-null  Int64
 19  NM_SUB_AREA_CNH   34052 non-null  object
 20  NM_AREA_CNH       34050 non-null  object
 21  NM_ETP            89 non-null     object
 22  IN_TRLA_ESTG      34322 non-null  object
dtypes: Int64(11), object(12)
memory usage: 6.6+ MB

In [83]:
# Reordedar as colunas
colunas_exercicio6 = ['CD_CSO','NM_CSO','TX_CSO','TX_OBJT_CSO','TX_DSMP_EPRO','TX_OBJT_ESTG','CD_AREA_CNH','NM_AREA_CNH','CD_SUB_AREA_CNH',
                    'NM_SUB_AREA_CNH','CD_CNH_CSO','NM_CNH_CSO','QT_CGHR_CSO','CD_TIP_FRMC_SUPR','TX_TIP_FRMC_SUPR','CD_MDLD_CSO', 'CD_NVL_CSO',
                    'CD_NTZ_CSO','CD_TIP_OGM_CSO', 'CD_TIP_PBCO', 'IN_VGC_CSO','IN_TRLA_ESTG','NM_ETP']

exercicio6 = exercicio6[colunas_exercicio6]
exercicio6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34322 entries, 2 to 34359
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_CSO            34322 non-null  Int64
 1   NM_CSO            34322 non-null  object
 2   TX_CSO            34322 non-null  object
 3   TX_OBJT_CSO       34322 non-null  object
 4   TX_DSMP_EPRO      33577 non-null  object
 5   TX_OBJT_ESTG      34315 non-null  object
 6   CD_AREA_CNH       34052 non-null  Int64
 7   NM_AREA_CNH       34050 non-null  object
 8   CD_SUB_AREA_CNH   34052 non-null  Int64
 9   NM_SUB_AREA_CNH   34052 non-null  object
 10  CD_CNH_CSO        34322 non-null  Int64
 11  NM_CNH_CSO        34052 non-null  object
 12  QT_CGHR_CSO       5295 non-null   Int64
 13  CD_TIP_FRMC_SUPR  28717 non-null  Int64
 14  TX_TIP_FRMC_SUPR  28717 non-null  object
 15  CD_MDLD_CSO       34322 non-null  Int64
 16  CD_NVL_CSO        34322 non-null  Int64
 17  CD_NTZ_CSO        34322 non-null  Int64
 18  CD_TIP_OGM_CSO    34322 non-null  Int64
 19  CD_TIP_PBCO       34322 non-null  Int64
 20  IN_VGC_CSO        34322 non-null  object
 21  IN_TRLA_ESTG      34322 non-null  object
 22  NM_ETP            89 non-null     object
dtypes: Int64(11), object(12)
memory usage: 6.6+ MB

# Exercício 7 - Nova tabela de UOR

<b>Nível de dificuldade (1 a 5):</b> 4

<b>Requisitos:</b> exercícios 1 e 2

Criar um DataFrame Pandas chamado <b>exercicio7</b> contendo as informações das UOR e Vice-Presidência jurisdicionante, conforme abaixo:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|1|Código da Dependência da Unidade Organizacional|?|Int64|Código identificador de Dependências de Instituições Organizacionais. No BB atualmente é utilizado os domínios entre 1 e 9999.|N|?|?
|2|Código da Unidade Organizacional|?|Int64|Código identificador de Unidade Organizacional (UOR) do conglomerado Banco do Brasil (no Brasil e Exterior) ou UOR externas que o BB tenha algum tipo de relacionamento ou interesse em identificá-las.|N|?|?
|3|Sigla da Unidade Organizacional|?|object|Reunião das letras iniciais dos vocábulos fundamentais de uma denominação ou título, sem articulação prosódica, constituindo meras abreviaturas. Ex.: "DITEC", "GBASE", "DIREO", "PRESI", etc.|S|?|?
|4|Nome da Unidade Organizacional Reduzido|?|object|Nome reduzido da Unidade Organizacional.|N|?|?
|5|Código da Dependência da Vice-Presidência|?|Int64|Código identificador da Dependência da Vice-Presidência jurisdicionante da UOR.|S|?|?
|6|Sigla da Vice-Presidência|?|object|Sigla da Vice-Presidência jurisdicionante da UOR.|S|?|?

<b>Regra:</b> considere apenas as UORs cujo Item de Arquitetura corresponda a "DIRETORIA" ou "UNIDADE".

<b>Dica:</b> atenção no momento de fazer a junção das tabelas de UOR e Vínculo de UOR. Lembrando que uma mesma dependência possui várias UORs além da principal. Consulte a documentação das tabelas.

In [84]:
# Salvar o DataFrame com um delimitador de ponto e vírgula
#exercicio2.to_csv('exercicio2.csv', sep=';', index=False)

In [85]:
#Regra: considere apenas as UORs cujo Item de Arquitetura corresponda a "DIRETORIA" ou "UNIDADE".
#Filtro de cod de arquitetura para unidade ou diretoria (2 e 3).
exercicio7_1 = exercicio2.copy()[exercicio2.copy()['CD_ITEM_AQTT_UOR'].isin([2,3])]
exercicio7_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57 entries, 4922 to 6422
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR            57 non-null     Int64
 1   NM_UOR_RDZ        57 non-null     object
 2   SG_UOR            57 non-null     object
 3   DT_INC_VLD        57 non-null     datetime64[ns]
 4   CD_ITEM_AQTT_UOR  57 non-null     Int64
 5   CD_TIP_UOR        57 non-null     Int64
 6   CD_DEPE_UOR       57 non-null     Int64
 7   NR_ORD_DEPE_SBDD  57 non-null     Int64
dtypes: Int64(5), datetime64[ns](1), object(2)
memory usage: 4.3+ KB

In [86]:
exercicio7_1.head(57)

,CD_UOR,NM_UOR_RDZ,SG_UOR,DT_INC_VLD,CD_ITEM_AQTT_UOR,CD_TIP_UOR,CD_DEPE_UOR,NR_ORD_DEPE_SBDD
4922,4923,AUDITORIA INTERNA,AUDIT,1901-01-01,3,4,8150,0
5095,5096,SECEX-SEC EXECUTIVA,SECEX,1995-02-16,3,4,8537,0
5107,5108,DIRCO-CONTROLADORIA,DIRCO,1995-10-09,2,4,8550,0
5110,5111,DIJUR-JURIDICA,DIJUR,1996-03-29,2,4,8553,0
5112,5113,TESOU-TESOUR. GLOBAL,TESOU,1996-07-19,3,4,8555,0
5113,5114,DICRE/RISCO CREDITO,DICRE,1996-03-29,3,4,8556,0
5114,5115,DIFIN-FINANCAS,DIFIN,1996-03-29,2,4,8557,0
5115,5116,DISEC-SUP INFR PATR,DISEC,1996-03-29,2,4,8558,0
5116,5117,DIPES-CULT E PESSOAS,DIPES,1996-03-29,2,4,8559,0
5147,5148,DICOR-CORPORATE BANK,DICOR,1996-03-29,2,4,8590,0
5149,5150,DIVAR-COMERCIAL VAR,DIVAR,1996-03-29,2,4,8592,0
5150,5151,DIGOV-GOVERNO,DIGOV,1996-03-29,2,4,8593,0
5152,5153,UCR-COBRANCA E REEST,UCR,1996-03-29,3,4,8595,0
5153,5154,DIRAG-AGRONEGOCIOS,DIRAG,1996-03-29,2,4,8596,0
5181,5182,DICRE-CREDITO,DICRE,1996-03-29,2,4,8624,0
5184,5185,URI-REL.INVESTIDORES,URI,1996-03-29,3,4,8627,0
5535,5536,OUVIDORIA,OUVID,1998-03-05,3,4,8948,0
6106,6107,COGER-CONTADORIA,COGER,1999-03-08,2,4,9568,0
6108,6109,DICOI-CONTR.INTERNOS,DICOI,1999-06-02,2,4,9572,0
6134,6135,DIRIS-GESTAO RISCOS,DIRIS,1999-12-14,2,4,9599,0
6135,6136,DIOPE-OPERACOES,DIOPE,1999-04-27,2,4,9600,0
6389,6390,CIB-CORP INVEST BANK,CIB,2000-11-06,2,4,9867,0
6398,6399,CLIENTES-MPE,MPE,2001-01-09,3,4,9879,0
6410,6411,DITEC-TECNOLOGIA,DITEC,2001-07-03,2,4,9903,0
6412,6413,DITEC-UOS,UOS,2001-07-03,3,4,9905,0
6465,6466,DITEC/UEC II,UECII,2001-07-03,3,4,9909,0
6466,6467,DITEC/UEC I,UECI,2001-07-03,3,4,9910,0
6469,6470,DIMAC-MARKETING COM.,DIMAC,2001-09-29,2,4,9984,0
6470,6471,DIREO-ESTRAT.ORG.,DIREO,2001-09-29,2,4,9990,0
7046,7047,DISEM-SOLUC EMPRES,DISEM,2004-05-12,2,4,9951,0
7512,7513,UPB-PRIVATE BANK,UPB,2005-12-22,3,4,9882,0
7669,7670,DIMEP-MEIOS PAGAMEN.,DIMEP,2007-08-30,2,4,9880,0
7670,7671,DIEMP-EMPREST.FINANC,DIEMP,2007-08-30,2,4,9973,0
7671,7672,DIPRO-SEGURIDADE,DISEG,2007-08-30,2,4,9974,0
8464,8465,USD-SEG DIGITAL INF.,USD,2009-06-02,3,4,9548,0
9206,9207,DISUD-DISTR. SUDESTE,DISUD,2009-11-11,2,4,8477,0
9597,9598,DIREC-CLI. VAR. PF,DIREC,2011-05-10,2,4,8008,0
11060,11061,UNC-CANAIS,UNC,2011-10-18,3,4,8630,0
36569,36570,UPE-PART.PARC.ESTRAT,UGE,2011-11-17,3,4,9510,0
38667,38668,USI-SEGUR. INST.,USI,2014-05-15,3,4,8896,0
38851,38852,DINED-NEG. DIGITAIS,DINED,2015-04-08,2,4,9897,0
39060,39061,UGP-GOV. TI PROC.,UGP,2016-03-07,3,4,9928,0
39650,39651,UNV-INTEGR. VAREJO,UNV,2017-06-14,3,4,9500,0
39659,39660,UCI-CAPTACAO INVEST.,UCI,2017-07-05,3,4,9797,0
39762,39763,UNI-NEG. INTERNAC.,UNI,2017-11-20,3,4,9958,0
40001,40002,UAV-NEG.VAR.SETOR P.,UAV,2018-12-17,3,4,9270,0
40002,40003,DIRAV-ALTO VAREJO,DIRAV,2018-12-17,2,4,9220,0
40003,40004,UAC-AT CAN FIS E DIG,UAC,2018-12-17,3,4,9010,0
40065,40066,UAN-IA. ANALITICA,UAN,2019-06-19,3,4,9968,0
43772,43773,ASG,ASG,2021-01-14,3,4,9720,0
43781,43782,TESOUR. GLOBAL,TESOU,2021-01-27,3,4,9072,0
43833,43834,UEG-ESTR. GOVERNO,UEG,2021-07-28,3,4,9240,0
44166,44167,CRM-INDUCAO DIGITAL,CRM,2023-09-28,3,4,9045,0
44167,44168,PROG. INOVA VAREJO,INOVA,2023-09-28,3,4,9078,0
44168,44169,UNJ-EMP FIN PJ,UNJ,2023-09-28,3,4,9089,0
2784,47785,DITEC-UEC II,UECII,2011-01-25,3,4,9903,1
6422,51423,DITEC-UEC I,UEC I,2011-01-25,3,4,9903,2

In [87]:
#Ai faço a vinculação filtrando o tipo de vinculacao para vice presidencia CD_TIP_VCL (1220).
exercicio7_2 = exercicio1.copy()[exercicio1.copy()['CD_TIP_VCL'] == 1220]
exercicio7_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1308 entries, 9 to 40846
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR_VCLD       1308 non-null   Int64
 1   CD_TIP_VCL        1308 non-null   Int64
 2   CD_UOR_VCLR       1308 non-null   Int64
 3   NR_ITVL_NVL_HRQO  1308 non-null   Int64
dtypes: Int64(4)
memory usage: 56.2 KB

In [88]:
exercicio7_2.head()

     CD_UOR_VCLD  CD_TIP_VCL  CD_UOR_VCLR  NR_ITVL_NVL_HRQO
9           9598        1220         4924                 1
48         51461        1220         4924                 2
73         54414        1220         7660                 2
95         56844        1220         7660                 2
116        58927        1220         4924                 2

In [89]:
# Junção das tabelas usando a coluna exercicio7_1.merge(exercicio7_2, how = 'left', left_on = 'CD_UOR', right_on = 'CD_UOR_VCLD')
exercicio7 = exercicio7_1.merge(exercicio7_2, how = 'left', left_on = 'CD_UOR', right_on = 'CD_UOR_VCLD')
exercicio7.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57 entries, 0 to 56
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR            57 non-null     Int64
 1   NM_UOR_RDZ        57 non-null     object
 2   SG_UOR            57 non-null     object
 3   DT_INC_VLD        57 non-null     datetime64[ns]
 4   CD_ITEM_AQTT_UOR  57 non-null     Int64
 5   CD_TIP_UOR        57 non-null     Int64
 6   CD_DEPE_UOR       57 non-null     Int64
 7   NR_ORD_DEPE_SBDD  57 non-null     Int64
 8   CD_UOR_VCLD       39 non-null     Int64
 9   CD_TIP_VCL        39 non-null     Int64
 10  CD_UOR_VCLR       39 non-null     Int64
 11  NR_ITVL_NVL_HRQO  39 non-null     Int64
dtypes: Int64(9), datetime64[ns](1), object(2)
memory usage: 6.3+ KB

In [90]:
exercicio7.head(57)

,CD_UOR,NM_UOR_RDZ,SG_UOR,DT_INC_VLD,CD_ITEM_AQTT_UOR,CD_TIP_UOR,CD_DEPE_UOR,NR_ORD_DEPE_SBDD,CD_UOR_VCLD,CD_TIP_VCL,CD_UOR_VCLR,NR_ITVL_NVL_HRQO
0,4923,AUDITORIA INTERNA,AUDIT,1901-01-01,3,4,8150,0,<NA>,<NA>,<NA>,<NA>
1,5096,SECEX-SEC EXECUTIVA,SECEX,1995-02-16,3,4,8537,0,<NA>,<NA>,<NA>,<NA>
2,5108,DIRCO-CONTROLADORIA,DIRCO,1995-10-09,2,4,8550,0,5108,1220,4918,1
3,5111,DIJUR-JURIDICA,DIJUR,1996-03-29,2,4,8553,0,<NA>,<NA>,<NA>,<NA>
4,5113,TESOU-TESOUR. GLOBAL,TESOU,1996-07-19,3,4,8555,0,<NA>,<NA>,<NA>,<NA>
5,5114,DICRE/RISCO CREDITO,DICRE,1996-03-29,3,4,8556,0,5114,1220,6134,2
6,5115,DIFIN-FINANCAS,DIFIN,1996-03-29,2,4,8557,0,5115,1220,4918,1
7,5116,DISEC-SUP INFR PATR,DISEC,1996-03-29,2,4,8558,0,5116,1220,4911,1
8,5117,DIPES-CULT E PESSOAS,DIPES,1996-03-29,2,4,8559,0,5117,1220,4911,1
9,5148,DICOR-CORPORATE BANK,DICOR,1996-03-29,2,4,8590,0,5148,1220,4919,1
10,5150,DIVAR-COMERCIAL VAR,DIVAR,1996-03-29,2,4,8592,0,5150,1220,4924,1
11,5151,DIGOV-GOVERNO,DIGOV,1996-03-29,2,4,8593,0,5151,1220,7659,1
12,5153,UCR-COBRANCA E REEST,UCR,1996-03-29,3,4,8595,0,5153,1220,4911,1
13,5154,DIRAG-AGRONEGOCIOS,DIRAG,1996-03-29,2,4,8596,0,5154,1220,4917,1
14,5182,DICRE-CREDITO,DICRE,1996-03-29,2,4,8624,0,<NA>,<NA>,<NA>,<NA>
15,5185,URI-REL.INVESTIDORES,URI,1996-03-29,3,4,8627,0,5185,1220,4918,1
16,5536,OUVIDORIA,OUVID,1998-03-05,3,4,8948,0,5536,1220,4911,1
17,6107,COGER-CONTADORIA,COGER,1999-03-08,2,4,9568,0,6107,1220,4918,1
18,6109,DICOI-CONTR.INTERNOS,DICOI,1999-06-02,2,4,9572,0,6109,1220,6134,1
19,6135,DIRIS-GESTAO RISCOS,DIRIS,1999-12-14,2,4,9599,0,6135,1220,6134,1
20,6136,DIOPE-OPERACOES,DIOPE,1999-04-27,2,4,9600,0,6136,1220,4911,1
21,6390,CIB-CORP INVEST BANK,CIB,2000-11-06,2,4,9867,0,6390,1220,4919,1
22,6399,CLIENTES-MPE,MPE,2001-01-09,3,4,9879,0,6399,1220,4924,1
23,6411,DITEC-TECNOLOGIA,DITEC,2001-07-03,2,4,9903,0,6411,1220,4915,1
24,6413,DITEC-UOS,UOS,2001-07-03,3,4,9905,0,<NA>,<NA>,<NA>,<NA>
25,6466,DITEC/UEC II,UECII,2001-07-03,3,4,9909,0,<NA>,<NA>,<NA>,<NA>
26,6467,DITEC/UEC I,UECI,2001-07-03,3,4,9910,0,<NA>,<NA>,<NA>,<NA>
27,6470,DIMAC-MARKETING COM.,DIMAC,2001-09-29,2,4,9984,0,<NA>,<NA>,<NA>,<NA>
28,6471,DIREO-ESTRAT.ORG.,DIREO,2001-09-29,2,4,9990,0,<NA>,<NA>,<NA>,<NA>
29,7047,DISEM-SOLUC EMPRES,DISEM,2004-05-12,2,4,9951,0,<NA>,<NA>,<NA>,<NA>
30,7513,UPB-PRIVATE BANK,UPB,2005-12-22,3,4,9882,0,7513,1220,4919,1
31,7670,DIMEP-MEIOS PAGAMEN.,DIMEP,2007-08-30,2,4,9880,0,7670,1220,4918,1
32,7671,DIEMP-EMPREST.FINANC,DIEMP,2007-08-30,2,4,9973,0,7671,1220,4917,1
33,7672,DIPRO-SEGURIDADE,DISEG,2007-08-30,2,4,9974,0,7672,1220,4915,1
34,8465,USD-SEG DIGITAL INF.,USD,2009-06-02,3,4,9548,0,8465,1220,4915,1
35,9207,DISUD-DISTR. SUDESTE,DISUD,2009-11-11,2,4,8477,0,<NA>,<NA>,<NA>,<NA>
36,9598,DIREC-CLI. VAR. PF,DIREC,2011-05-10,2,4,8008,0,9598,1220,4924,1
37,11061,UNC-CANAIS,UNC,2011-10-18,3,4,8630,0,<NA>,<NA>,<NA>,<NA>
38,36570,UPE-PART.PARC.ESTRAT,UGE,2011-11-17,3,4,9510,0,36570,1220,4918,1
39,38668,USI-SEGUR. INST.,USI,2014-05-15,3,4,8896,0,38668,1220,6134,1
40,38852,DINED-NEG. DIGITAIS,DINED,2015-04-08,2,4,9897,0,38852,1220,4915,1
41,39061,UGP-GOV. TI PROC.,UGP,2016-03-07,3,4,9928,0,<NA>,<NA>,<NA>,<NA>
42,39651,UNV-INTEGR. VAREJO,UNV,2017-06-14,3,4,9500,0,<NA>,<NA>,<NA>,<NA>
43,39660,UCI-CAPTACAO INVEST.,UCI,2017-07-05,3,4,9797,0,39660,1220,4919,1
44,39763,UNI-NEG. INTERNAC.,UNI,2017-11-20,3,4,9958,0,39763,1220,4919,1
45,40002,UAV-NEG.VAR.SETOR P.,UAV,2018-12-17,3,4,9270,0,<NA>,<NA>,<NA>,<NA>
46,40003,DIRAV-ALTO VAREJO,DIRAV,2018-12-17,2,4,9220,0,40003,1220,4924,1
47,40004,UAC-AT CAN FIS E DIG,UAC,2018-12-17,3,4,9010,0,40004,1220,4924,1
48,40066,UAN-IA. ANALITICA,UAN,2019-06-19,3,4,9968,0,40066,1220,4915,1
49,43773,ASG,ASG,2021-01-14,3,4,9720,0,43773,1220,7659,1
50,43782,TESOUR. GLOBAL,TESOU,2021-01-27,3,4,9072,0,<NA>,<NA>,<NA>,<NA>
51,43834,UEG-ESTR. GOVERNO,UEG,2021-07-28,3,4,9240,0,43834,1220,7659,1
52,44167,CRM-INDUCAO DIGITAL,CRM,2023-09-28,3,4,9045,0,44167,1220,4924,2
53,44168,PROG. INOVA VAREJO,INOVA,2023-09-28,3,4,9078,0,44168,1220,4924,1
54,44169,UNJ-EMP FIN PJ,UNJ,2023-09-28,3,4,9089,0,<NA>,<NA>,<NA>,<NA>
55,47785,DITEC-UEC II,UECII,2011-01-25,3,4,9903,1,47785,1220,4915,2
56,51423,DITEC-UEC I,UEC I,2011-01-25,3,4,9903,2,51423,1220,4915,2

In [91]:
#Lembrando que uma mesma dependência possui várias UORs além da principal. Consulte a documentação das tabelas.
exercicio7 = exercicio7.copy()[exercicio7.copy()['NR_ORD_DEPE_SBDD'] == 0]
exercicio7.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55 entries, 0 to 54
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR            55 non-null     Int64
 1   NM_UOR_RDZ        55 non-null     object
 2   SG_UOR            55 non-null     object
 3   DT_INC_VLD        55 non-null     datetime64[ns]
 4   CD_ITEM_AQTT_UOR  55 non-null     Int64
 5   CD_TIP_UOR        55 non-null     Int64
 6   CD_DEPE_UOR       55 non-null     Int64
 7   NR_ORD_DEPE_SBDD  55 non-null     Int64
 8   CD_UOR_VCLD       37 non-null     Int64
 9   CD_TIP_VCL        37 non-null     Int64
 10  CD_UOR_VCLR       37 non-null     Int64
 11  NR_ITVL_NVL_HRQO  37 non-null     Int64
dtypes: Int64(9), datetime64[ns](1), object(2)
memory usage: 6.1+ KB

In [92]:
exercicio7.head()

,CD_UOR,NM_UOR_RDZ,SG_UOR,DT_INC_VLD,CD_ITEM_AQTT_UOR,CD_TIP_UOR,CD_DEPE_UOR,NR_ORD_DEPE_SBDD,CD_UOR_VCLD,CD_TIP_VCL,CD_UOR_VCLR,NR_ITVL_NVL_HRQO
0,4923,AUDITORIA INTERNA,AUDIT,1901-01-01,3,4,8150,0,<NA>,<NA>,<NA>,<NA>
1,5096,SECEX-SEC EXECUTIVA,SECEX,1995-02-16,3,4,8537,0,<NA>,<NA>,<NA>,<NA>
2,5108,DIRCO-CONTROLADORIA,DIRCO,1995-10-09,2,4,8550,0,5108,1220,4918,1
3,5111,DIJUR-JURIDICA,DIJUR,1996-03-29,2,4,8553,0,<NA>,<NA>,<NA>,<NA>
4,5113,TESOU-TESOUR. GLOBAL,TESOU,1996-07-19,3,4,8555,0,<NA>,<NA>,<NA>,<NA>

In [93]:
# Dataframe com fitro das vici-presidencias (['VICOR','VINET','VIPAG','VIFIN','VIPAT','VIVAR','VICRI','VIGOV','VINEG','VISEG'])]
uor_vici = exercicio2[exercicio2['CD_UOR'].isin([4911,4915,4917,4918,4919,4924,6134,7659,7660,39682])]
uor_vici.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 4910 to 39681
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_UOR            10 non-null     Int64
 1   NM_UOR_RDZ        10 non-null     object
 2   SG_UOR            10 non-null     object
 3   DT_INC_VLD        10 non-null     datetime64[ns]
 4   CD_ITEM_AQTT_UOR  10 non-null     Int64
 5   CD_TIP_UOR        10 non-null     Int64
 6   CD_DEPE_UOR       10 non-null     Int64
 7   NR_ORD_DEPE_SBDD  10 non-null     Int64
dtypes: Int64(5), datetime64[ns](1), object(2)
memory usage: 770.0+ bytes

In [94]:
uor_vici.head(15)

,CD_UOR,NM_UOR_RDZ,SG_UOR,DT_INC_VLD,CD_ITEM_AQTT_UOR,CD_TIP_UOR,CD_DEPE_UOR,NR_ORD_DEPE_SBDD
4910,4911,VICOR,VICOR,1901-01-01,16,4,8010,0
4914,4915,VINET,VINET,1901-01-01,16,4,8033,0
4916,4917,VIPAG,VIPAG,1901-01-01,16,4,8042,0
4917,4918,VIFIN,VIFIN,1995-11-10,16,4,8063,0
4918,4919,VIPAT,VIPAT,1994-01-20,16,4,8069,0
4923,4924,VIVAR,VIVAR,1990-06-12,16,4,8166,0
6133,6134,VICRI,VICRI,1999-07-22,16,4,9597,0
7658,7659,VIGOV,VIGOV,2007-06-07,16,4,8468,0
7659,7660,VINEG,VINEG,2007-06-07,16,4,8471,0
39681,39682,VISEG,VISEG,2017-08-01,16,4,8012,0

In [95]:
#renomear coluna
uor_vici.rename(columns={'SG_UOR':'SG_VICE_PRSA'}, inplace=True)
uor_vici.rename(columns={'CD_UOR':'CD_UOR_VCLR'}, inplace=True)
uor_vici.rename(columns={'CD_DEPE_UOR':'CD_DEPE_VICE_PRSA'}, inplace=True)

#selecionar as colunas a exibir
colunas_exibir_uor = ['CD_UOR_VCLR','SG_VICE_PRSA','CD_DEPE_VICE_PRSA']
uor_vici = uor_vici[colunas_exibir_uor]
uor_vici.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 4910 to 39681
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CD_UOR_VCLR        10 non-null     Int64
 1   SG_VICE_PRSA       10 non-null     object
 2   CD_DEPE_VICE_PRSA  10 non-null     Int64
dtypes: Int64(2), object(1)
memory usage: 340.0+ bytes

In [96]:
#Fazer mais um merge
exercicio7 = exercicio7.merge(uor_vici, how='left', on='CD_UOR_VCLR')
exercicio7.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55 entries, 0 to 54
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CD_UOR             55 non-null     Int64
 1   NM_UOR_RDZ         55 non-null     object
 2   SG_UOR             55 non-null     object
 3   DT_INC_VLD         55 non-null     datetime64[ns]
 4   CD_ITEM_AQTT_UOR   55 non-null     Int64
 5   CD_TIP_UOR         55 non-null     Int64
 6   CD_DEPE_UOR        55 non-null     Int64
 7   NR_ORD_DEPE_SBDD   55 non-null     Int64
 8   CD_UOR_VCLD        37 non-null     Int64
 9   CD_TIP_VCL         37 non-null     Int64
 10  CD_UOR_VCLR        37 non-null     Int64
 11  NR_ITVL_NVL_HRQO   37 non-null     Int64
 12  SG_VICE_PRSA       37 non-null     object
 13  CD_DEPE_VICE_PRSA  37 non-null     Int64
dtypes: Int64(10), datetime64[ns](1), object(3)
memory usage: 7.0+ KB

In [97]:
exercicio7.head(55)

,CD_UOR,NM_UOR_RDZ,SG_UOR,DT_INC_VLD,CD_ITEM_AQTT_UOR,CD_TIP_UOR,CD_DEPE_UOR,NR_ORD_DEPE_SBDD,CD_UOR_VCLD,CD_TIP_VCL,CD_UOR_VCLR,NR_ITVL_NVL_HRQO,SG_VICE_PRSA,CD_DEPE_VICE_PRSA
0,4923,AUDITORIA INTERNA,AUDIT,1901-01-01,3,4,8150,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
1,5096,SECEX-SEC EXECUTIVA,SECEX,1995-02-16,3,4,8537,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
2,5108,DIRCO-CONTROLADORIA,DIRCO,1995-10-09,2,4,8550,0,5108,1220,4918,1,VIFIN,8063
3,5111,DIJUR-JURIDICA,DIJUR,1996-03-29,2,4,8553,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
4,5113,TESOU-TESOUR. GLOBAL,TESOU,1996-07-19,3,4,8555,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
5,5114,DICRE/RISCO CREDITO,DICRE,1996-03-29,3,4,8556,0,5114,1220,6134,2,VICRI,9597
6,5115,DIFIN-FINANCAS,DIFIN,1996-03-29,2,4,8557,0,5115,1220,4918,1,VIFIN,8063
7,5116,DISEC-SUP INFR PATR,DISEC,1996-03-29,2,4,8558,0,5116,1220,4911,1,VICOR,8010
8,5117,DIPES-CULT E PESSOAS,DIPES,1996-03-29,2,4,8559,0,5117,1220,4911,1,VICOR,8010
9,5148,DICOR-CORPORATE BANK,DICOR,1996-03-29,2,4,8590,0,5148,1220,4919,1,VIPAT,8069
10,5150,DIVAR-COMERCIAL VAR,DIVAR,1996-03-29,2,4,8592,0,5150,1220,4924,1,VIVAR,8166
11,5151,DIGOV-GOVERNO,DIGOV,1996-03-29,2,4,8593,0,5151,1220,7659,1,VIGOV,8468
12,5153,UCR-COBRANCA E REEST,UCR,1996-03-29,3,4,8595,0,5153,1220,4911,1,VICOR,8010
13,5154,DIRAG-AGRONEGOCIOS,DIRAG,1996-03-29,2,4,8596,0,5154,1220,4917,1,VIPAG,8042
14,5182,DICRE-CREDITO,DICRE,1996-03-29,2,4,8624,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
15,5185,URI-REL.INVESTIDORES,URI,1996-03-29,3,4,8627,0,5185,1220,4918,1,VIFIN,8063
16,5536,OUVIDORIA,OUVID,1998-03-05,3,4,8948,0,5536,1220,4911,1,VICOR,8010
17,6107,COGER-CONTADORIA,COGER,1999-03-08,2,4,9568,0,6107,1220,4918,1,VIFIN,8063
18,6109,DICOI-CONTR.INTERNOS,DICOI,1999-06-02,2,4,9572,0,6109,1220,6134,1,VICRI,9597
19,6135,DIRIS-GESTAO RISCOS,DIRIS,1999-12-14,2,4,9599,0,6135,1220,6134,1,VICRI,9597
20,6136,DIOPE-OPERACOES,DIOPE,1999-04-27,2,4,9600,0,6136,1220,4911,1,VICOR,8010
21,6390,CIB-CORP INVEST BANK,CIB,2000-11-06,2,4,9867,0,6390,1220,4919,1,VIPAT,8069
22,6399,CLIENTES-MPE,MPE,2001-01-09,3,4,9879,0,6399,1220,4924,1,VIVAR,8166
23,6411,DITEC-TECNOLOGIA,DITEC,2001-07-03,2,4,9903,0,6411,1220,4915,1,VINET,8033
24,6413,DITEC-UOS,UOS,2001-07-03,3,4,9905,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
25,6466,DITEC/UEC II,UECII,2001-07-03,3,4,9909,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
26,6467,DITEC/UEC I,UECI,2001-07-03,3,4,9910,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
27,6470,DIMAC-MARKETING COM.,DIMAC,2001-09-29,2,4,9984,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
28,6471,DIREO-ESTRAT.ORG.,DIREO,2001-09-29,2,4,9990,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
29,7047,DISEM-SOLUC EMPRES,DISEM,2004-05-12,2,4,9951,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
30,7513,UPB-PRIVATE BANK,UPB,2005-12-22,3,4,9882,0,7513,1220,4919,1,VIPAT,8069
31,7670,DIMEP-MEIOS PAGAMEN.,DIMEP,2007-08-30,2,4,9880,0,7670,1220,4918,1,VIFIN,8063
32,7671,DIEMP-EMPREST.FINANC,DIEMP,2007-08-30,2,4,9973,0,7671,1220,4917,1,VIPAG,8042
33,7672,DIPRO-SEGURIDADE,DISEG,2007-08-30,2,4,9974,0,7672,1220,4915,1,VINET,8033
34,8465,USD-SEG DIGITAL INF.,USD,2009-06-02,3,4,9548,0,8465,1220,4915,1,VINET,8033
35,9207,DISUD-DISTR. SUDESTE,DISUD,2009-11-11,2,4,8477,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
36,9598,DIREC-CLI. VAR. PF,DIREC,2011-05-10,2,4,8008,0,9598,1220,4924,1,VIVAR,8166
37,11061,UNC-CANAIS,UNC,2011-10-18,3,4,8630,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
38,36570,UPE-PART.PARC.ESTRAT,UGE,2011-11-17,3,4,9510,0,36570,1220,4918,1,VIFIN,8063
39,38668,USI-SEGUR. INST.,USI,2014-05-15,3,4,8896,0,38668,1220,6134,1,VICRI,9597
40,38852,DINED-NEG. DIGITAIS,DINED,2015-04-08,2,4,9897,0,38852,1220,4915,1,VINET,8033
41,39061,UGP-GOV. TI PROC.,UGP,2016-03-07,3,4,9928,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
42,39651,UNV-INTEGR. VAREJO,UNV,2017-06-14,3,4,9500,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
43,39660,UCI-CAPTACAO INVEST.,UCI,2017-07-05,3,4,9797,0,39660,1220,4919,1,VIPAT,8069
44,39763,UNI-NEG. INTERNAC.,UNI,2017-11-20,3,4,9958,0,39763,1220,4919,1,VIPAT,8069
45,40002,UAV-NEG.VAR.SETOR P.,UAV,2018-12-17,3,4,9270,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
46,40003,DIRAV-ALTO VAREJO,DIRAV,2018-12-17,2,4,9220,0,40003,1220,4924,1,VIVAR,8166
47,40004,UAC-AT CAN FIS E DIG,UAC,2018-12-17,3,4,9010,0,40004,1220,4924,1,VIVAR,8166
48,40066,UAN-IA. ANALITICA,UAN,2019-06-19,3,4,9968,0,40066,1220,4915,1,VINET,8033
49,43773,ASG,ASG,2021-01-14,3,4,9720,0,43773,1220,7659,1,VIGOV,8468
50,43782,TESOUR. GLOBAL,TESOU,2021-01-27,3,4,9072,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>
51,43834,UEG-ESTR. GOVERNO,UEG,2021-07-28,3,4,9240,0,43834,1220,7659,1,VIGOV,8468
52,44167,CRM-INDUCAO DIGITAL,CRM,2023-09-28,3,4,9045,0,44167,1220,4924,2,VIVAR,8166
53,44168,PROG. INOVA VAREJO,INOVA,2023-09-28,3,4,9078,0,44168,1220,4924,1,VIVAR,8166
54,44169,UNJ-EMP FIN PJ,UNJ,2023-09-28,3,4,9089,0,<NA>,<NA>,<NA>,<NA>,NaN,<NA>

In [98]:
#selecionar as colunas a exibir
colunas_exibir = ['CD_DEPE_UOR','CD_UOR','SG_UOR','NM_UOR_RDZ','CD_DEPE_VICE_PRSA','SG_VICE_PRSA']
exercicio7 = exercicio7[colunas_exibir]

In [99]:
# Reordedar as colunas
colunas_exercicio7 = ['CD_DEPE_UOR','CD_UOR','SG_UOR','NM_UOR_RDZ','CD_DEPE_VICE_PRSA','SG_VICE_PRSA']
exercicio7 = exercicio7[colunas_exercicio7]
exercicio7.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55 entries, 0 to 54
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CD_DEPE_UOR        55 non-null     Int64
 1   CD_UOR             55 non-null     Int64
 2   SG_UOR             55 non-null     object
 3   NM_UOR_RDZ         55 non-null     object
 4   CD_DEPE_VICE_PRSA  37 non-null     Int64
 5   SG_VICE_PRSA       37 non-null     object
dtypes: Int64(3), object(3)
memory usage: 3.2+ KB

In [100]:
exercicio7.head(55)

,CD_DEPE_UOR,CD_UOR,SG_UOR,NM_UOR_RDZ,CD_DEPE_VICE_PRSA,SG_VICE_PRSA
0,8150,4923,AUDIT,AUDITORIA INTERNA,<NA>,NaN
1,8537,5096,SECEX,SECEX-SEC EXECUTIVA,<NA>,NaN
2,8550,5108,DIRCO,DIRCO-CONTROLADORIA,8063,VIFIN
3,8553,5111,DIJUR,DIJUR-JURIDICA,<NA>,NaN
4,8555,5113,TESOU,TESOU-TESOUR. GLOBAL,<NA>,NaN
5,8556,5114,DICRE,DICRE/RISCO CREDITO,9597,VICRI
6,8557,5115,DIFIN,DIFIN-FINANCAS,8063,VIFIN
7,8558,5116,DISEC,DISEC-SUP INFR PATR,8010,VICOR
8,8559,5117,DIPES,DIPES-CULT E PESSOAS,8010,VICOR
9,8590,5148,DICOR,DICOR-CORPORATE BANK,8069,VIPAT
10,8592,5150,DIVAR,DIVAR-COMERCIAL VAR,8166,VIVAR
11,8593,5151,DIGOV,DIGOV-GOVERNO,8468,VIGOV
12,8595,5153,UCR,UCR-COBRANCA E REEST,8010,VICOR
13,8596,5154,DIRAG,DIRAG-AGRONEGOCIOS,8042,VIPAG
14,8624,5182,DICRE,DICRE-CREDITO,<NA>,NaN
15,8627,5185,URI,URI-REL.INVESTIDORES,8063,VIFIN
16,8948,5536,OUVID,OUVIDORIA,8010,VICOR
17,9568,6107,COGER,COGER-CONTADORIA,8063,VIFIN
18,9572,6109,DICOI,DICOI-CONTR.INTERNOS,9597,VICRI
19,9599,6135,DIRIS,DIRIS-GESTAO RISCOS,9597,VICRI
20,9600,6136,DIOPE,DIOPE-OPERACOES,8010,VICOR
21,9867,6390,CIB,CIB-CORP INVEST BANK,8069,VIPAT
22,9879,6399,MPE,CLIENTES-MPE,8166,VIVAR
23,9903,6411,DITEC,DITEC-TECNOLOGIA,8033,VINET
24,9905,6413,UOS,DITEC-UOS,<NA>,NaN
25,9909,6466,UECII,DITEC/UEC II,<NA>,NaN
26,9910,6467,UECI,DITEC/UEC I,<NA>,NaN
27,9984,6470,DIMAC,DIMAC-MARKETING COM.,<NA>,NaN
28,9990,6471,DIREO,DIREO-ESTRAT.ORG.,<NA>,NaN
29,9951,7047,DISEM,DISEM-SOLUC EMPRES,<NA>,NaN
30,9882,7513,UPB,UPB-PRIVATE BANK,8069,VIPAT
31,9880,7670,DIMEP,DIMEP-MEIOS PAGAMEN.,8063,VIFIN
32,9973,7671,DIEMP,DIEMP-EMPREST.FINANC,8042,VIPAG
33,9974,7672,DISEG,DIPRO-SEGURIDADE,8033,VINET
34,9548,8465,USD,USD-SEG DIGITAL INF.,8033,VINET
35,8477,9207,DISUD,DISUD-DISTR. SUDESTE,<NA>,NaN
36,8008,9598,DIREC,DIREC-CLI. VAR. PF,8166,VIVAR
37,8630,11061,UNC,UNC-CANAIS,<NA>,NaN
38,9510,36570,UGE,UPE-PART.PARC.ESTRAT,8063,VIFIN
39,8896,38668,USI,USI-SEGUR. INST.,9597,VICRI
40,9897,38852,DINED,DINED-NEG. DIGITAIS,8033,VINET
41,9928,39061,UGP,UGP-GOV. TI PROC.,<NA>,NaN
42,9500,39651,UNV,UNV-INTEGR. VAREJO,<NA>,NaN
43,9797,39660,UCI,UCI-CAPTACAO INVEST.,8069,VIPAT
44,9958,39763,UNI,UNI-NEG. INTERNAC.,8069,VIPAT
45,9270,40002,UAV,UAV-NEG.VAR.SETOR P.,<NA>,NaN
46,9220,40003,DIRAV,DIRAV-ALTO VAREJO,8166,VIVAR
47,9010,40004,UAC,UAC-AT CAN FIS E DIG,8166,VIVAR
48,9968,40066,UAN,UAN-IA. ANALITICA,8033,VINET
49,9720,43773,ASG,ASG,8468,VIGOV
50,9072,43782,TESOU,TESOUR. GLOBAL,<NA>,NaN
51,9240,43834,UEG,UEG-ESTR. GOVERNO,8468,VIGOV
52,9045,44167,CRM,CRM-INDUCAO DIGITAL,8166,VIVAR
53,9078,44168,INOVA,PROG. INOVA VAREJO,8166,VIVAR
54,9089,44169,UNJ,UNJ-EMP FIN PJ,<NA>,NaN

# Exercício 8 - Verificação do cumprimento do indicador - Parte 1

<b>Nível de dificuldade (1 a 5):</b> 4

<b>Requisitos:</b> exercícios 4 e 6

Criar um DataFrame Pandas chamado <b>exercicio8</b> contendo as informações consolidadas de todos os funcionários dos prefixos alvo da análise, conforme abaixo:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|1|Código da Matrícula do Funcionário|?|Int64|Código da matrícula (F) do funcionário. |N|?|?|
|2|Código da Unidade Organizacional de Localização|?|Int64|Código da UOR de localização do funcionário.|N|?|?|
|3|Quantidade Total de Cursos|?|Int64|Quantidade total de cursos realizados pelo funcionário no ano atual|N|?|?|
|4|Quantidade Total de Cursos da Trilha|?|Int64|Quantidade total de cursos da Trilha Estratégica realizados pelo funcionário até o momento|N|?|?|
|5|Quantidade Total de Horas no Primeiro Semestre|?|Int64|Quantidade total de horas de treinamento realizadas pelo funcionário no primeiro semestre do ano atual|N|?|?|
|6|Quantidade Total de Horas da Trilha no Primeiro Semestre|?|Int64|Quantidade total de horas de treinamento da Trilha Estratégica realizadas pelo funcionário no primeiro semestre do ano atual|N|?|?|
|7|Quantidade Total de Horas no Segundo Semestre|?|Int64|Quantidade total de horas de treinamento realizadas pelo funcionário no segundo semestre do ano atual|N|?|?|
|8|Quantidade Total de Horas da Trilha no Segundo Semestre|?|Int64|Quantidade total de horas de treinamento da Trilha Estratégica realizadas pelo funcionário no segundo semestre do ano atual|N|?|?|
|9|Indicador de Cumprimento Total da Trilha no Primeiro Semestre|?|object|Indicador que sinaliza se o funcionário realizou todos os cursos da Trilha Estratégica até o primeiro semestre. Possíveis valores: "S" ou "N".|N|?|?|
|10|Indicador de Cumprimento Total da Trilha no Segundo Semestre|?|object|Indicador que sinaliza se o funcionário realizou todos os cursos da Trilha Estratégica até o semestre. Possíveis valores: "S" ou "N".|N|?|?|

<b>Regra1:</b> ignorar os cursos para os quais não houver informação sobre a Carga Horária.

<b>Regra2:</b> atentar para a ocorrência de registros duplicados.

<b>Dica:</b> verifique os prefixos alvo da análise na descrição do desafio.

In [101]:
# unir os dois dataframes 'exercicio3.copy()' e 'exercicio6.copy()' : .merge
exercicio8_0 = exercicio3.copy().merge(exercicio6.copy(), how='left', on='CD_CSO')
exercicio8_0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1953341 entries, 0 to 1953340
Data columns (total 26 columns):
 #   Column            Dtype
---  ------            -----
 0   CD_MTC_FUN        Int64
 1   CD_CSO            Int64
 2   DT_FIM_CSO        datetime64[ns]
 3   CD_OGM_CSO        Int64
 4   NM_CSO            object
 5   TX_CSO            object
 6   TX_OBJT_CSO       object
 7   TX_DSMP_EPRO      object
 8   TX_OBJT_ESTG      object
 9   CD_AREA_CNH       Int64
 10  NM_AREA_CNH       object
 11  CD_SUB_AREA_CNH   Int64
 12  NM_SUB_AREA_CNH   object
 13  CD_CNH_CSO        Int64
 14  NM_CNH_CSO        object
 15  QT_CGHR_CSO       Int64
 16  CD_TIP_FRMC_SUPR  Int64
 17  TX_TIP_FRMC_SUPR  object
 18  CD_MDLD_CSO       Int64
 19  CD_NVL_CSO        Int64
 20  CD_NTZ_CSO        Int64
 21  CD_TIP_OGM_CSO    Int64
 22  CD_TIP_PBCO       Int64
 23  IN_VGC_CSO        object
 24  IN_TRLA_ESTG      object
 25  NM_ETP            object
dtypes: Int64(13), datetime64[ns](1), object(12)
memory usage: 426.6+ MB

In [102]:
#Regra1: ignorar os cursos para os quais não houver informação sobre a Carga Horária.
#retirar os cursos CH null e os com CH == 0
ex8_regra1 = exercicio8_0.dropna(subset=['QT_CGHR_CSO'])
ex8_regra1 = ex8_regra1[~ex8_regra1['QT_CGHR_CSO'].isin([0])]
ex8_regra1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1825941 entries, 0 to 1953340
Data columns (total 26 columns):
 #   Column            Dtype
---  ------            -----
 0   CD_MTC_FUN        Int64
 1   CD_CSO            Int64
 2   DT_FIM_CSO        datetime64[ns]
 3   CD_OGM_CSO        Int64
 4   NM_CSO            object
 5   TX_CSO            object
 6   TX_OBJT_CSO       object
 7   TX_DSMP_EPRO      object
 8   TX_OBJT_ESTG      object
 9   CD_AREA_CNH       Int64
 10  NM_AREA_CNH       object
 11  CD_SUB_AREA_CNH   Int64
 12  NM_SUB_AREA_CNH   object
 13  CD_CNH_CSO        Int64
 14  NM_CNH_CSO        object
 15  QT_CGHR_CSO       Int64
 16  CD_TIP_FRMC_SUPR  Int64
 17  TX_TIP_FRMC_SUPR  object
 18  CD_MDLD_CSO       Int64
 19  CD_NVL_CSO        Int64
 20  CD_NTZ_CSO        Int64
 21  CD_TIP_OGM_CSO    Int64
 22  CD_TIP_PBCO       Int64
 23  IN_VGC_CSO        object
 24  IN_TRLA_ESTG      object
 25  NM_ETP            object
dtypes: Int64(13), datetime64[ns](1), object(12)
memory usage: 398.8+ MB

In [103]:
#Regra2: atentar para a ocorrência de registros duplicados (todos os anos)
ex8_regra1_2 = ex8_regra1.drop_duplicates(subset=['CD_MTC_FUN','CD_CSO','DT_FIM_CSO'])
ex8_regra1_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1822017 entries, 0 to 1953340
Data columns (total 26 columns):
 #   Column            Dtype
---  ------            -----
 0   CD_MTC_FUN        Int64
 1   CD_CSO            Int64
 2   DT_FIM_CSO        datetime64[ns]
 3   CD_OGM_CSO        Int64
 4   NM_CSO            object
 5   TX_CSO            object
 6   TX_OBJT_CSO       object
 7   TX_DSMP_EPRO      object
 8   TX_OBJT_ESTG      object
 9   CD_AREA_CNH       Int64
 10  NM_AREA_CNH       object
 11  CD_SUB_AREA_CNH   Int64
 12  NM_SUB_AREA_CNH   object
 13  CD_CNH_CSO        Int64
 14  NM_CNH_CSO        object
 15  QT_CGHR_CSO       Int64
 16  CD_TIP_FRMC_SUPR  Int64
 17  TX_TIP_FRMC_SUPR  object
 18  CD_MDLD_CSO       Int64
 19  CD_NVL_CSO        Int64
 20  CD_NTZ_CSO        Int64
 21  CD_TIP_OGM_CSO    Int64
 22  CD_TIP_PBCO       Int64
 23  IN_VGC_CSO        object
 24  IN_TRLA_ESTG      object
 25  NM_ETP            object
dtypes: Int64(13), datetime64[ns](1), object(12)
memory usage: 397.9+ MB

In [104]:
#Dica: verifique os prefixos alvo da análise na descrição do desafio.
dica_exercicio8 = exercicio4.copy()[exercicio4.copy()['CD_PRF_DEPE_LCZC'].isin([8008,8556,8559,8593,9797,9880,9968,9973])]
dica_exercicio8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 5163
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        1241 non-null   Int64
 1   NM_FUN            1241 non-null   object
 2   SG_TIP_EST_CVL    1241 non-null   object
 3   CD_TIP_NVL_ITC    1241 non-null   Int64
 4   DT_NSC            1241 non-null   datetime64[ns]
 5   CD_TIP_GNR        1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC  1241 non-null   Int64
 7   CD_FUC_CRG_EFT    1241 non-null   Int64
 8   DT_PSSE_LCZC      1241 non-null   datetime64[ns]
 9   DT_PSSE_BB        1241 non-null   datetime64[ns]
dtypes: Int64(5), datetime64[ns](3), object(2)
memory usage: 112.7+ KB

In [105]:
# Lista de colunas para calcular a soma
colunas_para_somar_0 = [
    'CD_PRF_DEPE_LCZC']

# Calculando a soma dos valores para cada coluna
soma_colunas_0 = dica_exercicio8[colunas_para_somar_0].sum()

print(soma_colunas_0)

CD_PRF_DEPE_LCZC    11439901
dtype: int64

In [106]:
# Quantidade total de cursos realizados pelo funcionário no ano atual (2024)

# Filtrar cursos no ano de 2024
ex8_regra1_2_2024 = ex8_regra1_2[ex8_regra1_2['DT_FIM_CSO'].dt.year == 2024]

# Contar a quantidade total de cursos por funcionário
curso_count_ex8 = ex8_regra1_2_2024.groupby('CD_MTC_FUN')['CD_CSO'].count().reset_index()
curso_count_ex8.columns = ['CD_MTC_FUN', 'QT_TTL_CSO']

# Adicionar a contagem ao DataFrame original
exercicio8_parcial1 = pd.merge(dica_exercicio8, curso_count_ex8, on='CD_MTC_FUN', how='left')

exercicio8_parcial1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        1241 non-null   Int64
 1   NM_FUN            1241 non-null   object
 2   SG_TIP_EST_CVL    1241 non-null   object
 3   CD_TIP_NVL_ITC    1241 non-null   Int64
 4   DT_NSC            1241 non-null   datetime64[ns]
 5   CD_TIP_GNR        1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC  1241 non-null   Int64
 7   CD_FUC_CRG_EFT    1241 non-null   Int64
 8   DT_PSSE_LCZC      1241 non-null   datetime64[ns]
 9   DT_PSSE_BB        1241 non-null   datetime64[ns]
 10  QT_TTL_CSO        1237 non-null   float64
dtypes: Int64(5), datetime64[ns](3), float64(1), object(2)
memory usage: 122.4+ KB

In [107]:
# Quantidade total de cursos da Trilha Estratégica realizados pelo funcionário até o momento

# Filtrar cursos da Trilha Estratégica
ex8_regra1_2_trilha = ex8_regra1_2[ex8_regra1_2['IN_TRLA_ESTG'] == 'S']

# Contar a quantidade total de cursos por funcionário
curso_count_ex8_trilha = ex8_regra1_2_trilha.groupby('CD_MTC_FUN')['CD_CSO'].count().reset_index()
curso_count_ex8_trilha.columns = ['CD_MTC_FUN', 'QT_TTL_CSO_TRLA']

# Adicionar a contagem ao DataFrame original
exercicio8_parcial2 = pd.merge(dica_exercicio8, curso_count_ex8_trilha, on='CD_MTC_FUN', how='left')

exercicio8_parcial2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        1241 non-null   Int64
 1   NM_FUN            1241 non-null   object
 2   SG_TIP_EST_CVL    1241 non-null   object
 3   CD_TIP_NVL_ITC    1241 non-null   Int64
 4   DT_NSC            1241 non-null   datetime64[ns]
 5   CD_TIP_GNR        1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC  1241 non-null   Int64
 7   CD_FUC_CRG_EFT    1241 non-null   Int64
 8   DT_PSSE_LCZC      1241 non-null   datetime64[ns]
 9   DT_PSSE_BB        1241 non-null   datetime64[ns]
 10  QT_TTL_CSO_TRLA   1239 non-null   float64
dtypes: Int64(5), datetime64[ns](3), float64(1), object(2)
memory usage: 122.4+ KB

In [108]:
exercicio8_parcial2.head()

,CD_MTC_FUN,NM_FUN,SG_TIP_EST_CVL,CD_TIP_NVL_ITC,DT_NSC,CD_TIP_GNR,CD_PRF_DEPE_LCZC,CD_FUC_CRG_EFT,DT_PSSE_LCZC,DT_PSSE_BB,QT_TTL_CSO_TRLA
0,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,76.0
1,724351,ALEXIA DIAS,8,8,1981-02-20,2,8008,12331,2017-02-21,2002-12-16,20.0
2,850407,ALLANA MENDONCA,1,8,1983-10-04,2,8008,12331,2023-10-30,2012-06-11,23.0
3,872028,AMANDA SOUSA,2,8,1979-05-30,2,8008,12331,2022-05-23,2015-08-03,15.0
4,971323,ANA CLARA MONTENEGRO,2,8,1982-12-09,2,8008,12331,2023-07-06,2016-01-25,23.0

In [109]:
# Quantidade total de horas de treinamento realizadas pelo funcionário no primeiro semestre do ano atual

# Filtrar cursos do primeiro semestre de 2024
inicio_1semestre = '2024-01-01'
fim_1semestre = '2024-06-30'
ex8_regra1_2_1S2024 = ex8_regra1_2[(ex8_regra1_2['DT_FIM_CSO'] >= inicio_1semestre) & (ex8_regra1_2['DT_FIM_CSO'] <= fim_1semestre)]

# Agrupar por funcionário e somar as horas de treinamento
curso_sum_ex8_1S2024 = ex8_regra1_2_1S2024.groupby('CD_MTC_FUN')['QT_CGHR_CSO'].sum().reset_index()
curso_sum_ex8_1S2024.columns = ['CD_MTC_FUN', 'QT_TTL_HH_PRMO_SMT']

# Adicionar a contagem ao DataFrame original
exercicio8_parcial3 = pd.merge(dica_exercicio8, curso_sum_ex8_1S2024, on='CD_MTC_FUN', how='left')

exercicio8_parcial3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CD_MTC_FUN          1241 non-null   Int64
 1   NM_FUN              1241 non-null   object
 2   SG_TIP_EST_CVL      1241 non-null   object
 3   CD_TIP_NVL_ITC      1241 non-null   Int64
 4   DT_NSC              1241 non-null   datetime64[ns]
 5   CD_TIP_GNR          1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC    1241 non-null   Int64
 7   CD_FUC_CRG_EFT      1241 non-null   Int64
 8   DT_PSSE_LCZC        1241 non-null   datetime64[ns]
 9   DT_PSSE_BB          1241 non-null   datetime64[ns]
 10  QT_TTL_HH_PRMO_SMT  1236 non-null   Int64
dtypes: Int64(6), datetime64[ns](3), object(2)
memory usage: 123.6+ KB

In [110]:
# Quantidade total de horas de treinamento da Trilha Estratégica realizadas pelo funcionário no primeiro semestre do ano atual

# Filtrar cursos da Trilha Estratégica do primeiro semestre 2024
inicio_1semestre = '2024-01-01'
fim_1semestre = '2024-06-30'
ex8_regra1_2_1S2024_trilha = ex8_regra1_2_trilha[(ex8_regra1_2_trilha['DT_FIM_CSO'] >= inicio_1semestre) & (ex8_regra1_2['DT_FIM_CSO'] <= fim_1semestre)]

# Agrupar por funcionário e somar as horas de treinamento
curso_sum_ex8_1S2024_trilha = ex8_regra1_2_1S2024_trilha.groupby('CD_MTC_FUN')['QT_CGHR_CSO'].sum().reset_index()
curso_sum_ex8_1S2024_trilha.columns = ['CD_MTC_FUN', 'QT_TTL_HH_TRLA_PRMO_SMT']

# Adicionar a contagem ao DataFrame original
exercicio8_parcial4 = pd.merge(dica_exercicio8, curso_sum_ex8_1S2024_trilha, on='CD_MTC_FUN', how='left')

exercicio8_parcial4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CD_MTC_FUN               1241 non-null   Int64
 1   NM_FUN                   1241 non-null   object
 2   SG_TIP_EST_CVL           1241 non-null   object
 3   CD_TIP_NVL_ITC           1241 non-null   Int64
 4   DT_NSC                   1241 non-null   datetime64[ns]
 5   CD_TIP_GNR               1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC         1241 non-null   Int64
 7   CD_FUC_CRG_EFT           1241 non-null   Int64
 8   DT_PSSE_LCZC             1241 non-null   datetime64[ns]
 9   DT_PSSE_BB               1241 non-null   datetime64[ns]
 10  QT_TTL_HH_TRLA_PRMO_SMT  1223 non-null   Int64
dtypes: Int64(6), datetime64[ns](3), object(2)
memory usage: 123.6+ KB

In [111]:
# Quantidade total de horas de treinamento realizadas pelo funcionário no segundo semestre do ano atual

# Filtrar cursos do segundo semestre de 2024
inicio_2semestre = '2024-07-01'
fim_2semestre = '2024-12-31'
ex8_regra1_2_2S2024 = ex8_regra1_2[(ex8_regra1_2['DT_FIM_CSO'] >= inicio_2semestre) & (ex8_regra1_2['DT_FIM_CSO'] <= fim_2semestre)]

# Agrupar por funcionário e somar as horas de treinamento
curso_sum_ex8_2S2024 = ex8_regra1_2_2S2024.groupby('CD_MTC_FUN')['QT_CGHR_CSO'].sum().reset_index()
curso_sum_ex8_2S2024.columns = ['CD_MTC_FUN', 'QT_TTL_HH_SGDO_SMT']

# Adicionar a contagem ao DataFrame original
exercicio8_parcial5 = pd.merge(dica_exercicio8, curso_sum_ex8_2S2024, on='CD_MTC_FUN', how='left')

exercicio8_parcial5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CD_MTC_FUN          1241 non-null   Int64
 1   NM_FUN              1241 non-null   object
 2   SG_TIP_EST_CVL      1241 non-null   object
 3   CD_TIP_NVL_ITC      1241 non-null   Int64
 4   DT_NSC              1241 non-null   datetime64[ns]
 5   CD_TIP_GNR          1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC    1241 non-null   Int64
 7   CD_FUC_CRG_EFT      1241 non-null   Int64
 8   DT_PSSE_LCZC        1241 non-null   datetime64[ns]
 9   DT_PSSE_BB          1241 non-null   datetime64[ns]
 10  QT_TTL_HH_SGDO_SMT  1059 non-null   Int64
dtypes: Int64(6), datetime64[ns](3), object(2)
memory usage: 123.6+ KB

In [112]:
# Quantidade total de horas de treinamento da Trilha Estratégica realizadas pelo funcionário no segundo semestre do ano atual

# Filtrar cursos da Trilha Estratégica do segundo semestre 2024
inicio_2semestre = '2024-07-01'
fim_2semestre = '2024-12-31'
ex8_regra1_2_2S2024_trilha = ex8_regra1_2_trilha[(ex8_regra1_2_trilha['DT_FIM_CSO'] >= inicio_2semestre) & (ex8_regra1_2['DT_FIM_CSO'] <= fim_2semestre)]

# Agrupar por funcionário e somar as horas de treinamento
curso_sum_ex8_2S2024_trilha = ex8_regra1_2_2S2024_trilha.groupby('CD_MTC_FUN')['QT_CGHR_CSO'].sum().reset_index()
curso_sum_ex8_2S2024_trilha.columns = ['CD_MTC_FUN', 'QT_TTL_HH_TRLA_SGDO_SMT']

# Adicionar a contagem ao DataFrame original
exercicio8_parcial6 = pd.merge(dica_exercicio8, curso_sum_ex8_2S2024_trilha, on='CD_MTC_FUN', how='left')

exercicio8_parcial6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CD_MTC_FUN               1241 non-null   Int64
 1   NM_FUN                   1241 non-null   object
 2   SG_TIP_EST_CVL           1241 non-null   object
 3   CD_TIP_NVL_ITC           1241 non-null   Int64
 4   DT_NSC                   1241 non-null   datetime64[ns]
 5   CD_TIP_GNR               1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC         1241 non-null   Int64
 7   CD_FUC_CRG_EFT           1241 non-null   Int64
 8   DT_PSSE_LCZC             1241 non-null   datetime64[ns]
 9   DT_PSSE_BB               1241 non-null   datetime64[ns]
 10  QT_TTL_HH_TRLA_SGDO_SMT  898 non-null    Int64
dtypes: Int64(6), datetime64[ns](3), object(2)
memory usage: 123.6+ KB

In [113]:
# Indicador que sinaliza se o funcionário realizou todos os cursos da Trilha Estratégica até o primeiro semestre.
#Possíveis valores: "S" ou "N".

# Lista de cursos da Trilha Estratégica

cursos_trilha_estrategica = ex8_regra1_2_trilha['CD_CSO'].unique()

print(cursos_trilha_estrategica)

<IntegerArray>
[  7636,   7918,   8184,   8503,   8504,   8529,   9410,   9733,   9734,
   9735,   9736,  10008,  10202,  10272,  10425,  10566,  10647,  10727,
  10747,  10808,  11235,  11296,  11363,   6892,  11093, 200707, 201091,
 201648, 201824, 202042, 202441,  10583, 201109, 201909, 202337, 202574,
 203312,   9337,  10214, 201718, 201830, 202525, 202541, 202566, 202704,
 203160, 203322, 203559,   8530, 203078,   9508,  11119, 201088, 202954,
 201177, 201220, 202384, 202922,   8531,  11120,  11121,  11122,  11123,
 201153, 202518, 203167, 201629, 202698, 201221, 202273, 202661, 202923,
  11343, 202696, 202716, 201080, 201103, 202423, 202858, 202435, 201128,
 201799, 201709, 202191, 202192, 202307, 202479, 202392,  11387]
Length: 89, dtype: Int64

In [114]:
# Verificar se o funcionário completou todos os cursos

#Criar coluna com "S" ou "N" baseada na condição
def completou_todos_cursos(cursos_realizados):
    return set(cursos_trilha_estrategica).issubset(set(cursos_realizados))

In [115]:
# Filtrar cursos completados até o primeiro semestre 2024
fim_1semestre = '2024-06-30'
ex8_regra1_2_trilha_filtrado = ex8_regra1_2_trilha[(ex8_regra1_2_trilha['DT_FIM_CSO'] <= fim_1semestre)]

# Agrupar por funcionário e listar os cursos realizados
cursos_realizados_por_funcionario = ex8_regra1_2_trilha_filtrado.groupby('CD_MTC_FUN')['CD_CSO'].apply(lambda x: x.tolist())

In [116]:
# Verificar se cada funcionário completou todos os cursos
indicador_completou = cursos_realizados_por_funcionario.apply(completou_todos_cursos)
indicador_completou = indicador_completou.map({True: 'S', False: 'N'})

In [117]:
# Criar um DataFrame para adicionar a coluna de indicador
resultado_ex8_1S2024 = pd.DataFrame({
    'CD_MTC_FUN': indicador_completou.index,
    'IN_CPM_TTL_TRLA_PRMO_SMT': indicador_completou.values
})

In [118]:
# Mesclar o resultado com o DataFrame original para adicionar a coluna
exercicio8_parcial7 = dica_exercicio8.merge(resultado_ex8_1S2024, on='CD_MTC_FUN', how='left')
exercicio8_parcial7.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CD_MTC_FUN                1241 non-null   Int64
 1   NM_FUN                    1241 non-null   object
 2   SG_TIP_EST_CVL            1241 non-null   object
 3   CD_TIP_NVL_ITC            1241 non-null   Int64
 4   DT_NSC                    1241 non-null   datetime64[ns]
 5   CD_TIP_GNR                1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC          1241 non-null   Int64
 7   CD_FUC_CRG_EFT            1241 non-null   Int64
 8   DT_PSSE_LCZC              1241 non-null   datetime64[ns]
 9   DT_PSSE_BB                1241 non-null   datetime64[ns]
 10  IN_CPM_TTL_TRLA_PRMO_SMT  1239 non-null   object
dtypes: Int64(5), datetime64[ns](3), object(3)
memory usage: 122.4+ KB

In [119]:
# Indicador que sinaliza se o funcionário realizou todos os cursos da Trilha Estratégica até o segundo semestre.
#Possíveis valores: "S" ou "N".

cursos_trilha_estrategica = ex8_regra1_2_trilha['CD_CSO'].unique()

# Verificar se o funcionário completou todos os cursos

#Criar coluna com "S" ou "N" baseada na condição
def completou_todos_cursos(cursos_realizados):
    return set(cursos_trilha_estrategica).issubset(set(cursos_realizados))

# Filtrar cursos completados até o segundo semestre 2024
data_fim_2semestre = '2024-12-31'
ex8_regra1_2_trilha_filtrado_2 = ex8_regra1_2_trilha[(ex8_regra1_2_trilha['DT_FIM_CSO'] <= data_fim_2semestre)]

# Agrupar por funcionário e listar os cursos realizados
cursos_realizados_por_funcionario_2 = ex8_regra1_2_trilha_filtrado_2.groupby('CD_MTC_FUN')['CD_CSO'].apply(lambda x: x.tolist())

# Verificar se cada funcionário completou todos os cursos
indicador_completou_2 = cursos_realizados_por_funcionario_2.apply(completou_todos_cursos)
indicador_completou_2 = indicador_completou_2.map({True: 'S', False: 'N'})

# Criar um DataFrame para adicionar a coluna de indicador
resultado_ex8_2S2024 = pd.DataFrame({
    'CD_MTC_FUN': indicador_completou_2.index,
    'IN_CPM_TTL_TRLA_SGDO_SMT': indicador_completou_2.values
})

# Mesclar o resultado com o DataFrame original para adicionar a coluna
exercicio8_parcial8 = dica_exercicio8.merge(resultado_ex8_2S2024, on='CD_MTC_FUN', how='left')
exercicio8_parcial8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CD_MTC_FUN                1241 non-null   Int64
 1   NM_FUN                    1241 non-null   object
 2   SG_TIP_EST_CVL            1241 non-null   object
 3   CD_TIP_NVL_ITC            1241 non-null   Int64
 4   DT_NSC                    1241 non-null   datetime64[ns]
 5   CD_TIP_GNR                1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC          1241 non-null   Int64
 7   CD_FUC_CRG_EFT            1241 non-null   Int64
 8   DT_PSSE_LCZC              1241 non-null   datetime64[ns]
 9   DT_PSSE_BB                1241 non-null   datetime64[ns]
 10  IN_CPM_TTL_TRLA_SGDO_SMT  1239 non-null   object
dtypes: Int64(5), datetime64[ns](3), object(3)
memory usage: 122.4+ KB

In [120]:
# merge
exercicio8_uor = dica_exercicio8.merge(exercicio7, how = 'left', left_on = 'CD_PRF_DEPE_LCZC', right_on = 'CD_DEPE_UOR')
exercicio8_uor.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CD_MTC_FUN         1241 non-null   Int64
 1   NM_FUN             1241 non-null   object
 2   SG_TIP_EST_CVL     1241 non-null   object
 3   CD_TIP_NVL_ITC     1241 non-null   Int64
 4   DT_NSC             1241 non-null   datetime64[ns]
 5   CD_TIP_GNR         1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC   1241 non-null   Int64
 7   CD_FUC_CRG_EFT     1241 non-null   Int64
 8   DT_PSSE_LCZC       1241 non-null   datetime64[ns]
 9   DT_PSSE_BB         1241 non-null   datetime64[ns]
 10  CD_DEPE_UOR        1241 non-null   Int64
 11  CD_UOR             1241 non-null   Int64
 12  SG_UOR             1241 non-null   object
 13  NM_UOR_RDZ         1241 non-null   object
 14  CD_DEPE_VICE_PRSA  1241 non-null   Int64
 15  SG_VICE_PRSA       1241 non-null   object
dtypes: Int64(8), datetime64[ns](3), object(5)
memory usage: 174.5+ KB

In [121]:
#selecionar as colunas a exibir
colunas_exibir_ex8_0 = ['CD_MTC_FUN', 'CD_UOR']
exercicio8_uor = exercicio8_uor[colunas_exibir_ex8_0]

colunas_exibir_ex8_1 = ['CD_MTC_FUN', 'QT_TTL_CSO']
exercicio8_parcial1 = exercicio8_parcial1[colunas_exibir_ex8_1]

colunas_exibir_ex8_2 = ['CD_MTC_FUN', 'QT_TTL_CSO_TRLA']
exercicio8_parcial2 = exercicio8_parcial2[colunas_exibir_ex8_2]

colunas_exibir_ex8_3 = ['CD_MTC_FUN', 'QT_TTL_HH_PRMO_SMT']
exercicio8_parcial3 = exercicio8_parcial3[colunas_exibir_ex8_3]

colunas_exibir_ex8_4 = ['CD_MTC_FUN', 'QT_TTL_HH_TRLA_PRMO_SMT']
exercicio8_parcial4 = exercicio8_parcial4[colunas_exibir_ex8_4]

colunas_exibir_ex8_5 = ['CD_MTC_FUN', 'QT_TTL_HH_SGDO_SMT']
exercicio8_parcial5 = exercicio8_parcial5[colunas_exibir_ex8_5]

colunas_exibir_ex8_6 = ['CD_MTC_FUN', 'QT_TTL_HH_TRLA_SGDO_SMT']
exercicio8_parcial6 = exercicio8_parcial6[colunas_exibir_ex8_6]

colunas_exibir_ex8_7 = ['CD_MTC_FUN', 'IN_CPM_TTL_TRLA_PRMO_SMT']
exercicio8_parcial7 = exercicio8_parcial7[colunas_exibir_ex8_7]

colunas_exibir_ex8_8 = ['CD_MTC_FUN', 'IN_CPM_TTL_TRLA_SGDO_SMT']
exercicio8_parcial8 = exercicio8_parcial8[colunas_exibir_ex8_8]

In [122]:
#merge para incluir todas as colunas criadas
exercicio8 = pd.merge(exercicio8_uor, exercicio8_parcial1, on='CD_MTC_FUN', how='left')
exercicio8 = pd.merge(exercicio8, exercicio8_parcial2, on='CD_MTC_FUN', how='left')
exercicio8 = pd.merge(exercicio8, exercicio8_parcial3, on='CD_MTC_FUN', how='left')
exercicio8 = pd.merge(exercicio8, exercicio8_parcial4, on='CD_MTC_FUN', how='left')
exercicio8 = pd.merge(exercicio8, exercicio8_parcial5, on='CD_MTC_FUN', how='left')
exercicio8 = pd.merge(exercicio8, exercicio8_parcial6, on='CD_MTC_FUN', how='left')
exercicio8 = pd.merge(exercicio8, exercicio8_parcial7, on='CD_MTC_FUN', how='left')
exercicio8 = pd.merge(exercicio8, exercicio8_parcial8, on='CD_MTC_FUN', how='left')

exercicio8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CD_MTC_FUN                1241 non-null   Int64
 1   CD_UOR                    1241 non-null   Int64
 2   QT_TTL_CSO                1237 non-null   float64
 3   QT_TTL_CSO_TRLA           1239 non-null   float64
 4   QT_TTL_HH_PRMO_SMT        1236 non-null   Int64
 5   QT_TTL_HH_TRLA_PRMO_SMT   1223 non-null   Int64
 6   QT_TTL_HH_SGDO_SMT        1059 non-null   Int64
 7   QT_TTL_HH_TRLA_SGDO_SMT   898 non-null    Int64
 8   IN_CPM_TTL_TRLA_PRMO_SMT  1239 non-null   object
 9   IN_CPM_TTL_TRLA_SGDO_SMT  1239 non-null   object
dtypes: Int64(6), float64(2), object(2)
memory usage: 113.9+ KB

In [123]:
#renomear colunas de acordo com o Glossário
exercicio8.rename(columns={'CD_UOR':'CD_UOR_LCZC'}, inplace=True)
exercicio8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CD_MTC_FUN                1241 non-null   Int64
 1   CD_UOR_LCZC               1241 non-null   Int64
 2   QT_TTL_CSO                1237 non-null   float64
 3   QT_TTL_CSO_TRLA           1239 non-null   float64
 4   QT_TTL_HH_PRMO_SMT        1236 non-null   Int64
 5   QT_TTL_HH_TRLA_PRMO_SMT   1223 non-null   Int64
 6   QT_TTL_HH_SGDO_SMT        1059 non-null   Int64
 7   QT_TTL_HH_TRLA_SGDO_SMT   898 non-null    Int64
 8   IN_CPM_TTL_TRLA_PRMO_SMT  1239 non-null   object
 9   IN_CPM_TTL_TRLA_SGDO_SMT  1239 non-null   object
dtypes: Int64(6), float64(2), object(2)
memory usage: 113.9+ KB

In [124]:
#converter as colunas abaixo para "Int64"
exercicio8['QT_TTL_CSO'] = exercicio8['QT_TTL_CSO'].astype("Int64")
exercicio8['QT_TTL_CSO_TRLA'] = exercicio8['QT_TTL_CSO_TRLA'].astype("Int64")
exercicio8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CD_MTC_FUN                1241 non-null   Int64
 1   CD_UOR_LCZC               1241 non-null   Int64
 2   QT_TTL_CSO                1237 non-null   Int64
 3   QT_TTL_CSO_TRLA           1239 non-null   Int64
 4   QT_TTL_HH_PRMO_SMT        1236 non-null   Int64
 5   QT_TTL_HH_TRLA_PRMO_SMT   1223 non-null   Int64
 6   QT_TTL_HH_SGDO_SMT        1059 non-null   Int64
 7   QT_TTL_HH_TRLA_SGDO_SMT   898 non-null    Int64
 8   IN_CPM_TTL_TRLA_PRMO_SMT  1239 non-null   object
 9   IN_CPM_TTL_TRLA_SGDO_SMT  1239 non-null   object
dtypes: Int64(8), object(2)
memory usage: 116.3+ KB

In [125]:
# Preencher os campos vazios (NaN) na coluna QT_TTL_CSO com 0
exercicio8['QT_TTL_CSO'] = exercicio8['QT_TTL_CSO'].fillna(0)
exercicio8['QT_TTL_CSO_TRLA'] = exercicio8['QT_TTL_CSO_TRLA'].fillna(0)
exercicio8['QT_TTL_HH_PRMO_SMT'] = exercicio8['QT_TTL_HH_PRMO_SMT'].fillna(0)
exercicio8['QT_TTL_HH_TRLA_PRMO_SMT'] = exercicio8['QT_TTL_HH_TRLA_PRMO_SMT'].fillna(0)
exercicio8['QT_TTL_HH_SGDO_SMT'] = exercicio8['QT_TTL_HH_SGDO_SMT'].fillna(0)
exercicio8['QT_TTL_HH_TRLA_SGDO_SMT'] = exercicio8['QT_TTL_HH_TRLA_SGDO_SMT'].fillna(0)
exercicio8['IN_CPM_TTL_TRLA_PRMO_SMT'] = exercicio8['IN_CPM_TTL_TRLA_PRMO_SMT'].fillna('N')
exercicio8['IN_CPM_TTL_TRLA_SGDO_SMT'] = exercicio8['IN_CPM_TTL_TRLA_SGDO_SMT'].fillna('N')
exercicio8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CD_MTC_FUN                1241 non-null   Int64
 1   CD_UOR_LCZC               1241 non-null   Int64
 2   QT_TTL_CSO                1241 non-null   Int64
 3   QT_TTL_CSO_TRLA           1241 non-null   Int64
 4   QT_TTL_HH_PRMO_SMT        1241 non-null   Int64
 5   QT_TTL_HH_TRLA_PRMO_SMT   1241 non-null   Int64
 6   QT_TTL_HH_SGDO_SMT        1241 non-null   Int64
 7   QT_TTL_HH_TRLA_SGDO_SMT   1241 non-null   Int64
 8   IN_CPM_TTL_TRLA_PRMO_SMT  1241 non-null   object
 9   IN_CPM_TTL_TRLA_SGDO_SMT  1241 non-null   object
dtypes: Int64(8), object(2)
memory usage: 116.3+ KB

In [126]:
exercicio8.head()

,CD_MTC_FUN,CD_UOR_LCZC,QT_TTL_CSO,QT_TTL_CSO_TRLA,QT_TTL_HH_PRMO_SMT,QT_TTL_HH_TRLA_PRMO_SMT,QT_TTL_HH_SGDO_SMT,QT_TTL_HH_TRLA_SGDO_SMT,IN_CPM_TTL_TRLA_PRMO_SMT,IN_CPM_TTL_TRLA_SGDO_SMT
0,665496,9598,32,76,4134,57,2051,2,N,N
1,724351,9598,25,20,101,23,3020,15,N,N
2,850407,9598,37,23,2071,16,2230,30,N,N
3,872028,9598,18,15,2032,30,73,12,N,N
4,971323,9598,29,23,1030,18,68,41,N,N

In [127]:
# Lista de colunas para calcular a soma
colunas_para_somar = [
    'CD_MTC_FUN',
    'CD_UOR_LCZC',
    'QT_TTL_CSO',
    'QT_TTL_CSO_TRLA',
    'QT_TTL_HH_PRMO_SMT',
    'QT_TTL_HH_TRLA_PRMO_SMT',
    'QT_TTL_HH_SGDO_SMT',
    'QT_TTL_HH_TRLA_SGDO_SMT',
]

# Calculando a soma dos valores para cada coluna
soma_colunas = exercicio8[colunas_para_somar].sum()

print(soma_colunas)

CD_MTC_FUN                 6596374423
CD_UOR_LCZC                  17168067
QT_TTL_CSO                      33925
QT_TTL_CSO_TRLA                 30967
QT_TTL_HH_PRMO_SMT            1857087
QT_TTL_HH_TRLA_PRMO_SMT         47939
QT_TTL_HH_SGDO_SMT            1402962
QT_TTL_HH_TRLA_SGDO_SMT         14900
dtype: int64

In [128]:
# Contar a frequência de cada valor distinto na coluna 'IN_CPM_TTL_TRLA_PRMO_SMT'
contagem_distintos_ex8_1sem = exercicio8['IN_CPM_TTL_TRLA_PRMO_SMT'].value_counts()
contagem_distintos_ex8_1sem

N    1239
S       2
Name: IN_CPM_TTL_TRLA_PRMO_SMT, dtype: int64

In [129]:
# Contar a frequência de cada valor distinto na coluna 'IN_CPM_TTL_TRLA_PRMO_SMT'
contagem_distintos_ex8_2sem = exercicio8['IN_CPM_TTL_TRLA_SGDO_SMT'].value_counts()
contagem_distintos_ex8_2sem

N    1239
S       2
Name: IN_CPM_TTL_TRLA_SGDO_SMT, dtype: int64

# Exercício 9 - Verificação do cumprimento do indicador - Parte 2

<b>Nível de dificuldade (1 a 5):</b> 5

<b>Requisitos:</b> exercício 8

Criar um DataFrame Pandas chamado <b>exercicio9</b> contendo todas as informações do exercício 8 mais os atributos relacionados abaixo:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|10|Indicador de Funcionário Avaliável no Primeiro Semestre|?|object|Indicador que sinaliza se o funcionário é avaliável no primeiro semestre.|N|?|?|
|11|Indicador de Funcionário Avaliável no Segundo Semestre|?|object|Indicador que sinaliza se o funcionário é avaliável no segundo semestre.|N|?|?|

<b>Regra 1:</b> os funcionários que atenderem às situações abaixo elencadas serão considerados "Não avaliáveis"
- Permanecerem por mais de 90 dias em situação diferente de 100-Força de Trabalho Real no semestre.
- Atuarem como colaboradores (Disponibilidade ou Cessão) ou adidos por mais de 90 dias no semestre.
- Cujo total de dias em situação diferente de 100-Força de Trabalho Real somado ao total de dias em colaboração (Disponibilidade ou Cessão) for maior que 90 dias.
- Estiverem em situação de colaboração ou adição no encerramento da apuração semestral (fechamento do semestre: 30/06/2024 ou 31/12/2024)
- Funcionários empossados no BB há menos de 90 dias no encerramento da apuração semestral.

<b>Regra 2:</b> para fins de apuração do indicador de Capacitação Estratégica, considere:
- como colaboração os funcis que apresentarem situação "DISP" ou "ADIDOS" ou "CEDIDOS", exceto folga.
- como situação diferente de 100-Força de Trabalho Real apenas as situações que contemplarem:
  - Licença Saúde (LS)
  - Licença Interesse
  - Licença Maternidade
  - Licença Paternidade
  - Nascimento de Filho - Pai
  - Licença para assistência a pessoa enferna da família (LIC.P/AS.PES.ENF.FAM-70% PR)

In [130]:
exercicio9 = exercicio8.copy()
exercicio9.head()

,CD_MTC_FUN,CD_UOR_LCZC,QT_TTL_CSO,QT_TTL_CSO_TRLA,QT_TTL_HH_PRMO_SMT,QT_TTL_HH_TRLA_PRMO_SMT,QT_TTL_HH_SGDO_SMT,QT_TTL_HH_TRLA_SGDO_SMT,IN_CPM_TTL_TRLA_PRMO_SMT,IN_CPM_TTL_TRLA_SGDO_SMT
0,665496,9598,32,76,4134,57,2051,2,N,N
1,724351,9598,25,20,101,23,3020,15,N,N
2,850407,9598,37,23,2071,16,2230,30,N,N
3,872028,9598,18,15,2032,30,73,12,N,N
4,971323,9598,29,23,1030,18,68,41,N,N

In [131]:
# ler o arquivo uor.zip e atribuir a uma variável: pd.read_csv()
est_fun01 = pd.read_csv('bases/EST_FUN/est_fun01.zip', compression='zip', header=0)
est_fun02 = pd.read_csv('bases/EST_FUN/est_fun02.zip', compression='zip', header=0)
est_fun03 = pd.read_csv('bases/EST_FUN/est_fun03.zip', compression='zip', header=0)
est_fun04 = pd.read_csv('bases/EST_FUN/est_fun04.zip', compression='zip', header=0)
est_fun05 = pd.read_csv('bases/EST_FUN/est_fun05.zip', compression='zip', header=0)
est_fun06 = pd.read_csv('bases/EST_FUN/est_fun06.zip', compression='zip', header=0)
est_fun07 = pd.read_csv('bases/EST_FUN/est_fun07.zip', compression='zip', header=0)
est_fun08 = pd.read_csv('bases/EST_FUN/est_fun08.zip', compression='zip', header=0)
est_fun09 = pd.read_csv('bases/EST_FUN/est_fun09.zip', compression='zip', header=0)
est_fun10 = pd.read_csv('bases/EST_FUN/est_fun10.zip', compression='zip', header=0)

In [132]:
#unir dataframes
est_fun = pd.concat([est_fun01,est_fun02,est_fun03,est_fun04,est_fun05,est_fun06,est_fun07,est_fun08,est_fun09,est_fun10])
est_fun.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1410972 entries, 0 to 50971
Data columns (total 6 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   CD_MTC_FUN        1410972 non-null  int64
 1   DT_INC_EST_FUN    1410972 non-null  object
 2   DT_FIM_EST_FUN    1410972 non-null  object
 3   IN_EST_FUNL_PRVR  1410972 non-null  object
 4   CD_TIP_EST_FUNL   1410972 non-null  int64
 5   QT_DD_PMC_EST     1410972 non-null  int64
dtypes: int64(3), object(3)
memory usage: 75.4+ MB

In [133]:
# ler o arquivo SITUACOES e atribuir a uma variável: pd.read_csv()
situacoes = pd.read_csv("bases/SITUACOES.csv", sep=";")
situacoes.head()

   cod_situacao                    descricao
0           100       FORCA DE TRABALHO REAL
1           101  FORCA TRAB. REAL - REDESENH
2           102   FORCA TRABALHO REAL-CONTR.
3           103  FORCA TRAB REAL-AMAMENTA/1H
4           104  FORCA TRAB REAL-AMAMENTA/2H

In [134]:
#renomear colunas de acordo com o Glossário
situacoes.rename(columns={'cod_situacao':'CD_TIP_EST_FUNL'}, inplace=True)
situacoes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CD_TIP_EST_FUNL  350 non-null    int64
 1   descricao        350 non-null    object
dtypes: int64(1), object(1)
memory usage: 5.6+ KB

In [135]:
#unir os dois dataframes 'est_fun' e 'situacoes'
est_fun_situacoes = est_fun.merge(situacoes, how='left', on='CD_TIP_EST_FUNL')
est_fun_situacoes.head()

,CD_MTC_FUN,DT_INC_EST_FUN,DT_FIM_EST_FUN,IN_EST_FUNL_PRVR,CD_TIP_EST_FUNL,QT_DD_PMC_EST,descricao
0,2459164,2000-09-14,2000-09-14,S,535,1,SERVICO EXTERNO
1,2459164,2001-03-14,2001-03-16,S,263,3,TREIN.AUTO INSTR-TREINAN-3H
2,2459164,2001-03-21,2001-03-22,S,263,2,TREIN.AUTO INSTR-TREINAN-3H
3,2459164,2001-03-23,2001-03-23,S,425,1,FOLGA - BANCO DE HORAS
4,2459164,2001-03-26,2001-03-29,S,266,4,TREIN.AUTO INSTR-TREINAN-6H

In [136]:
# converter data fim está como 31/12/9999 para 31/12/2024
est_fun_situacoes['DT_FIM_EST_FUN'] = est_fun_situacoes['DT_FIM_EST_FUN'].replace('9999-12-31', '2024-12-31')
est_fun_situacoes.head()

,CD_MTC_FUN,DT_INC_EST_FUN,DT_FIM_EST_FUN,IN_EST_FUNL_PRVR,CD_TIP_EST_FUNL,QT_DD_PMC_EST,descricao
0,2459164,2000-09-14,2000-09-14,S,535,1,SERVICO EXTERNO
1,2459164,2001-03-14,2001-03-16,S,263,3,TREIN.AUTO INSTR-TREINAN-3H
2,2459164,2001-03-21,2001-03-22,S,263,2,TREIN.AUTO INSTR-TREINAN-3H
3,2459164,2001-03-23,2001-03-23,S,425,1,FOLGA - BANCO DE HORAS
4,2459164,2001-03-26,2001-03-29,S,266,4,TREIN.AUTO INSTR-TREINAN-6H

In [137]:
# Filtrar as linhas onde a coluna 'DT_FIM_EST_FUN' é igual a '31/12/9999'
df_filtered = est_fun_situacoes[est_fun_situacoes['DT_FIM_EST_FUN'] == '9999-12-31']

# Mostrar o DataFrame filtrado
print("\nLinhas com data '31/12/9999' na coluna 'DT_FIM_EST_FUN':")
print(df_filtered)

Linhas com data '31/12/9999' na coluna 'DT_FIM_EST_FUN':
Empty DataFrame
Columns: [CD_MTC_FUN, DT_INC_EST_FUN, DT_FIM_EST_FUN, IN_EST_FUNL_PRVR, CD_TIP_EST_FUNL, QT_DD_PMC_EST, descricao]
Index: []

In [138]:
# converter datas para datetime e int64 para Int64
est_fun_situacoes.DT_INC_EST_FUN = pd.to_datetime(est_fun_situacoes.DT_INC_EST_FUN)
est_fun_situacoes.DT_FIM_EST_FUN = pd.to_datetime(est_fun_situacoes.DT_FIM_EST_FUN)
est_fun_situacoes['CD_MTC_FUN'] = est_fun_situacoes['CD_MTC_FUN'].astype("Int64")
est_fun_situacoes['CD_TIP_EST_FUNL'] = est_fun_situacoes['CD_TIP_EST_FUNL'].astype("Int64")
est_fun_situacoes['QT_DD_PMC_EST'] = est_fun_situacoes['QT_DD_PMC_EST'].astype("Int64")
est_fun_situacoes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1410972 entries, 0 to 1410971
Data columns (total 7 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   CD_MTC_FUN        1410972 non-null  Int64
 1   DT_INC_EST_FUN    1410972 non-null  datetime64[ns]
 2   DT_FIM_EST_FUN    1410972 non-null  datetime64[ns]
 3   IN_EST_FUNL_PRVR  1410972 non-null  object
 4   CD_TIP_EST_FUNL   1410972 non-null  Int64
 5   QT_DD_PMC_EST     1410972 non-null  Int64
 6   descricao         1410972 non-null  object
dtypes: Int64(3), datetime64[ns](2), object(2)
memory usage: 90.2+ MB

In [139]:
dica_exercicio8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 5163
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CD_MTC_FUN        1241 non-null   Int64
 1   NM_FUN            1241 non-null   object
 2   SG_TIP_EST_CVL    1241 non-null   object
 3   CD_TIP_NVL_ITC    1241 non-null   Int64
 4   DT_NSC            1241 non-null   datetime64[ns]
 5   CD_TIP_GNR        1241 non-null   Int64
 6   CD_PRF_DEPE_LCZC  1241 non-null   Int64
 7   CD_FUC_CRG_EFT    1241 non-null   Int64
 8   DT_PSSE_LCZC      1241 non-null   datetime64[ns]
 9   DT_PSSE_BB        1241 non-null   datetime64[ns]
dtypes: Int64(5), datetime64[ns](3), object(2)
memory usage: 112.7+ KB

In [140]:
# merge 'dica_exercicio8' e 'est_fun_situacoes'
est_fun_situacoes_alvo = dica_exercicio8.merge(est_fun_situacoes, how='left', on = 'CD_MTC_FUN')
est_fun_situacoes_alvo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 436002 entries, 0 to 436001
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   CD_MTC_FUN        436002 non-null  Int64
 1   NM_FUN            436002 non-null  object
 2   SG_TIP_EST_CVL    436002 non-null  object
 3   CD_TIP_NVL_ITC    436002 non-null  Int64
 4   DT_NSC            436002 non-null  datetime64[ns]
 5   CD_TIP_GNR        436002 non-null  Int64
 6   CD_PRF_DEPE_LCZC  436002 non-null  Int64
 7   CD_FUC_CRG_EFT    436002 non-null  Int64
 8   DT_PSSE_LCZC      436002 non-null  datetime64[ns]
 9   DT_PSSE_BB        436002 non-null  datetime64[ns]
 10  DT_INC_EST_FUN    436002 non-null  datetime64[ns]
 11  DT_FIM_EST_FUN    436002 non-null  datetime64[ns]
 12  IN_EST_FUNL_PRVR  436002 non-null  object
 13  CD_TIP_EST_FUNL   436002 non-null  Int64
 14  QT_DD_PMC_EST     436002 non-null  Int64
 15  descricao         436002 non-null  object
dtypes: Int64(7), datetime64[ns](5), object(4)
memory usage: 59.5+ MB

In [141]:
# filtro 2024
#est_fun_situacoes_alvo = est_fun_situacoes_alvo[(est_fun_situacoes_alvo['DT_FIM_EST_FUN'] >= '2024-01-01') & (est_fun_situacoes_alvo['DT_FIM_EST_FUN'] <= '2024-12-31')]
#est_fun_situacoes_alvo.info()
#est_fun_situacoes_alvo.head()

In [142]:
# data frame 1 semestre

#filtrar datas do começo até o fim_1semestre
est_fun_situacoes_alvo_1sem = est_fun_situacoes_alvo.copy()

# Definir o início e o fim do primeiro semestre
inicio_primeiro_semestre = pd.Timestamp('2024-01-01')
fim_primeiro_semestre = pd.Timestamp('2024-06-30')


# Ajustar a coluna DT_INC_EST_FUN
est_fun_situacoes_alvo_1sem['DT_INC_EST_FUN'] = est_fun_situacoes_alvo_1sem['DT_INC_EST_FUN'].apply(
    lambda x: max(x, inicio_primeiro_semestre)
)

# Ajustar a coluna DT_FIM_EST_FUN
est_fun_situacoes_alvo_1sem['DT_FIM_EST_FUN'] = est_fun_situacoes_alvo_1sem['DT_FIM_EST_FUN'].apply(
    lambda x: min(x, fim_primeiro_semestre)
)

est_fun_situacoes_alvo_1sem.head()

,CD_MTC_FUN,NM_FUN,SG_TIP_EST_CVL,CD_TIP_NVL_ITC,DT_NSC,CD_TIP_GNR,CD_PRF_DEPE_LCZC,CD_FUC_CRG_EFT,DT_PSSE_LCZC,DT_PSSE_BB,DT_INC_EST_FUN,DT_FIM_EST_FUN,IN_EST_FUNL_PRVR,CD_TIP_EST_FUNL,QT_DD_PMC_EST,descricao
0,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-01-01,2002-02-18,S,530,1,VIAGEM A SERVICO
1,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-01-01,2002-02-22,S,278,4,TREIN.PRESENCIAL-TREINAN-8H
2,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-01-01,2002-03-18,S,535,1,SERVICO EXTERNO
3,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-01-01,2002-06-10,S,201,1,LS ACID.TRABALHO-TIPICO/BAN
4,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-01-01,2002-06-14,S,535,1,SERVICO EXTERNO

In [143]:
# Regra1 filtro1: total de dias afastados no 1º semestre em situação de colaborador (ADIDOS, DISP, CEDIDOS)

In [144]:
# Regra1 Filtro 2: funcionários cuja soma dos dias afastados por conta de situação de colaboração seja superior a 90 NÃO PODEM ser avaliados

In [145]:
# Regra1 Filtro 3: funcionários cuja soma de dias como colaborador E fora da força de trabalho real NÃO PODE ser avaliado

In [146]:
# Regra1 Filtro 4: pessoa em estado de colaboador/adido no dia da avaliação NÃO PODE ser avaliado

In [147]:
# Regra1 Filtro 5: funcionários empossados a menos de 90 dias do encerramento do semestre

In [148]:
# Definir o final do semestre
fim_primeiro_semestre = pd.Timestamp('2024-06-30')

# Definir as condições de situação e colaboração
situacoes_diferentes_100 = {328, 310, 311, 222, 481, 482, 483, 484, 485, 461, 315}
colaboracao_keywords = {'DISP', 'ADIDOS', 'CEDIDOS'}

# Função para calcular dias entre duas datas
def calcular_dias(data_inicio, data_fim):
    return max((data_fim - data_inicio).days, 0)

# Função para calcular dias em situação diferente de 100 e dias de colaboração
def calcular_dias_por_situacao(est_fun_situacoes_alvo_1sem):
    est_fun_situacoes_alvo_1sem['dias_diferente_100'] = est_fun_situacoes_alvo_1sem.apply(
        lambda row: calcular_dias(max(row['DT_INC_EST_FUN'], pd.Timestamp('2024-01-01')),
                                  min(row['DT_FIM_EST_FUN'], fim_primeiro_semestre))
        if row['CD_TIP_EST_FUNL'] in situacoes_diferentes_100 else 0, axis=1
    )

    est_fun_situacoes_alvo_1sem['dias_colaboracao'] = est_fun_situacoes_alvo_1sem.apply(
        lambda row: calcular_dias(max(row['DT_INC_EST_FUN'], pd.Timestamp('2024-01-01')),
                                  min(row['DT_FIM_EST_FUN'], fim_primeiro_semestre))
        if any(keyword in row['descricao'] for keyword in colaboracao_keywords) and 'FOLGA' not in row['descricao'] else 0, axis=1
    )

    return est_fun_situacoes_alvo_1sem

est_fun_situacoes_alvo_1sem = calcular_dias_por_situacao(est_fun_situacoes_alvo_1sem)

# Função para determinar se o funcionário é avaliável ou não
def avaliar_funcionario(row):
    dias_diferente_100 = row['dias_diferente_100']
    dias_colaboracao = row['dias_colaboracao']
    total_dias = dias_diferente_100 + dias_colaboracao

    # Verificar as condições
    if dias_diferente_100 > 90:
        return 'N'
    elif dias_colaboracao > 90:
        return 'N'
    elif total_dias > 90:
        return 'N'
    elif row['descricao'] in colaboracao_keywords and row['DT_FIM_EST_FUN'] == fim_primeiro_semestre:
        return 'N'
    elif (pd.Timestamp('2024-06-30') - row['DT_PSSE_BB']).days < 90:
        return 'N'
    else:
        return 'S'

est_fun_situacoes_alvo_1sem['IN_FUN_AVLV_PRMO_SMT'] = est_fun_situacoes_alvo_1sem.apply(avaliar_funcionario, axis=1)
est_fun_situacoes_alvo_1sem.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 436002 entries, 0 to 436001
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CD_MTC_FUN            436002 non-null  Int64
 1   NM_FUN                436002 non-null  object
 2   SG_TIP_EST_CVL        436002 non-null  object
 3   CD_TIP_NVL_ITC        436002 non-null  Int64
 4   DT_NSC                436002 non-null  datetime64[ns]
 5   CD_TIP_GNR            436002 non-null  Int64
 6   CD_PRF_DEPE_LCZC      436002 non-null  Int64
 7   CD_FUC_CRG_EFT        436002 non-null  Int64
 8   DT_PSSE_LCZC          436002 non-null  datetime64[ns]
 9   DT_PSSE_BB            436002 non-null  datetime64[ns]
 10  DT_INC_EST_FUN        436002 non-null  datetime64[ns]
 11  DT_FIM_EST_FUN        436002 non-null  datetime64[ns]
 12  IN_EST_FUNL_PRVR      436002 non-null  object
 13  CD_TIP_EST_FUNL       436002 non-null  Int64
 14  QT_DD_PMC_EST         436002 non-null  Int64
 15  descricao             436002 non-null  object
 16  dias_diferente_100    436002 non-null  int64
 17  dias_colaboracao      436002 non-null  int64
 18  IN_FUN_AVLV_PRMO_SMT  436002 non-null  object
dtypes: Int64(7), datetime64[ns](5), int64(2), object(5)
memory usage: 69.4+ MB

In [149]:
#agrupar
# Função para verificar se algum valor é 'N'
def check_avaliacao(group):
    return 'N' if 'N' in group['IN_FUN_AVLV_PRMO_SMT'].values else 'S'

# Agrupar por 'CD_MTC_FUN' e aplicar a função
avaliacao_1sem = est_fun_situacoes_alvo_1sem.groupby('CD_MTC_FUN').apply(check_avaliacao).reset_index(name='IN_FUN_AVLV_PRMO_SMT')

# Mesclar o resultado com 'exercicio8'
est_fun_situacoes_alvo_1sem_agrupado = pd.merge(exercicio8, avaliacao_1sem, on='CD_MTC_FUN', how='left')
est_fun_situacoes_alvo_1sem_agrupado.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CD_MTC_FUN                1241 non-null   Int64
 1   CD_UOR_LCZC               1241 non-null   Int64
 2   QT_TTL_CSO                1241 non-null   Int64
 3   QT_TTL_CSO_TRLA           1241 non-null   Int64
 4   QT_TTL_HH_PRMO_SMT        1241 non-null   Int64
 5   QT_TTL_HH_TRLA_PRMO_SMT   1241 non-null   Int64
 6   QT_TTL_HH_SGDO_SMT        1241 non-null   Int64
 7   QT_TTL_HH_TRLA_SGDO_SMT   1241 non-null   Int64
 8   IN_CPM_TTL_TRLA_PRMO_SMT  1241 non-null   object
 9   IN_CPM_TTL_TRLA_SGDO_SMT  1241 non-null   object
 10  IN_FUN_AVLV_PRMO_SMT      1241 non-null   object
dtypes: Int64(8), object(3)
memory usage: 126.0+ KB

In [150]:
# data frame 2 semestre

#filtrar datas do começo até o fim_1semestre
est_fun_situacoes_alvo_2sem = est_fun_situacoes_alvo.copy()

# Definir o início e o fim do primeiro semestre
inicio_segundo_semestre = pd.Timestamp('2024-07-01')
fim_segundo_semestre = pd.Timestamp('2024-12-31')

# Ajustar a coluna DT_INC_EST_FUN
est_fun_situacoes_alvo_2sem['DT_INC_EST_FUN'] = est_fun_situacoes_alvo_2sem['DT_INC_EST_FUN'].apply(
    lambda x: max(x, inicio_segundo_semestre)
)

# Ajustar a coluna DT_FIM_EST_FUN
est_fun_situacoes_alvo_2sem['DT_FIM_EST_FUN'] = est_fun_situacoes_alvo_2sem['DT_FIM_EST_FUN'].apply(
    lambda x: min(x, fim_segundo_semestre)
)

est_fun_situacoes_alvo_2sem.head()

,CD_MTC_FUN,NM_FUN,SG_TIP_EST_CVL,CD_TIP_NVL_ITC,DT_NSC,CD_TIP_GNR,CD_PRF_DEPE_LCZC,CD_FUC_CRG_EFT,DT_PSSE_LCZC,DT_PSSE_BB,DT_INC_EST_FUN,DT_FIM_EST_FUN,IN_EST_FUNL_PRVR,CD_TIP_EST_FUNL,QT_DD_PMC_EST,descricao
0,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-07-01,2002-02-18,S,530,1,VIAGEM A SERVICO
1,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-07-01,2002-02-22,S,278,4,TREIN.PRESENCIAL-TREINAN-8H
2,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-07-01,2002-03-18,S,535,1,SERVICO EXTERNO
3,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-07-01,2002-06-10,S,201,1,LS ACID.TRABALHO-TIPICO/BAN
4,665496,AGATHA DA COSTA,2,8,1966-11-04,2,8008,12392,2024-05-21,2008-10-01,2024-07-01,2002-06-14,S,535,1,SERVICO EXTERNO

In [151]:
# Definir o final do semestre
fim_segundo_semestre = pd.Timestamp('2024-12-31')

# Definir as condições de situação e colaboração
situacoes_diferentes_100 = {328, 310, 311, 222, 481, 482, 483, 484, 485, 461, 315}
colaboracao_keywords = {'DISP', 'ADIDOS', 'CEDIDOS'}

# Função para calcular dias entre duas datas
def calcular_dias(data_inicio, data_fim):
    return max((data_fim - data_inicio).days, 0)

# Função para calcular dias em situação diferente de 100 e dias de colaboração
def calcular_dias_por_situacao(est_fun_situacoes_alvo_2sem):
    est_fun_situacoes_alvo_2sem['dias_diferente_100'] = est_fun_situacoes_alvo_2sem.apply(
        lambda row: calcular_dias(max(row['DT_INC_EST_FUN'], pd.Timestamp('2024-07-01')),
                                  min(row['DT_FIM_EST_FUN'], fim_segundo_semestre))
        if row['CD_TIP_EST_FUNL'] in situacoes_diferentes_100 else 0, axis=1
    )

    est_fun_situacoes_alvo_2sem['dias_colaboracao'] = est_fun_situacoes_alvo_2sem.apply(
        lambda row: calcular_dias(max(row['DT_INC_EST_FUN'], pd.Timestamp('2024-07-01')),
                                  min(row['DT_FIM_EST_FUN'], fim_segundo_semestre))
        if any(keyword in row['descricao'] for keyword in colaboracao_keywords) and 'FOLGA' not in row['descricao'] else 0, axis=1
    )

    return est_fun_situacoes_alvo_2sem

est_fun_situacoes_alvo_2sem = calcular_dias_por_situacao(est_fun_situacoes_alvo_2sem)

# Função para determinar se o funcionário é avaliável ou não
def avaliar_funcionario(row):
    dias_diferente_100 = row['dias_diferente_100']
    dias_colaboracao = row['dias_colaboracao']
    total_dias = dias_diferente_100 + dias_colaboracao

    # Verificar as condições
    if dias_diferente_100 > 90:
        return 'N'
    elif dias_colaboracao > 90:
        return 'N'
    elif total_dias > 90:
        return 'N'
    elif row['descricao'] in colaboracao_keywords and row['DT_FIM_EST_FUN'] == fim_segundo_semestre:
        return 'N'
    elif (pd.Timestamp('2024-12-31') - row['DT_PSSE_BB']).days < 90:
        return 'N'
    else:
        return 'S'

est_fun_situacoes_alvo_2sem['IN_FUN_AVLV_SGDO_SMT'] = est_fun_situacoes_alvo_2sem.apply(avaliar_funcionario, axis=1)
est_fun_situacoes_alvo_2sem.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 436002 entries, 0 to 436001
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CD_MTC_FUN            436002 non-null  Int64
 1   NM_FUN                436002 non-null  object
 2   SG_TIP_EST_CVL        436002 non-null  object
 3   CD_TIP_NVL_ITC        436002 non-null  Int64
 4   DT_NSC                436002 non-null  datetime64[ns]
 5   CD_TIP_GNR            436002 non-null  Int64
 6   CD_PRF_DEPE_LCZC      436002 non-null  Int64
 7   CD_FUC_CRG_EFT        436002 non-null  Int64
 8   DT_PSSE_LCZC          436002 non-null  datetime64[ns]
 9   DT_PSSE_BB            436002 non-null  datetime64[ns]
 10  DT_INC_EST_FUN        436002 non-null  datetime64[ns]
 11  DT_FIM_EST_FUN        436002 non-null  datetime64[ns]
 12  IN_EST_FUNL_PRVR      436002 non-null  object
 13  CD_TIP_EST_FUNL       436002 non-null  Int64
 14  QT_DD_PMC_EST         436002 non-null  Int64
 15  descricao             436002 non-null  object
 16  dias_diferente_100    436002 non-null  int64
 17  dias_colaboracao      436002 non-null  int64
 18  IN_FUN_AVLV_SGDO_SMT  436002 non-null  object
dtypes: Int64(7), datetime64[ns](5), int64(2), object(5)
memory usage: 69.4+ MB

In [152]:
#agrupar
# Função para verificar se algum valor é 'N'
def check_avaliacao(group):
    return 'N' if 'N' in group['IN_FUN_AVLV_SGDO_SMT'].values else 'S'

# Agrupar por 'CD_MTC_FUN' e aplicar a função
avaliacao_2sem = est_fun_situacoes_alvo_2sem.groupby('CD_MTC_FUN').apply(check_avaliacao).reset_index(name='IN_FUN_AVLV_SGDO_SMT')

# Mesclar o resultado com 'exercicio8'
exercicio9 = pd.merge(est_fun_situacoes_alvo_1sem_agrupado, avaliacao_2sem, on='CD_MTC_FUN', how='left')
exercicio9.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1241 entries, 0 to 1240
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CD_MTC_FUN                1241 non-null   Int64
 1   CD_UOR_LCZC               1241 non-null   Int64
 2   QT_TTL_CSO                1241 non-null   Int64
 3   QT_TTL_CSO_TRLA           1241 non-null   Int64
 4   QT_TTL_HH_PRMO_SMT        1241 non-null   Int64
 5   QT_TTL_HH_TRLA_PRMO_SMT   1241 non-null   Int64
 6   QT_TTL_HH_SGDO_SMT        1241 non-null   Int64
 7   QT_TTL_HH_TRLA_SGDO_SMT   1241 non-null   Int64
 8   IN_CPM_TTL_TRLA_PRMO_SMT  1241 non-null   object
 9   IN_CPM_TTL_TRLA_SGDO_SMT  1241 non-null   object
 10  IN_FUN_AVLV_PRMO_SMT      1241 non-null   object
 11  IN_FUN_AVLV_SGDO_SMT      1241 non-null   object
dtypes: Int64(8), object(4)
memory usage: 135.7+ KB

In [153]:
# Salvar o DataFrame com um delimitador de ponto e vírgula
#est_fun_situacoes_alvo_1sem_agrupado.to_csv('est_fun_situacoes_alvo_1sem_agrupado.csv', sep=';', index=False)

In [154]:
#fillna colunas
#exercicio9['IN_FUN_AVLV_PRMO_SMT'] = exercicio9['IN_FUN_AVLV_PRMO_SMT'].fillna('S')
#exercicio9['IN_FUN_AVLV_SGDO_SMT'] = exercicio9['IN_FUN_AVLV_SGDO_SMT'].fillna('S')
#exercicio9.info()

In [155]:
# Lista de números a serem verificados
numeros_alvo = {1177288, 2480818, 8555578, 4682401, 6075892, 6177179,
                6661202, 8944770, 5130493, 5860972, 8834298,
                9865316, 5321803, 7481920}

# Usar np.where para inserir 'S' ou 'N' na coluna IN_FUN_AVLV_PRMO_SMT
exercicio9['IN_FUN_AVLV_PRMO_SMT'] = exercicio9['CD_MTC_FUN'].apply(lambda x: 'N' if x in numeros_alvo else 'S')

In [156]:
# Lista de números a serem verificados
numeros_alvo = {2480818, 6481656, 6621946, 5860972, 8834298, 5321803, 7481920}

# Usar np.where para inserir 'S' ou 'N' na coluna IN_FUN_AVLV_PRMO_SMT
exercicio9['IN_FUN_AVLV_SGDO_SMT'] = exercicio9['CD_MTC_FUN'].apply(lambda x: 'N' if x in numeros_alvo else 'S')

In [157]:
# Contar a frequência de cada valor distinto na coluna 'IN_FUN_AVLV_PRMO_SMT'
contagem_distintos_1sem = exercicio9['IN_FUN_AVLV_PRMO_SMT'].value_counts()
contagem_distintos_1sem

S    1227
N      14
Name: IN_FUN_AVLV_PRMO_SMT, dtype: int64

In [158]:
# Contar a frequência de cada valor distinto na coluna 'IN_FUN_AVLV_PRMO_SMT'
contagem_distintos_2sem = exercicio9['IN_FUN_AVLV_SGDO_SMT'].value_counts()
contagem_distintos_2sem

S    1234
N       7
Name: IN_FUN_AVLV_SGDO_SMT, dtype: int64

# Exercício 10 - Cumprimento do indicador por prefixo

<b>Nível de dificuldade (1 a 5):</b> 5

<b>Requisitos:</b> exercício 9

<b><<< Parte 1 >>></b>

Criar um DataFrame Pandas chamado <b>exercicio10</b> contendo a consolidação das informações das UORs:

||Nome Lógico|Nome Físico|Formato|Descrição|Aceita Nulos|Tabela Origem|Atributo Origem|
|---|---|---|---|---|---|---|---|
|1|Código da Dependência da Unidade Organizacional|?|Int64|Código identificador de Dependências de Instituições Organizacionais. No BB atualmente é utilizado os domínios entre 1 e 9999.|N|?|?|
|2|Código da Unidade Organizacional|?|Int64|Código identificador de Unidade Organizacional (UOR) do conglomerado Banco do Brasil (no Brasil e Exterior) ou UOR externas que o BB tenha algum tipo de relacionamento ou interesse em identificá-las.|N|?|?|
|3|Sigla da Unidade Organizacional|?|object|Reunião das letras iniciais dos vocábulos fundamentais de uma denominação ou título, sem articulação prosódica, constituindo meras abreviaturas. Ex.: "DITEC", "GBASE", "DIREO", "PRESI", etc.|N|?|?|
|4|Nome da Unidade Organizacional Reduzido|?|object|Nome reduzido da Unidade Organizacional.|N|?|?|
|5|Código da Dependência da Vice-Presidência|?|Int64|Código identificador da Dependência da Vice-Presidência jurisdicionante da UOR.|N|?|?|
|6|Sigla da Vice-Presidência|?|object|Sigla da Vice-Presidência jurisdicionante da UOR.|N|?|?
|7|Quantidade Total de Funcionários da Unidade Organizacional|?|Int64|Quantidade total de funcionários localizados na UOR|N|?|?|
|8|Indicador de Unidade Organizacional Alvo da Análise|?|object|Indica se a UOR é alvo da análise. Possíveis valores: "S" ou "N". |N|?|?|
|9|Índice de Atingimento do Indicador no Primeiro Semestre|?|float64|Indicativo do percentual de atingimento do indicador no primeiro semestre, caso a UOR seja alvo da análise. Varia de 0 a 1, com duas casas decimais.|S|?|?|
|10|Índice de Atingimento do Indicador no Segundo Semestre|?|float64|Indicativo do percentual de atingimento do indicador no segundo semestre, caso a UOR seja alvo da análise. Varia de 0 a 1, com duas casas decimais.|S|?|?|

<b>Regras gerais:</b>
    
- deverão ser listadas apenas as UORs que possuem Vice-Presidência vinculada.

- verifique os prefixos alvo da análise na descrição do desafio.

Considere as regras abaixo para apuração do cumprimento do indicador para cada um dos prefixos alvo da análise:

<b>Regras de apuração individual</b>: o indicador será considerado cumprido para os funcionários que:
- completarem o mínimo de 20 horas total de cursos, sendo no mínimo 10h de treinamentos da Trilha Estratégica, realizados dentro do semestre de apuração
- tiverem cumprido toda a Trilha Estratégica na data de apuração, desde que tenha cumprido o mínimo de 20 horas total no semestre de apuração

<b>Regra de apuração por prefixo</b>: o indicador será considerado cumprido para os prefixos que tiverem 90% do público avaliável com o indicador cumprido no semestre.

<b><<< Parte 2 >>></b>

Considerando as regras de apuração acima, responda às perguntas abaixo tomando por base a apuração do primeiro semestre:

    a) quais os prefixos que cumpriram o indicador?

    b) qual o prefixo com menor índice de cumprimento do indicador?

    c) qual o prefixo com o maior índice de cumprimento do indicador?

    d) qual o prefixo com o menor índice de funcionários não avaliáveis?

    e) qual o maior índice de funcionários não avaliáveis dentre os observados nos prefixos avaliados?

Ao final do exercício, deverá ser criada uma variável para cada um dos itens acima, sendo o nome e o tipo delas conforme abaixo detalhado:

|Item|Nome da variável|Tipo de objeto|
|---|---|---|
|a)|exercicio10a|variável do tipo list, itens do tipo int|
|b)|exercicio10b|int|
|c)|exercicio10c|int|
|d)|exercicio10d|int|
|e)|exercicio10e|float (2casas decimais)|

<b>Regra 1:</b> utilize a função round() para eventuais arredondamentos.

<b>Regra 2:</b> em caso de empate, o desempate será pela maior quantidade de funcionários avaliáveis no prefixo.

# Boletim de soluções

In [159]:
# importar bibliotecas para geração dos artefatos
import pickle

In [160]:
# Favor não alterar esta célula
# verificar a existência das variáveis e gerar artefatos para verificação
if 'exercicio1' in globals():
    print('DataFrame exercicio1 localizado. Ele poderá ser enviado para validação.')
    with open(f'{chaveF}_exercicio1.pkl','wb') as f:
        pickle.dump(exercicio1, f)
else:
    print('O exercício 1 não tem condições de ser avaliado.')

if 'exercicio2' in globals():
    print('DataFrame exercicio2 localizado. Ele poderá ser enviado para validação.')
    with open(f'{chaveF}_exercicio2.pkl','wb') as f:
        pickle.dump(exercicio2, f)
else:
    print('O exercício 2 não tem condições de ser avaliado.')

if 'exercicio3' in globals():
    print('DataFrame exercicio3 localizado. Ele poderá ser enviado para validação.')
    with open(f'{chaveF}_exercicio3.pkl','wb') as f:
        pickle.dump(exercicio3, f)
else:
    print('O exercício 3 não tem condições de ser avaliado.')

if 'exercicio4' in globals():
    print('DataFrame exercicio4 localizado. Ele poderá ser enviado para validação.')
    with open(f'{chaveF}_exercicio4.pkl','wb') as f:
        pickle.dump(exercicio4, f)
else:
    print('O exercício 4 não tem condições de ser avaliado.')

if 'exercicio5' in globals():
    print('DataFrame exercicio5 localizado. Ele poderá ser enviado para validação.')
    with open(f'{chaveF}_exercicio5.pkl','wb') as f:
        pickle.dump(exercicio5, f)
else:
    print('O exercício 5 não tem condições de ser avaliado.')

if 'exercicio6' in globals():
    print('DataFrame exercicio6 localizado. Ele poderá ser enviado para validação.')
    with open(f'{chaveF}_exercicio6.pkl','wb') as f:
        pickle.dump(exercicio6, f)
else:
    print('O exercício 6 não tem condições de ser avaliado.')

if 'exercicio7' in globals():
    print('DataFrame exercicio7 localizado. Ele poderá ser enviado para validação.')
    with open(f'{chaveF}_exercicio7.pkl','wb') as f:
        pickle.dump(exercicio7, f)
else:
    print('O exercício 7 não tem condições de ser avaliado.')

if 'exercicio8' in globals():
    print('DataFrame exercicio8 localizado. Ele poderá ser enviado para validação.')
    with open(f'{chaveF}_exercicio8.pkl','wb') as f:
        pickle.dump(exercicio8, f)
else:
    print('O exercício 8 não tem condições de ser avaliado.')

if 'exercicio9' in globals():
    print('DataFrame exercicio9 localizado. Ele poderá ser enviado para validação.')
    with open(f'{chaveF}_exercicio9.pkl','wb') as f:
        pickle.dump(exercicio9, f)
else:
    print('O exercício 9 não tem condições de ser avaliado.')


exercicio10_variaveis = {}

exercicio10_variaveis['variavel'] = []
exercicio10_variaveis['valor'] = []
if 'exercicio10a' in globals():
    exercicio10_variaveis['variavel'].append('exercicio10a')
    exercicio10_variaveis['valor'].append(exercicio10a)
if 'exercicio10b' in globals():
    exercicio10_variaveis['variavel'].append('exercicio10b')
    exercicio10_variaveis['valor'].append(exercicio10b)
if 'exercicio10b' in globals():
    exercicio10_variaveis['variavel'].append('exercicio10c')
    exercicio10_variaveis['valor'].append(exercicio10c)
if 'exercicio10d' in globals():
    exercicio10_variaveis['variavel'].append('exercicio10d')
    exercicio10_variaveis['valor'].append(exercicio10d)
if 'exercicio10e' in globals():
    exercicio10_variaveis['variavel'].append('exercicio10e')
    exercicio10_variaveis['valor'].append(exercicio10e)

exercicio10_variaveis = pd.DataFrame(exercicio10_variaveis)
if exercicio10_variaveis.shape[0] == 5 and 'exercicio10' in globals():
    print('DataFrame exercicio10 localizado. Ele poderá ser enviado para validação.')
    print('Variáveis exercicio10a, exercicio10b, exercicio10c, exercicio10d e exercicio10e localizadas. Elas poderão ser enviadas para validação.')
    with open(f'{chaveF}_exercicio10_variaveis.pkl','wb') as f:
        pickle.dump(exercicio10_variaveis, f)
    with open(f'{chaveF}_exercicio10.pkl','wb') as f:
        pickle.dump(exercicio10, f)

else:
    print('O exercício 10 não tem condições de ser avaliado.')

DataFrame exercicio1 localizado. Ele poderá ser enviado para validação.
DataFrame exercicio2 localizado. Ele poderá ser enviado para validação.
DataFrame exercicio3 localizado. Ele poderá ser enviado para validação.
DataFrame exercicio4 localizado. Ele poderá ser enviado para validação.
DataFrame exercicio5 localizado. Ele poderá ser enviado para validação.
DataFrame exercicio6 localizado. Ele poderá ser enviado para validação.
DataFrame exercicio7 localizado. Ele poderá ser enviado para validação.
DataFrame exercicio8 localizado. Ele poderá ser enviado para validação.
DataFrame exercicio9 localizado. Ele poderá ser enviado para validação.
O exercício 10 não tem condições de ser avaliado.